### ISSUE TITLE
Tools 

### ISSUE THREAD

**Issue by di48l069** [dmustanger/7dtd-ServerTools#1]
Good day man, love your 7dtd tools they epic, check out https://github.com/di48l069/CraftAdmin im considering of making a plugin manager and implementing your tools so user can have ability to turn them off or on :+1:

**Comment by dmustanger** [comment]
:D thanks let me know if you need anything

**Comment by di48l069** [comment]
@dmustanger where did you get list of illegal items?

**Comment by di48l069** [comment]
@dmustanger hey man would you like to integrate a plugin system into my application so people can use your plugins?

**Comment by dmustanger** [comment]
sure just let me know what i need to do

**Comment by di48l069** [comment]
@dmustanger Take a look at my basic 7dtd Manager would be nice if we had a plugin manager where people can download your tools and can add them to application and they can use it.

**Comment by di48l069** [comment]
Im just not sure how we would do this???
