### ISSUE TITLE
No Z Axis on /sethome and /home

### ISSUE THREAD

**Issue by Aersaud** [dmustanger/7dtd-ServerTools#10]
There is no Z axis stored for the home command thus you will end up on the highest elevation possible where you /sethome.

**Comment by dmustanger** [comment]
This is working as intended. If we set the z axis you fall through the world.

**Comment by Aersaud** [comment]
The only down side is when you /home and lets say your house is multiple stories you will teleport onto the roof rather than where you established home at with the /sethome command.

**Comment by dmustanger** [comment]
this has been fixed 
https://github.com/dmustanger/7dtd-ServerTools/commit/c6dca3b8a9e01306775ba00d3a20b06366b270aa
