### ISSUE TITLE
 Lack of documents Mogul.cs

### ISSUE THREAD

**Issue by hugoshao** [dmustanger/7dtd-ServerTools#102]
When I downloaded 7dtd-ServerTools, I couldn't find the file Mogul.cs

**Comment by ObsComp** [comment]
https://github.com/dmustanger/7dtd-ServerTools/tree/master/ServerTools/src/ChatCommands

It is there. I just checked for it.

There are two different things you can download. You can download the source code or the compressed zip file that contains just the files needed to run ST on a server.
