### ISSUE TITLE
Clan commands

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#106]
Please add commands fo clans:
/listclans - all clans list
/clansplayers clanname - list players in clan with name
/clanofficers clanname - list oficers in clan with name
/clanowner clanname - see clan owner
/clancolor clanname - color for prefix
/clantp name - teleport to clanname point with cost
/addclantp name -  add teleport point for clan players (for admins, owner and officer only)
/delclantp name

**Comment by ObsComp** [comment]
/clanlist has been added as a command

I will be doing an update with the rest of them soon.
