### ISSUE TITLE
maxping not working

### ISSUE THREAD

**Issue by StefanRed** [dmustanger/7dtd-ServerTools#11]
Hey there, thank you for your mod!
the RAT tool made my server laggy so I tried your mod, it works nice but it doesn't kick / ban ppl with a ping higher then the set one.
I want it to kick / ban them if the ping is higher then 250 but I have many visitors around 300 or higher.

I am using 7dtd server manager 8.01, could this be a conflict?

~Stefan

**Comment by dmustanger** [comment]
Most llikely user error as high ping kicker is working proper. Check the log output for errors
