### ISSUE TITLE
Block for mobs or item spawner

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#115]
Detect the block placed by the player with the name specified in the configuration file, for the appearance of the mobs or items at the specified time.

admin commands for example:
/addspawner spawnername blockname mobtype/itemtype counts interval spawnradius detectplayerradius cost permissions 

/delspawner spawnername

A block with the specified name can be place on the ground by any player

**Comment by dmustanger** [comment]
as quoted from your first one

"I do not want to link into the world blocks list until A17 is out with the refined world generation and new block code. The current internal code to make this feature is messy and might prove very difficult. I will keep it in mind though."
