### ISSUE TITLE
Zones PvP vs noZombie

### ISSUE THREAD

**Issue by raptikCZ** [dmustanger/7dtd-ServerTools#120]
Hello, 
i have some strange behavior with setting up of zones.
it looked, that function of PvE and noZombie are swaped.
when i turn PvE true, then zombies are deleted from zone, but no Jail/kill reaction when player is killed
when i turn noZombie true, zombies remain in zone, but jail and kill reactions works fine

same behavior on ST ver. 11 and 11.1
Alocs fixes ver, 14-17-26 (command - common - webandmap)
copis addition ver 3.6
in testing proccess i simplified zones settings to this:

`<?xml version="1.0" encoding="UTF-8"?>
<Zones>
    <Zone>
        <zone corner1="-10000,-56,10000" corner2="10000,200,0" entryMessage="Severni strana - PvP" exitMessage="Opoustis Severni stranu - PvP" response="" reminderNotice="Jsi na Severu v PvP" circle="False" PvE="False" noZombie="False" />
        <zone corner1="-10000,-56,-10000" corner2="10000,200,1" entryMessage="Jizni strana - PvE" exitMessage="Opoustis Jizni stranu - PvE" response="" reminderNotice="Jsi na Jihu v PvE" circle="False" PvE="True" noZombie="False" />
    </Zone>
</Zones>`

Thank you for reply and time

**Comment by ObsComp** [comment]
Interesting. I will put this back into testing and see whats going on. Thanks for the heads up

**Comment by ObsComp** [comment]
I found the error and just released 11.2 with the fix and some others. Thanks again.
