### ISSUE TITLE
mute list error

### ISSUE THREAD

**Issue by raptikCZ** [dmustanger/7dtd-ServerTools#126]
hello,
when i set mute commands = true 
`        <Tool Name="Chat_Command_Response" Server_Response_Name="[FFCC00]ZapRa" Color="[00FF00]" Chat_Command_Private="/" Chat_Command_Public="!" Mute_Commands="True" />`

and when i run command _mute list_ i got this in log:

`2018-09-22T22:10:32 21145.115 INF [SERVERTOOLS] Error in ConsoleCommandMuteConsole.Run: System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
  at System.Collections.Generic.List`1[System.String].get_Item (Int32 index) [0x00000] in <filename unknown>:0
  at ServerTools.MutedConsole.Execute (System.Collections.Generic.List`1 _params, CommandSenderInfo _senderInfo) [0x00000] in <filename unknown>:0 .
`

1 steamid is in list - no list generated, mute not working for that steamid

ST 11.2
Alocs fixes ver, 14-17-26 (command - common - webandmap)
copis addition ver 3.6

Thanks for help

**Comment by dmustanger** [comment]
yea after looking at the mute code it needs to be re worked after the database move. we will get to it asap

**Comment by ObsComp** [comment]
Fix for this added to 11.4
