### ISSUE TITLE
"Kick or Beware" on "excessive collapse" proposal

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#127]
Hello, This week our server was deleted by the hoster. The reason was supposedly permanent excessive CPU load. Triggered by permanent collapse let various blocks. My question is, could one incorporate monitoring of the players that cause this with possibly a kick option?
Greeting (Google Translate)

**Comment by dmustanger** [comment]
kicking still wont solve the 100% cpu usage. It is a mechanic that the developers (The Fun Pimps) need to address.
