### ISSUE TITLE
PVP zone with penalty, PVE without

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#128]
Hello, we have planned cities as a PVP zone, but unfortunately the following does not work here. Error1: Outside the zone "player kills player" no penalty, within the zone "player kills player" penalty occurs. Setting Config: Jail_Enabled = "True"; Zones: PvE = "false"; The same with Zones: PvE = "true". Error2: If the killer is in jail and the victim types "/ forgive" he will get the message "this player is not in jail". And I have to free the killer via the console. Attached my XML files. Greetings...

[XMLs.zip](https://github.com/dmustanger/7dtd-ServerTools/files/2431892/XMLs.zip)

**Comment by ObsComp** [comment]
Zones are not pvp/pve. They are whatever you set the world to but you have the option of penalizing players who start to do pvp inside of one by setting that zone to pve.

I will look into the jail issue

**Comment by JoeWenger1** [comment]
Hello again, We have tried to generate a zone where PVP is allowed. With "PVE = false". But it is punished exactly the wrong Side. "PVE = True" does not change that. You are always punished outside the zone. And unfortunately, a new bug with version 11.4 has been added. Entering a zone has no entry Message now, and second I think only circle works, but not yet tested exactly. Greetings

**Comment by JoeWenger1** [comment]
I have understood it now. Here is my little manual. We wanted cities as PVP zones and the rest as PVE. First I entered the whole map (zone corner1="0,0,0" corner2="9999", PVE=True). Then I entered my city ( example corner1="2647,0,4447" corner2="1358,150,3332", PVE=False). I had assumed that this setting would overlap and not work. So everything worked correctly! Sorry my mistake.
