### ISSUE TITLE
No Zone entry messages are displayed anymore

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#129]
**Describe the bug**
Since version 11.4, no zone messages are displayed anymore

**How To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows Server 2016]
 - ServerTools Version [e.g. 11.5]

**Additional context**

UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!
[output_log.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2438855/output_log.txt)

**Comment by ObsComp** [comment]
Fallback handler could not load library D:/home/sid_522772/sevenDays/7DaysToDieServer_Data/Mono/x86_64/libc
Fallback handler could not load library D:/home/sid_522772/sevenDays/7DaysToDieServer_Data/Mono/x86_64/.\libc
Fallback handler could not load library D:/home/sid_522772/sevenDays/7DaysToDieServer_Data/Mono/x86_64/libc

I can see the database is not being loaded. This is a problem we are seeing on linux systems. You must allow permission to those folders for the 7 days to utilize. It is a permissions problem.

**Comment by JoeWenger1** [comment]
These 3 error messages have all. See: https://7daystodie.com/forums/showthread.php?79004-fallback-handler-could-not-load-library. I have now created a "Dedicated Server" on a Windows machine for testing, all Vanilla. With the same result. 11.3 zone messages are working, 11.4 zone messages are no longer working.

**Comment by ObsComp** [comment]
Ok sorry Joe, that was my error. I shifted something in the code in 11 and it broke it. I have fixed it for 11.6 which we will release today. Thank you for the report!

**Comment by VitalGrigoryev** [comment]
11.7 Server2008 sp2 64
no zone messages are displayed anymore
