### ISSUE TITLE
Hard coded entities in day7 command

### ISSUE THREAD

**Issue by StompyNZ** [dmustanger/7dtd-ServerTools#13]
In day7.cs the checks use the entity class name which means on a modded server this function won't work correctly.

A better way to handle it would be to look at the entity.GetType() instead. Returns EntityPlayer, EntityZombie, EntityAnimal etc (as per the Class setting in entityclasses.xml)

**Comment by MkxTrax** [comment]
Hey Stompy. This Mod is starting to struggle now have you a personal fix. ill get it from you =?

**Comment by dmustanger** [comment]
This part of the mod is working as intended. If people mod the server from vanilla  they should edit the source code and rebuild to fit their needs
