### ISSUE TITLE
Kick/Ban Voting enhancements

### ISSUE THREAD

**Issue by stevotvr** [dmustanger/7dtd-ServerTools#130]
Kick voting is useful for times when no admins are present, but it can also be abused. It's also not very effective if the player can immediately reconnect.

So I propose two enhancements to address these issues:
- Add an access level restriction option to voting commands
- Add a ban vote with a configurable duration

**Comment by dmustanger** [comment]
adding an access level kinda defeats the purose
we can add a temp ban option

**Comment by stevotvr** [comment]
I don't think it defeats the purpose. What if you only want people that you know have vote access without giving everyone access? Every other server management system I have used has this flexibility, and I think it would add value to this one.

**Comment by ObsComp** [comment]
I added a 5 minute wait period when people are kicked for a reserved slot. I thought I did for kick vote too but I will add something for 13.1
