### ISSUE TITLE
"/forgive to release the killer from jail" not work

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#131]
**Describe the bug**
If the killer is in jail and the victim types "/ forgive" he will get the message "this player is not online and so can not be forgiven or removed from Jail". And I have to free the killer via the console.

**How To Reproduce**
Kill a Player in a PVE Zone

**Expected behavior**

**Screenshots**
![alpha_16 4_2018-10-08_18-50-12](https://user-images.githubusercontent.com/43305712/46622741-de651980-cb2b-11e8-90f4-5a1ee5cd501c.jpg)
![alpha_16 4_2018-10-08_18-49-44](https://user-images.githubusercontent.com/43305712/46622742-de651980-cb2b-11e8-8dba-b87a662dedec.jpg)

**Desktop (please complete the following information):**
 - ServerTools Version [e.g. 11.6]

**Additional context**

UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!
[output_log__2018-10-08__18-35-28.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2456888/output_log__2018-10-08__18-35-28.txt)

**Comment by ObsComp** [comment]
I have updated the responses so as to no give a false positive if it did not attempt to remove them from jail. Your output log does not show anyone trying to forgive them and release them. Please provide an output log of that event for us. I will close this for now, please open a new one with the output log if it is still an issue.
