### ISSUE TITLE
Please add Phrases for Kill an Jail Funktion

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#132]
**Is your feature request related to a problem? Please describe.**
Hello, can you add Phrases for the Jail Funktion? Then our Translation is perfekt. 
Examples: type /return to teleport back to your death position. There is a time limit. | Type /forgive to relaise your killer from jail. | Your killer has been forgiven. ...  

Many Thanks for your great work! 
Joe

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ObsComp** [comment]
I will mark this down for 13.1

I am going to redo all of the phrases and add the missing ones
