### ISSUE TITLE
Wish for a new say command

### ISSUE THREAD

**Issue by Ganktimebaby** [dmustanger/7dtd-ServerTools#134]
Hi!

i have the wish for a new say command like /saye for sayempty 

this command is like the normal telnet/console /say but without Server:    
only for admins for special texts and macros at telnet ;))

thanks and hope u know what i mean

**Comment by ObsComp** [comment]
You specifically want the Server: suppressed from the response then?

**Comment by Ganktimebaby** [comment]
Yes i changed it with scriptingmod but it works Not in a17.

;)

Like /zsay Text 

And ingame u read only Text 
Thats great for Server rules bot messeges and and and 
I can later post my script from a16 but it was in js.
And im not good in c# 

Thanks

**Comment by ObsComp** [comment]
you specifically want something like the command say that broadcasts to the whole server but doesnt show the name Server:    is that correct?
