### ISSUE TITLE
Command "mute add" does not work

### ISSUE THREAD

**Issue by zelenovas** [dmustanger/7dtd-ServerTools#135]
**Describe the bug**
Command "mute add" working only for some seconds, not even for 1 minute, even if you set 30 minutes in command. When you use "mute list" command right after "mute add" you see added player name and time for mute, but SteamID  is "0" (maybe it's just some typo in code). But after some seconds there is no one in "mute list", no matter what time you set in command "mute add". And of course player can chatting.

**How To Reproduce**
1. Enter command in game console or via telnet: **mute add SteamID 999**
_(server response is correct)_
2. Enter command in game console or via telnet: **mute list**
_(server response is not so correct, steam id equals 0)_
3. After about 30 seconds enter command in game console or via telnet: **mute list**
_(mute list will be empty and player can chatting)_

**Expected behavior**
Player can't chat for 999 minutes.
Mute list contains player's SteamID and name with minutes left for mute.

**Screenshots**
No screenshots.

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 16.04.2 LTS (x64)
 - ServerTools Version: 11.8 or 11.7 (tested on both)

**Additional context**
MySQL enabled, configured and works, but field "isMuted" is not changable via command "mute add".
Manually changing field "isMuted" to "true" does not help, player can chat.

[output_log__2018-11-04__06-44-10.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2545554/output_log__2018-11-04__06-44-10.txt)

**Comment by ObsComp** [comment]
I received a another report about this. I will double check if it exists in V12. If it is working I will close this message. Thank you for the report

**Comment by zelenovas** [comment]
Hm... and what about Server Tools for Alpha 16? Can you fix that for v11.* too? Thanks.

**Comment by ObsComp** [comment]
I believe this is fixed now. Please report it again if you are still seeing issues.

**Comment by xorex** [comment]
ST 12.95 
only one minute mute work good
`mute add 76561199999999999 30

Steam Id 76561199999999999, player name Tester has been muted for 30 minutes.
2019-03-13T03:48:54 234.660 INF Chat handled by mod 'Server Tools': Chat (from '76561199999999999', entity id '171', to 'Global'): 'Tester': test
2019-03-13T03:49:38 279.012 INF Chat handled by mod 'Server Tools': Chat (from '76561199999999999', entity id '171', to 'Global'): 'Tester': test
2019-03-13T03:49:39 280.045 INF Chat handled by mod 'Server Tools': Chat (from '76561199999999999', entity id '171', to 'Global'): 'Tester': test
2019-03-13T03:49:55 296.267 INF Chat (from '76561199999999999', entity id '171', to 'Global'): 'Tester': test`
