### ISSUE TITLE
wallet/bank not working

### ISSUE THREAD

**Issue by cmenchion** [dmustanger/7dtd-ServerTools#136]
**Describe the bug**
I type:
/wallet in chat tells me I have 4040 in my wallet
/bank does not work, unless i use full steam id in the console screen, It shows white in chat
/wallet deposit 1 or withdraw 1 shows white in chat and does not work either in console

**How To Reproduce**
Turn on both wallet and bank, edit the coin to casinoCoin for both the bank and wallet, Turn off inside_claim, save config and save game and restart. 

**Expected behavior**
I expect what the chest one secure one wood I tried would deposit or withdraw something. It seems killing zombies adds to the wallet.
![1](https://user-images.githubusercontent.com/3522103/48453573-a4241300-e78e-11e8-8706-cd7183de7114.png)
![2](https://user-images.githubusercontent.com/3522103/48453575-a5edd680-e78e-11e8-8d03-1788e8baa615.png)

**Screenshots**

**Desktop (please complete the following information):**
2 week old install Win7
Intel 4770
16GB Ram
2xNvidia 770 oc's

**Additional context**
I also have Valmar's expansion pack.

I have no log.???

**Comment by ObsComp** [comment]
All seems to be working in test now. Thank you.

**Comment by PauloAlmas** [comment]
I'm in my land claim and the above is not working, i'm in my lan claim and type says 2720, i'm front my chest and type 
/deposit 100
it says:
...you canot use this command here. stand in your own or friend's claimed space.
 /wallet deposit  
the same

**Comment by ObsComp** [comment]
There is an issue with the claim process at the moment that I need to sort out. It will be in the next patch I am working on. Sorry for the problems

________________________________
