### ISSUE TITLE
Personal message when entering a specific region.

### ISSUE THREAD

**Issue by Monomir** [dmustanger/7dtd-ServerTools#138]
Hi Dmustanger! Thanks for your work.
On Alpha 17 there are certain problems with the random generator of the world and as I see many servers use Navezgane.
And as you understand there are problems with the number of loot.
Tell me, is it possible to somehow configure the Server Tool, so that I can specify certain coordinates or regions that will wipe and that the players entering into them receive a message in personal messages that it is undesirable to build a base in this territory, so how will it be reset?

PS I apologize for my english, i use google translate

**Comment by dmustanger** [comment]
not at the moment. once we have the bugs fixed for a17 we can look into adding this
