### ISSUE TITLE
Gimme System do not work

### ISSUE THREAD

**Issue by Patrick9091** [dmustanger/7dtd-ServerTools#15]
in Console Shows any item pick up but no item in inventory
please help

**Comment by dmustanger** [comment]
need more info.
have you updated to the latest version?
do you have errors in your log files?
are you picking the item up from the ground as it drops at your feet?

**Comment by Patrick9091** [comment]
use 3.10 with 3.09 dont work too
log: 2017-08-08T00:39:06 120569.182 INF GameMessage handled by mod 'Server Tools': Chat: 'XXX': /gimme
nothing more
no item in my inventory, no item drop on the ground

**Comment by dmustanger** [comment]
still need more info here.
are you on windows or linux?
can you post a full log output file?

**Comment by drphlux** [comment]
@Patrick9091 Did you remember to set:

```
-bash-4.2$ grep Gimme ServerToolsConfig.xml 
        <Tool Name="Gimme" Enable="True" DelayBetweenGimmeUses="60" AlwaysShowResponse="True" />
```

It was broken with 3.9, but startet working again with 3.10.

**Comment by Patrick9091** [comment]
Windows

**Comment by Patrick9091** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<ServerTools>
    <Version>
        <Version Version="3.1" />
    </Version>
    <Tools>
        <Tool Name="AdminChatCommands" Enable="False" PermissionLevelForMute="0" />
        <Tool Name="AdminNameColoring" Enable="True" AdminLevelNeeded="0" AdminPrefix="(ADMIN)" AdminColor="[FF0000]" ModeratorLevelNeeded="1" ModeratorPrefix="(MOD)" ModeratorColor="[008000]" />
        <Tool Name="AnnounceInvalidItemStack" Enable="False" />
        <Tool Name="AutoSaveWorld" Enable="True" DelayBetweenWorldSaves="10" />
        <Tool Name="BadWordFilter" Enable="False" />
        <Tool Name="ChatFloodProtection" Enable="False" />
        <Tool Name="ChatLogger" Enable="True" />
        <Tool Name="ClanManager" Enable="True" />
        <Tool Name="CustomCommands" Enable="False" ChatColor="[00FF00]" />
        <Tool Name="Day7" Enable="False" />
        <Tool Name="Gimme" Enable="False" DelayBetweenGimmeUses="60" AlwaysShowResponse="False" />
        <Tool Name="HighPingKicker" Enable="True" Maxping="200" SamplesNeeded="0" />
        <Tool Name="InfoTicker" Enable="True" DelayBetweenMessages="10" />
        <Tool Name="InvalidItemKicker" Enable="True" Ban="True" />
        <Tool Name="Killme" Enable="False" DelayBetweenKillmeUses="60" />
        <Tool Name="Motd" Enable="True" Message="Welcome to [DE] 7 Days to Die - Just Survive - NO WIPE! {PlayerName} !" />
        <Tool Name="ReservedSlots" Enable="False" />
        <Tool Name="SetHome" Enable="True" DelayBetweenSetHomeUses="120" />
        <Tool Name="Watchlist" Enable="False" />
    </Tools>
</ServerTools>`

**Comment by Patrick9091** [comment]
<Tool Name="Gimme" Enable="False" DelayBetweenGimmeUses="60" AlwaysShowResponse="False" />

**Comment by Patrick9091** [comment]
code
<Tool Name="Gimme" Enable="True" DelayBetweenGimmeUses="60" AlwaysShowResponse="False" />

**Comment by Patrick9091** [comment]
`<Tool Name="Gimme" Enable="False" DelayBetweenGimmeUses="60" AlwaysShowResponse="False" />`

**Comment by zelenovas** [comment]
/gimme doesn't work only if I use "cpc" command to change my name color in chat, but when I set color to default color FFFFFF /gimme works fine.

**Comment by Patrick9091** [comment]
ok works now
1. deactivate admincoloring
2. rename         <item item="coffeBeans" min="1" max="5" /> to         <item item="coffeeBeans" min="1" max="5" />

**Comment by dmustanger** [comment]
yea coppi mod and mine do not work good together since we both use chat hooks
