### ISSUE TITLE
Multiple error with 17.1

### ISSUE THREAD

**Issue by thomasbonsirven** [dmustanger/7dtd-ServerTools#152]
Hello,

After update server to 17.1 I have a multiple error.

That is for events : ( look screenshot )

![screenshot_20190125-131037](https://user-images.githubusercontent.com/18753454/51745381-e88f3180-20a2-11e9-91bd-3f206e5e95b1.jpg)

Thanks in advance

**Comment by ObsComp** [comment]
I have not used the new terminal window yet. I will look in to this. Thank you for the report.

**Comment by thomasbonsirven** [comment]
Hello,

In the game or with telnet is same problem!
