### ISSUE TITLE
CentOS 7: ServerTools failed to connect to an sql database. ST requires this to operate.

### ISSUE THREAD

**Issue by XelaNull** [dmustanger/7dtd-ServerTools#153]
**Describe the bug**
Fresh install of 7DaysToDie on CentOS7 with ServerTools results in error in the game server logs:
`Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.so
                                                                                                                                                         322,1         88%
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/SQLite.Interop
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/./libSQLite.Interop.dll.so
Fallback handler could not load library /data/7DTD/7DaysToDieServer_Data/Mono/x86_64/libSQLite.Interop.dll
2019-02-02T14:04:32 23.135 INF ServerTools failed to connect to an sql database. ST requires this to operate.
2019-02-02T14:04:32 23.188 INF ---------------------------------------------------------------
2019-02-02T14:04:32 23.188 INF [SERVERTOOLS] Verifying configuration file & Saving new entries
2019-02-02T14:04:32 23.188 INF ---------------------------------------------------------------
2019-02-02T14:04:32 23.200 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"
2019-02-02T14:04:32 23.200 EXC Object reference not set to an instance of an object
NullReferenceException: Object reference not set to an instance of an object
  at ServerTools.MySqlDatabase.TQuery (System.String _sql) [0x00000] in <filename unknown>:0
  at ServerTools.SQL.TQuery (System.String _sql) [0x00000] in <filename unknown>:0
  at ServerTools.Mods.Load () [0x00000] in <filename unknown>:0
  at ServerTools.LoadProcess.Load (Int32 _state) [0x00000] in <filename unknown>:0
  at ServerTools.LoadProcess.Load (Int32 _state) [0x00000] in <filename unknown>:0
  at ServerTools.LoadProcess.Load (Int32 _state) [0x00000] in <filename unknown>:0
  at ServerTools.LoadProcess.Load (Int32 _state) [0x00000] in <filename unknown>:0
  at ServerTools.LoadProcess.Load (Int32 _state) [0x00000] in <filename unknown>:0
  at ServerTools.API.GameStartDone () [0x00000] in <filename unknown>:0
  at ModEvent.Invoke () [0x00000] in <filename unknown>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
Logger:masterLogException(Exception)
Logger:Exception(Exception)
Log:Exception(Exception)
ModEventAbs`1:LogError(Exception, Receiver)
ModEvent:Invoke()
<startGameCo>c__Iterator1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

(Filename:  Line: -1)

2019-02-02T14:04:32 23.206 INF StartGame done
2019-02-02T14:04:35 26.115 INF [Steamworks.NET] GameServer.Init successful
2019-02-02T14:04:35 26.120 INF [Steamworks.NET] Making server public`

**How To Reproduce**
1. Install 7DaysToDie game server on CentOS 7
2. Unzip 7dtd-ServerTools-12.7.zip inside the root of the 7DaysToDie installation directory.
3. Start 7DaysToDie

**Expected behavior**
ServerTools should utilize the built-in sqlite to create any needed databases. As a fall-back, I should be able to edit the ServerToolsConfig.xml and enable MariaDB/MySQL support, but that does not work either.

**Desktop (please complete the following information):**
[root@fbe7dd7cb1e0 7DTD]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[root@fbe7dd7cb1e0 7DTD]# ls -l *ServerTools*
-rw-r--r-- 1 root root 15501708 Dec 29 21:51 7dtd-ServerTools-12.7.zip

**Additional context**
The installation documentation for ServerTools does not explain how to utilize MySQL. I assumed that it only needed enabled within the ServerToolsConfig.xml file, but I also tried creating a databases to see if maybe ServerTools required that too.

<Tool Name="DataBase" EnableMySql="True
[7dtd.log](https://github.com/dmustanger/7dtd-ServerTools/files/2824485/7dtd.log)
" ServerHost="localhost" Port="3306" DatabaseName="ServerTools" UserName="root" Password="" />

[root@fbe7dd7cb1e0 7DTD]# mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.3.12-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> CREATE DATABASE ServerTools CHARACTER SET utf8 COLLATE utf8_general_ci;
Query OK, 1 row affected (0.001 sec)

MariaDB [(none)]> quit
Bye

**** Creating the database like above had no affect on the error message 

[root@fbe7dd7cb1e0 /]# rpm -qa | grep -i -e maria -e mysql -e sqlite | sort
MariaDB-client-10.3.12-1.el7.centos.x86_64
MariaDB-common-10.3.12-1.el7.centos.x86_64
MariaDB-compat-10.3.12-1.el7.centos.x86_64
MariaDB-server-10.3.12-1.el7.centos.x86_64
perl-DBD-SQLite-1.39-3.el7.x86_64
php72w-mysql-7.2.14-1.w7.x86_64
sqlite-3.7.17-8.el7.x86_64
sqlite-devel-3.7.17-8.el7.x86_64
sqlite-tcl-3.7.17-8.el7.x86_64

UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!

**Comment by XelaNull** [comment]
[7dtd.log](https://github.com/dmustanger/7dtd-ServerTools/files/2824501/7dtd.log)

**Comment by albiejames** [comment]
This issue is known and is currently being addressed. The authors will probably release a fix on the next major update. If you really want, you can try getting sqlite working at the least by downloading and implementing the sqlite-libs I posted here.
https://github.com/dmustanger/7dtd-ServerTools/issues/145#issuecomment-450664035
#145 
#150

**Comment by Wdrussell1** [comment]
I have been able to replicate this as well of course and would just like to update the issue and hope for a solution soon.

**Comment by XelaNull** [comment]
Here is a one-liner that can be run on an Ubuntu/Debian or CentOS system, from your 7dtd game server installation directory, that will patch ServerTools installation so it functions with Sqlite.

([[ -f /etc/redhat-release ]] && yum install gcc-c++ git -y || apt-get install g++ git -y) && rm -rf System.Data.SQLite && git clone https://github.com/moneymanagerex/System.Data.SQLite && cd System.Data.SQLite/Setup && /bin/bash ./compile-interop-assembly-release.sh && yes | cp -f ../SQLite.Interop/src/generic/libSQLite.Interop.so ../../7DaysToDieServer_Data/Mono/x86_64 && cd ../.. && echo "yes" && echo "libSQLite.Interop.so successfully copied into ../../7DaysToDieServer_Data/Mono/x86_64";

**Comment by Wdrussell1** [comment]
while i appreciate the fix. i honestly want to wait until he has an official fix. working with databases is a pain to have to redo everything. Just for the sake of being impatient.

**Comment by ObsComp** [comment]
Alright so the time has come linux user lol.

Latest release 12.94 has fixed for linux users in the zip file. This is for alpha 17.2
If you are still using 17.1, please use 12.72.
