### ISSUE TITLE
Bad word filter does not work

### ISSUE THREAD

**Issue by xorex** [dmustanger/7dtd-ServerTools#154]
Bad word filter does not work on ST 12.93. It worked fine on version 12.7, but did not work with non-Latin phrases or characters.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - ServerTools Version 12.93

There are no warnings or errors in the log file

**Comment by ObsComp** [comment]
I will have to look in to that. We didn't change anything that should have compromised it. Thank you for the report

**Comment by xorex** [comment]
I didn't change anything on the server, but it working fine atm. This may be due to a bug where system messages that should be sent to the pm, but are sent to a public chat. It doesn't happen often.
