### ISSUE TITLE
Night_Alert message not showing (12.94)

### ISSUE THREAD

**Issue by xorex** [dmustanger/7dtd-ServerTools#158]
Night_Alert message not showing.

**Desktop (please complete the following information):**
OS: Windows Server 2016
ServerTools Version 12.94

There are no warnings or errors in the log file.
Only latest server_fixes 352 Installed on server.

**Comment by ObsComp** [comment]
Okie, thanks man. I will write it down for tests

**Comment by xorex** [comment]
once saw a phrase, but unfortunately it does not appear if you set the time with the **settime** command, which makes testing difficult and time consuming)

**Comment by PauloAlmas** [comment]
on my server dont apper to :(

**Comment by ObsComp** [comment]
Are you still using 12.94? It has been updated well past that. I will double check that it works with the latest release tho

**Comment by PauloAlmas** [comment]
I'm using that latest version, is pre instaled in rented server : 
https://www.g-portal.com/
no message shown night alert, protected zone, ... only show the entering a server msg ...

**Comment by PauloAlmas** [comment]
have you tested ?

**Comment by PauloAlmas** [comment]
have you tested ?

**Comment by ObsComp** [comment]
No I have not yet

________________________________

**Comment by PauloAlmas** [comment]
i see no server shudler messages are send, only default ones enter server, new player, ...

**Comment by PauloAlmas** [comment]
can you see it ? i need it working, i may make donation if you put it work in my server, add me to discord ☠ArNaLdInHo☠#4871

**Comment by ObsComp** [comment]
https://discord.gg/6G8VZQg
This is the main discord channel for ServerTools
It has links if you wish to donate
It also has latest progress on an upcoming patch
You can make requests for features and bug fixes there
