### ISSUE TITLE
Jail Affecting Innocent People via Zone PVE/PVP

### ISSUE THREAD

**Issue by suL33T** [dmustanger/7dtd-ServerTools#163]
Innocent people are affected by party member's actions. So someone killed a person in a non PVE area and a person totally on a different part of the map in the same party got jailed.

**Comment by suL33T** [comment]
Yes, this person was also in the PVE zone but in a totally different grid.

**Comment by suL33T** [comment]
[output_log.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2969746/output_log.txt)
I've attached my log. Please look at where "Sgt.lee has killed Morytania with Iron Sledgehammer" is and directly below that. All three are in a party together. Unitatoe24 was not in the fight and was digging quite a ways away from where the fight happened.

Thanks!

**Comment by suL33T** [comment]
I've also attached my zones file


[zones.txt](https://github.com/dmustanger/7dtd-ServerTools/files/2969757/zones.txt)

**Comment by suL33T** [comment]
![servertools](https://user-images.githubusercontent.com/48467305/54413874-88853680-46b4-11e9-9f76-b38b3cb6810a.PNG)
servertools as well

**Comment by suL33T** [comment]
Actually realized this isn't limited to party members, it seems to be for whomever is in the same zone. Last night, someone died in a protected non PVP zone while I was in it and I got a message saying that I murdered them?

**Comment by suL33T** [comment]
[output_log (3).txt](https://github.com/dmustanger/7dtd-ServerTools/files/2974865/output_log.3.txt)
Another instance here, please look for "Player 'The Last Praetor' died" looks like they died of non PVP but someone got jailed anyway.

**Comment by raptikCZ** [comment]
I have similar problem...
there is jailed, killed, kicked or banned killer and victim - but we are just tested with two people on server...

> Game version: Alpha 17.2 (b27) Compatibility Version: Alpha 17.2
> Mod CSMM Patrons: 9.6.7
> Mod Allocs command extensions: 18
> Mod Allocs server fixes: 21
> Mod Allocs MapRendering and Webinterface: 31
> Mod Server Tools: 12.95

**Comment by ObsComp** [comment]
Thank you for the report. Version 13.0 has been released and should fix this along with many other bugs. Please feel free to report it again if you continue to have issues and I will make sure it is a priority fix.
