### ISSUE TITLE
Add Command for Zone

### ISSUE THREAD

**Issue by suL33T** [dmustanger/7dtd-ServerTools#166]
Please add a feature to allow users to use a command to let them know which zone they are in.

**Comment by Demon-MC** [comment]
please correct the command a /bike, not only works on bike
  <Tool Name="Vehicle_Teleport" Enable="true" Bike="true" Mini_Bike="true" Motor_Bike="true" Jeep="true" Gyro="true" Inside_Claim="True" Delay_Between_Uses="1" Command_Cost="0" />

**Comment by Demon-MC** [comment]
<Tool Name="Vehicle_Teleport" Enable="true" Bike="true" Mini_Bike="true" Motor_Bike="true" Jeep="true" Gyro="true" Inside_Claim="True" Delay_Between_Uses="1" Command_Cost="0" />

**Comment by ObsComp** [comment]
Ok, I can add that, thank you for the suggestion

**Comment by ObsComp** [comment]
Demon-MC I have added this to my testing for 13.1. Version 13.0 has just been released. Please try the command there. It should only teleport the minibike you have set as your saved bike. Each type should require the use of different commands such as /gyro. I will test and double check for the next release. Thank you for the report.
