### ISSUE TITLE
Zone /return Command

### ISSUE THREAD

**Issue by suL33T** [dmustanger/7dtd-ServerTools#174]
**Describe the bug**
Victim unable to use command /return upon death from a player in a PVE zone

**How To Reproduce**
Go in a PVE zone, have someone kill you (I had kill the murderer option turned on), then type /return upon spawning

**Expected behavior**
I expected the victim to be able to return to the death spot

**Screenshots**
Provided

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ServerTools Version 18.0.3

![Zone return Command](https://user-images.githubusercontent.com/48467305/67356381-d4cc0b00-f50e-11e9-8f5d-432b70ec3673.png)
[output_log (4).txt](https://github.com/dmustanger/7dtd-ServerTools/files/3760059/output_log.4.txt)

**Comment by dmustanger** [comment]
Ty we will look into this also

**Comment by ObsComp** [comment]
This has been fixed in 18.1.1
