### ISSUE TITLE
/waypoint PVP Check

### ISSUE THREAD

**Issue by suL33T** [dmustanger/7dtd-ServerTools#175]
**Describe the bug**
When PVP check is turned on for the /waypoint command, using it is impossible as it will return a phrase stating there is a non-ally nearby even when there isn't

**How To Reproduce**
Turn on the /waypoint command and have PVP check be True, then use a waypoint.

**Expected behavior**
A phrase will be returned stating there is a non-ally nearby and will not allow you to teleport

**Screenshots**
Provided (only two people in the server and Akayah is 1.5Km away -  command I used: /way home)
Last message there reads I traveled properly but this is after turning PVP check to false

**Desktop (please complete the following information):**
 - OS: Windows 10
 - ServerTools Version 18.0.3
![20191022235807_1](https://user-images.githubusercontent.com/48467305/67366803-03ef7600-f529-11e9-9020-2597b2de2027.jpg)
[output_log (5).txt](https://github.com/dmustanger/7dtd-ServerTools/files/3760692/output_log.5.txt)

**Comment by dmustanger** [comment]
Thank you, we will look into it

**Comment by dmustanger** [comment]
this is fixed in the next release

**Comment by Rival819** [comment]
Hi my friend and thank you for this great mod, I have an A20 dedicated server and I noticed that even if set to enabled, the Public waypoints wont work, I see the ones I configured in the xml when typing /way but it just wont teleport to them, I also noticed there his no public teleport command in CommandList.xml and also a completly missing information note on how to use it inside the "HowToSetup.txt" file, the public teleport infos are completly absent.  
<a href="https://freeimage.host/i/YIEXRe"><img src="https://iili.io/YIEXRe.th.png" alt="YIEXRe.th.png" border="0"></a>
