### ISSUE TITLE
Entity Clean up issue

### ISSUE THREAD

**Issue by MeredithSealy** [dmustanger/7dtd-ServerTools#177]
**Describe the bug**
Before the recent version update, I had made the Market and Lobby as Zombie free zones. (nozombie=true).  It was working fine. After installing to 18.1.4 however, it seems somehow this protected area is slipping to a different area of the map. I've checked the /loc for each corner in the Zones.xml for both the Lobby and Market. They are they correct coords. I've turned no zombies to False for now, because when I restarted the server, checked my coords, the issue continues.  The issue is that Server Tools is performing an Entity Cleanup on any Zombie in the area I've not set up as a Zone to begin with. 
**How To Reproduce**
Change the Lobby and Market to no_zombies=True produces Zombie despawning on areas of the map that have no Zones associated them. 

**Expected behavior**
no_zombies=True in the Market and Lobby (or any zone I set the /loc coords to, should only despawn zombies in those specific areas. 

**Screenshots**
![despawn log](https://user-images.githubusercontent.com/57696788/68732566-e3ec2900-05a1-11ea-8918-e0d99b1f19c9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows Server 2016]
 - ServerTools Version [e.g. 11.3]
Running on Serverblends hosting
Server Tools Version 18.1.4
[output_log.txt](https://github.com/dmustanger/7dtd-ServerTools/files/3839398/output_log.txt)

**Additional context**

UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!

**Comment by Uberlettuce** [comment]
I am having the same issue, tried a fresh zone file as well. Zombies spawn in, then they get de-spawned and re-spawned. I have shut of the zones for now.

**Comment by dmustanger** [comment]
thanks we will look at whats going on and try to have a fix out soon

**Comment by ObsComp** [comment]
Working in tests for new version 18.1.5
Please repost a new log if you are still having any issues with the Zone tool
