### ISSUE TITLE
Hardcore Mode

### ISSUE THREAD

**Issue by CBree** [dmustanger/7dtd-ServerTools#179]
Am I missing something with Hardcore mode on this script? I have set it to a single life with zero extra lives, but when a user dies, they are just respawning like they would normally?
From the HowToSetup.xml file "If they run out, their stats are recorded and they are kicked, then their player profile is deleted." - none of this is happening?

**Comment by CBree** [comment]
Oh, also... in my ServerToolsConfig.xml - there is no <Tool Name="Hatch_Elevator_Detector" Enable="False" /> variable?

This is all on the latest version of 18.1.6 running Ubuntu 18.04

**Comment by dmustanger** [comment]
we will look into hardcore mode. 

hatch elevator has been removed. there is no need for it now as hatch elevators dont work anymore.

**Comment by CBree** [comment]
Ahh, okay. It was still in the how to file, so thought something was going wrong. Much appreciated in looking into hardcore mode, it looks interesting.

**Comment by ObsComp** [comment]
Thank you for the heads up. I will look at this right now

**Comment by ObsComp** [comment]
Do you have optional set to true? That makes it where players must sign up for it by typing /hardcore on

**Comment by CBree** [comment]
I do, yes - tried various settings in that option
`<Tool Name="Hardcore" Enable="True" Optional="True" Max_Deaths="1" Max_Extra_Lives="0" Life_Price="2000" />`

That is what I currently have it set to.

**Comment by CBree** [comment]
Oops, didn't read that... will try now.

**Comment by ObsComp** [comment]
I have to redo the instructions entirely. They are very old and a lot has changed. Sorry for any confusion around it.

**Comment by CBree** [comment]
All good, and works as expected now. Much appreciate your help, thank you.

**Comment by ObsComp** [comment]
Woot awesome. I will update the instructions in the next update to help clear up any confusion. If you have issues, please feel free to post them. Have fun and enjoy ST.
