### ISSUE TITLE
report feature 

### ISSUE THREAD

**Issue by onykage** [dmustanger/7dtd-ServerTools#18]
just a suggestion.

Add a feature for /report to pull up a ui to allow the user to select a user and submit a comment about said user for a report.  say grab the last 50 lines of the log and store it with the request in a txt file.

mebbe make this accessable to the allocs web fixes to be displayed somewhere in there??  reaching here.

ps...  id like to contribute..  can I do that?

**Comment by ObsComp** [comment]
Interesting idea. We have a GUI being worked on for 6.0. I will keep this in mind for that project.

**Comment by ObsComp** [comment]
GUI project was cancelled for now. We were trying a few directions with it but the focus has been on getting more tools, cleaner code and faster operations as more stuff went in over time.

The GUI project also requires potentially injecting code into the assets and I do not want to go that route right now in an alpha state game.

I have an idea for the report system and will likely get it in to version 7.1 or 7.2.

**Comment by ObsComp** [comment]
9.0 is released with a report tool. Players can type /report and their message. Online admins are given the message and the report is logged to a report file for later review. a future version will have those email out to a custom email address
