### ISSUE TITLE
Vehicle_Transport maximum distance configurable

### ISSUE THREAD

**Issue by dncastilho** [dmustanger/7dtd-ServerTools#181]
Hi, 

I love the feature of being able to transport my bike to my position. However, I think it would be great if the maximum distance allowed for this functionality to be configurable in ServerTools.xml. Would you guys mind implementing this feature?

Thanks in advance!

**Comment by ObsComp** [comment]
Yeah that should be no problem. I will write it down for a future release

**Comment by dmustanger** [comment]
This has been added in the latest version

**Comment by dncastilho** [comment]
thank you!
