### ISSUE TITLE
VOTING REWARDS

### ISSUE THREAD

**Issue by Retsof123** [dmustanger/7dtd-ServerTools#184]
**Describe the bug**
Voting rewards are not being awarded.

**How To Reproduce**
Details below. Tried over the last week since update to ver 18.1.6

**Expected behavior**
After a player has voted on 7daystodie-servers.com they enter /reward into the chat box and get a reward as listed in the xml. This does not happen and hasn't since I updated my server to use ver 8.6. The reply to /reward is  '{playername} checking for your vote', and that is it. I have checked my server at 7daystodie-servers.com and the votes have registered. I have also checked the config xml and confirmed the api and server number, all correct.
[CommandLog_12-7-2019.txt](https://github.com/dmustanger/7dtd-ServerTools/files/3935086/CommandLog_12-7-2019.txt)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 64 bit, unknown about the other players.
            Server is a windows based server supplied by streamline-servers
 - ServerTools Version 18.1.6

**Additional context**
The only log that shows anything is the commandlog.txt and is included. If there are any other logs please let me know. outputlog.txt does not show any server tools commands.
UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!

**Comment by ObsComp** [comment]
Sorry I did not respond sooner. I have not heard of any other issues. You may have a mistake in the reward.xml that is stopping items from spawning. There is another output log. It is normally found in the  7DaysToDieServer_Data folder by default.

**Comment by ObsComp** [comment]
If there is an issue with the config or an xml file, that output log will report it. This is the main output for servers and the default location for errors and exception reports. It runs a new one each time you start your server.

**Comment by Retsof123** [comment]
output_log.txt only shows one line that is related:

2019-12-26 16:20:23 | 47989.112 | Log | Chat handled by mod 'Server Tools': Chat (from '76561197995221683', entity id '171',

 to 'Global'): 'retsof123': /reward
-- | -- | -- | --


In game in the chat screen:
ServerTools: retsof123 checking for your vote.

No reply after 15 minutes. I have attached the votereward.xml and servertoolsconfig.xml and output_log.txt
[STConfig.zip](https://github.com/dmustanger/7dtd-ServerTools/files/4001907/STConfig.zip)
[output_log.txt](https://github.com/dmustanger/7dtd-ServerTools/files/4001908/output_log.txt)

I am still using ver 18.1.8 because I do't want to re-edit the servertoolsconfig.xml every couple of days and it is working very well except for this issue.

**Comment by ObsComp** [comment]
18.2.4 has added an automatic xml backup but does delete the originals. You can just copy and paste them over and use them for a reference in case some major change happen to the way the file is written. This should help tremendously for updates and that annoying step of setting the xml again and again.

I tried the reward out and had no issues. Considering this worked prior, that is very strange. It has not been modified in a long time.

I may add a que system to it in order to help prevent potential request overlaps to the website but it has not been needed or a problem for other servers. You are one of the first I have heard having issues. Double check the API key you used is correct and that the voting site still has your server registered and active.

**Comment by Retsof123** [comment]
All good, I found a space after the API that I hadn't noticed, it works fine now. Thanks for all your help and I appreciate the efforts to minimize editing of the config file after each update.

**Comment by Retsof123** [comment]
All good, I found a space after the API that I hadn't noticed. Thanks for all your help and I appreciate the efforts to minimize editing of the config file after each update.

 

Peter Lennon

Retsof123
