### ISSUE TITLE
world radius set

### ISSUE THREAD

**Issue by sLimLong** [dmustanger/7dtd-ServerTools#185]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to add a function to the console that will change the value of World_Radius

**Additional context**
Let's say we write "worldradius set NP 4000" in the console
and he changes the radius of the world right in the game.

**Comment by ObsComp** [comment]
Are you speaking about the radius tool that keeps them within bounds or the actual world?

**Comment by sLimLong** [comment]
I'm talking about the server tools function that keeps players within the given boundaries

**Comment by ObsComp** [comment]
Oh yeah no problem. I can add that on the next release. I intend to add all of the options from every tool to the console commands. There are unfortunately 90+ tools and options for every single one lol. I have been avoiding it like the plague. I have it written down for next update

**Comment by ObsComp** [comment]
Added to 18.2.3. Have fun!
