### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by di7gan** [dmustanger/7dtd-ServerTools#188]
Hello,
1、where can I get the GPS plug-in? 
2、A18.3 Copy the compressed ”bin\mods\“ to ”7 Days to Die Dedicated Server\mods\" and the following prompt appears, and there are no files in" 7 Days to Die Dedicated Server\ServerTools"

2020-01-09T11:28:29 115.000 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"DllNotFoundException: SQLite.Interop.dll
3、Is "Real_World_Time" the hour? The timekeeping in my server seems to be the game startup time + 60 minutes
Thank you!

**Comment by di7gan** [comment]
[新建文本文档.txt](https://github.com/dmustanger/7dtd-ServerTools/files/4038472/default.txt)

**Comment by ObsComp** [comment]
It looks like the installation did not go smoothly. Make sure to download from the releases and not the master files open to build your own version of ST. 
Inside the provided zip file you will find a mods folder that you place inside the dedicated server root folder which is where it should be installed to. You will find the 7daystodieserver.exe in this folder.
If you already have a mods folder, dont worry. Just place it in there anyways and it will merge the files inside. If it asks to overwrite and servertools files when prompted, do so. 

Now start the server again and see what the output log reports.

**Comment by ObsComp** [comment]
I suspect you may have been using Linux which caused the sqlite issue. This has been removed in more recent versions of ST. Please give it another shot if you have not.

Closing this topic
