### ISSUE TITLE
Party is unable to use sethome

### ISSUE THREAD

**Issue by NiccoJS** [dmustanger/7dtd-ServerTools#189]
Greetings.

Some users from our Server are unable to use /sethome in a Party members House protected by an land claim block.
is there any workaround or is this a bug?

EDIT: this is the error code: you are not inside your own or an ally's claimed space. You can not save this as your home.

**Comment by di7gan** [comment]
请先使用领地石后在使用/sethome

**Comment by NiccoJS** [comment]
we did.
i test this for myself
all are unable to use sethome inside friends claim zone

**Comment by ObsComp** [comment]
Okay I suspect the way I have it looking for your claim or an ally. I suspect a friend space is different so I will have to add a friend check as well. Thank you for the report

**Comment by Dimmer27** [comment]
to put a bedroll in someones claim area you have to be allied, same goes for the /sethome command

**Comment by NiccoJS** [comment]
already tested.
result was the same

**Comment by ObsComp** [comment]
There was a bug for a bit with this but it should be fixed. Please report again if still an issue.
