### ISSUE TITLE
More features and ideas 

### ISSUE THREAD

**Issue by Thodde26** [dmustanger/7dtd-ServerTools#19]
hi i would love to say thank you for doing so good work

here my ideas for more features
+ Server Autorestarter
+ more HomePoints
+ Teleport to a friend
+ addTeleport Points
+ EconomicSystem

Since I can not code myself I would look over some extensions.
sorry for my English

Best Regrades
Thodde26

**Comment by Thodde26** [comment]
sorry for the late response i was the last two weeks Ill. I hate it ^^

1. Homepoints
The Homepoints will be used the Permission files Serveradmin.xml and webpermissions.xml 
Serveradmin.xml 
for example: 
100 = Stammspieler 
200 = Builder 
300 = Donator ( ViP ) 
400 = Moderatoren 
500 = Junior Admin 
600 = …... 
999 = Webadmin 
1000 = FullAdmin 
 
The Perrmission in Serveradmin.xml and webpermissions.xml must configure. 

for example: 
Stammspieler = 2 Homepoints 
Builder= 4 Homepoints 
Donator = 6 Homepoints 
Junior Admin = 8 Homepoints 
Webadmin= 10 Homepoints 
FullAdmin= 12 Homepoints 
 
I'll create 2 sample files 
The function should be so that you /home name or / homexx 
(/home name) where name stands for the home point the player has set before 
 
Commands: 
/sethome name 
/home name 
/delhome name

**Comment by Thodde26** [comment]
sorry for my english i hope you understand what i mean

**Comment by ObsComp** [comment]
A server auto restart is not possible without a exe operating outside of ServerTools itself to monitor if it has closed down. This is a plan for a future version that will provide a visual GUI for server management.

The best option is to have the server set as a windows service. If it is closed down, it will automatically startup when set as a service.

One more home point can be set after enabling via config in version 6.0. You can also set it to donator only.

Teleport to a friend is planned for a future version, thank you for the idea.

Teleport points? There is a travel system available. What do you mean by teleport points? Market teleport and return?

Coin and Market system is will be in version 6.1.

**Comment by ObsComp** [comment]
Coin and Market will be in 7.0
Teleport to a friend will be in 7.0 as well
:)

**Comment by Thodde26** [comment]
I wait for the Version
 Thx for the new Features

**Comment by ObsComp** [comment]
7.0 is out now. It adds teleport to friend, shop system.

A second set of home points are already been added.

ServerTools will never be able to auto restart with how it operates. It is only running while the server is open. As mentioned before, setting it as a windows service is the best option and typically how most dedicated servers are handling it.

The travel system covers the teleport points and you can also make your own with custom commands.

Looks like its finally all covered. Enjoy :)
