### ISSUE TITLE
Protected area can't be removed

### ISSUE THREAD

**Issue by Dimmer27** [dmustanger/7dtd-ServerTools#190]
**Describe the bug**
When creating a protected area with the ps add command it creates the area in the ps list, but when doing the ps remove "1" it says it removes it but the area is still in the ps list until server restart but the area is still protected even if not in the list no longer

**How To Reproduce**
create a protected area with the "ps add" command test if area is now indestructible then try to remove the area with "ps remove "1" and se if the area is now back to normal.

**Expected behavior**
I expected the area to be protected = indestructible when using the add command, but also expected it to turn back to normal when I removed the protection from the area

**Screenshots**
nope no screenshots would help explain this
[output_log__2020-01-16__11-26-56.txt](https://github.com/dmustanger/7dtd-ServerTools/files/4070994/output_log__2020-01-16__11-26-56.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 - server being hosted at Nitrado - and another at Gportal
 - ServerTools Version 18.2.4

**Additional context**

UPLOAD A COMPLETE LOG FILE WITH YOUR BUG REPORT! IF THERE IS NO LOGFILE WE WILL CLOSE THE REPORT!

**Comment by ObsComp** [comment]
Thank you for the report. It is a little awkward right now and yes it can get stuck if not remove in the right manner. Quite annoying really. It is the very first release of the tool though. Dont go wild with it haha. I am going to try and make it easier for people and refine it. People are getting confused with the zones protected as well. In your case it is the protected spaces tool though. I noticed this issue early on too. It is just the order of removal and a bug in the console command. Just be cautious applying it for now if you do. Make sure you intend to lock down the area. I am getting a internally hosted server within the server running a website so you can monitor stuff live from a browser and update your xml files easier. Once that is done I should have the rest of the patch work on the go and get a release out for you.

**Comment by ObsComp** [comment]
Protected space and zones have been updated in 19.0.11
Please update to the latest version. Sorry it took so long
