### ISSUE TITLE
Protected Zones start flickering

### ISSUE THREAD

**Issue by NiccoJS** [dmustanger/7dtd-ServerTools#191]
Describe the bug
After adding an protected zone, items like doors, barrels, wheels, hatches & spikes start flickering.
The F1 Console als spamming alot of red text.

How To Reproduce
- setup an trader for start zone.
- start protecting the entire prefab
- set (protected="true")

Screenshots
1. https://www.directupload.net/file/d/5717/eytj6mz7_jpg.htm
2. https://www.directupload.net/file/d/5717/ij5ewpv8_jpg.htm
3. https://www.directupload.net/file/d/5717/fpb39gvo_png.htm

Desktop (please complete the following information):

    OS: Windows Server 2019 Datacenter - Server is hosted on our company Dataserver
    7 Days to Die Version: 18.3 B4
    Server Tools Version: 18.2.4
    Darkness Falls Version: V2.5 EXPERIMENTAL B2 + Hotfix

Server Log will not created caused by Server Manager RAT2
i need to figure out whats is causing this

**Comment by ObsComp** [comment]
There might be a conflict from another mod but I need to work on some major refinements to that tool. It is the very first release of it so consider it early beta :)   working on a big project right now and then I will be back to bug fixing and get this worked out. i would recommend being very cautious with that tool or just leave it off for now until I get some time to go over it.

**Comment by NiccoJS** [comment]
Greetings.
Thans for your response. another Problem is that if the Zone is protected and i set the value from true back to false the entire area stays indestructible.

i disabled the feature till there is an update.

P.s if there is an conflict keep in mind Darkness Dalls will be updated to a new Version today or tomorrow.
See official Discord

**Comment by ObsComp** [comment]
I have updated the protection system now in 19.0.11. Sorry it took so long. If you have a Zone or Protected Space that gets stuck as protected while not on your list or set to false, you can turn the tool off/on again and it will clear it up.
