### ISSUE TITLE
max. lenght clan name.

### ISSUE THREAD

**Issue by febreze21** [dmustanger/7dtd-ServerTools#193]
hello it's not an issue but there is a way to increase the limit of the lenght of the name (addclan) limited to 6 now. thanks you for your answer ! very good mod thanks you for your works !

**Comment by ObsComp** [comment]
Hi febreze. I could add an adjustment option so you can set the upper limit. Glad you are enjoying it and thank you for the advice

**Comment by febreze21** [comment]
Thanks you ! I wait this feature for the players who asked this ;).

**Comment by febreze21** [comment]
Oh and i have an other suggestion for further. If you could add a "rpname" like if a player type this command he can set his roleplay name in the server (different to the steam name) ;) and yu bad word filter list will work work with this too ;D

**Comment by ObsComp** [comment]
Clan name length can now be set. I have the role play name still written down.
