### ISSUE TITLE
Zone Command to Show Zone

### ISSUE THREAD

**Issue by suL33T** [dmustanger/7dtd-ServerTools#195]
Last release or so, I asked for a "zone" command to show which zone the current player is at. I don't seem to be able to use it or do not know the command for it.

**Comment by ObsComp** [comment]
I have marked this down for upcoming patches. It will be added

**Comment by ObsComp** [comment]
if you enable the Location tool and type /loc in chat, it will tell you which zone you are in if you are standing in one at the time

**Comment by ObsComp** [comment]
This is only available since version 19.5.3 which is the latest release
