### ISSUE TITLE
sethome,Website

### ISSUE THREAD

**Issue by sLimLong** [dmustanger/7dtd-ServerTools#196]
The / sethome command does not work

p.s it does not give out information, then that "sethome" should be put on claimblock
```
2020-03-02T11:14:51 2959.045 ERR [MODS] Error while executing ChatMessage on mod "Server Tools"
NullReferenceException: Object reference not set to an instance of an object
```
website everything is ok with the site, an error occurred: D

**Comment by ObsComp** [comment]
This should have been fixed in the last two versions of ST. If you are still seeing this issue, please report it again.
