### ISSUE TITLE
/shop not working

### ISSUE THREAD

**Issue by icklejitta** [dmustanger/7dtd-ServerTools#197]
Hello, can get an answer to this as its driving me crazy.

I have edited the shop.xml file to include my shop items, as far as I can tell all the data is correct, I got the item ID's from commands.gg for 7 Days To Die.

The file is on my hosted dedi server inside the servertools folder (all other features work just not shop) I type !shop or /shop in game chat and I get a green message saying something like ADMIN: The shop is currently empty, contact server administrator.  I am the server admin and I cant figure out whats wrong??  Help please players are waiting for this, I even spent hours listing and adding pics to our Discord for it lol.
![1](https://user-images.githubusercontent.com/61877226/76091713-01605b00-5fb6-11ea-98e9-9a5be8037a2c.jpg)
![2](https://user-images.githubusercontent.com/61877226/76091718-01f8f180-5fb6-11ea-9f79-218f3d82d2e5.jpg)
![3](https://user-images.githubusercontent.com/61877226/76091720-032a1e80-5fb6-11ea-8bce-2a2e02a1ddb0.jpg)

NOTE: Some of the xml is truncated because its so long, pics show start and end.

**Comment by chaplinchap** [comment]
I can get the command /shop to work either.
The command /buy 1 1 (for example) works.
But if ppl cant see what they buy whats the point?

**Comment by ObsComp** [comment]
It sounds like some bugs that were in the shop at the time. It should be fixed now in the last two versions of ST. If you are still having issues, please report it again and I will take a look.
