### ISSUE TITLE
Custom Commands Delay Not Working

### ISSUE THREAD

**Issue by Fuviox** [dmustanger/7dtd-ServerTools#20]
Using custom commands doesn't seem to trigger the delay timer.

**Comment by ijurisic** [comment]
Any chance for fix this?

**Comment by ObsComp** [comment]
I will be looking into this very soon. Hopefully we can program a dynamic data save system. I have something in mind. As of now, custom commands do not allow delays. The way it is setup fools a lot of admins since the existing default entries show a delay.

**Comment by ObsComp** [comment]
Except a solution in 6.1

**Comment by ObsComp** [comment]
Got it fixed in 6.4. Please update to that for custom command delays. It works on the first ten entries in the list. You can add more commands but they will not have delays.
