### ISSUE TITLE
Player_Stat_Check check player skills is no working？

### ISSUE THREAD

**Issue by adun1982** [dmustanger/7dtd-ServerTools#200]
i test it，normal player level 1（a18.4 windows server），skills 100(use cheat tools)，mod is no check，no log，no ban。Did I miss ？

**Comment by ObsComp** [comment]
It is not checking skill vs level but rather the player stats. It is too hard to organize appropriate skill levels per lvl with mods, custom servers and the pimps altering the base values occasionally. This tool just monitors stats instead.

_player.speedForward;
_player.Stats.Health.Value;
_player.Stats.Stamina.Value;
_player.jumpStrength;
_player.height;
