### ISSUE TITLE
Idea and question tp check and commands 18.4 b4

### ISSUE THREAD

**Issue by geinporem1976** [dmustanger/7dtd-ServerTools#201]
so the idea i ask for is can we also get a tp protection if in claimed area. would be great<enemyclaim> 

My question is i have sethome and friends teleport working on 18.4 windows version,but i can only get it to work with !home !commands instead off /home /commands.

i tried diff settings <private chat global chat settings where this is set> but when changed it still uses <!> for the commands and </> does unknown command.

**Comment by ObsComp** [comment]
Do you have any other managers operating? You can change the default command prefix to whatever you want. Change the setting  Chat_Command_Private to whatever symbol or prefix you want for commands. Some times other managers utilize this and do not pass commands through after processing that they have not applied. There is sometimes an option to allow pass through of commands with these
