### ISSUE TITLE
Customize Bloodmoon Warrior phrases

### ISSUE THREAD

**Issue by BioSs54** [dmustanger/7dtd-ServerTools#202]
Hi,
I want to change this sentence : https://github.com/dmustanger/7dtd-ServerTools/blob/3c0d37baba063412246cc7d523507f39a9fdb277/ServerTools/src/Tools/Bloodmoon_Warrior/Bloodmoon_Warrior.cs#L246

I dont found in  ServerToolsPhrases.xml
guess isnt customizable ?

BioSs.

**Comment by ObsComp** [comment]
It has not been added yet. I will be working on adding all of the missing phrases very soon. I am changing the back end of how it functions to make it easier to update and for you to customize with a few tags such as <PlayerName> <Date> <Time> <Level>. ST will automatically fill those in for you if available
