### ISSUE TITLE
Days_Before_Save_Delete

### ISSUE THREAD

**Issue by Khurune** [dmustanger/7dtd-ServerTools#203]
Days_Before_Save_Delete Not working on servers hosted via TCAdmin.

This leads of 100s of GB's being used up and having to be manually deleted.

**Comment by ObsComp** [comment]
For which tool is that. Be cautious of updates to config files. You may have old elements that have had their names changed. The latest version of ST should update that for you but check your output log in case of an error report. There is currently no option labeled that anymore.

**Comment by Khurune** [comment]
This was a little while ago, I'll keep an eye on it for future builds, we've currently scripted any servers that install it to remove that option for now. Once A19 is stable and ST is good to go, I'll do some testing then.
