### ISSUE TITLE
Server restart on horde night

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#206]
Hello!
First, Thank you for providing these great tool. 
The horde night detection is good, but it does not go out with time. The restart always happens shortly before the end of the horde night.

**Comment by geinporem1976** [comment]
correct i see the same here at aprox 1 am on hord night it say <auto shutdown detected the bloodmoon has ended>

**Comment by ObsComp** [comment]
It should be improved in the latest edition 19.0.1 and 18.4.12 which is being released right now.

Thank you
