### ISSUE TITLE
Cans of Chili not rewarded by gimme.

### ISSUE THREAD

**Issue by caligineux** [dmustanger/7dtd-ServerTools#208]
I believe the problem is due to a typo on line 188 of Gimme.cs. The item name "foodcanChili" should reference "foodCanChili". Also, the description "Can of Chilli" should be changed to "Can of Chili".

**Comment by ObsComp** [comment]
Alright I took a note of it and will check the code

**Comment by ObsComp** [comment]
I fixed this in the latest release. Thank you
