### ISSUE TITLE
Name coloring

### ISSUE THREAD

**Issue by ObsComp** [dmustanger/7dtd-ServerTools#21]
Name color change and prefix:

You can only set one admin tier and one moderator tier to a color.
Example, I can set tier 0 for admins and tier 6 for moderators but this means a tier 5 will not get a color change.

Can this be programmed a little differently? I will explain...

I have 3 admin tiers on my server 0, 1, 2. Each have their own respective powers enabled as we teach and train them to work with the tools we offer before setting them to a higher tier.
Our moderators range is 3, 4, 5, 6. Each of those have their own commands and responsibilities too.

I would like to be able to set 3-6 as green to represent moderators and 0-2 for admins. The config could be remapped multiple ways allowing a range input, I will leave that for you to decide how it would work.

My hope is this...
Tool Name="AdminNameColoring" Enable="True" AdminLevelNeeded="2" AdminPrefix="(Adm)" AdminColor="[FF0000]" ModeratorLevelNeeded="6" ModeratorPrefix="(Mod)" ModeratorColor="[008000]"

OR

<Tool Name="AdminNameColoring" Enable="True" AdminLevelNeeded="0,2" AdminPrefix="(Adm)" AdminColor="[FF0000]" ModeratorLevelNeeded="3,6" ModeratorPrefix="(Mod)" ModeratorColor="[008000]"

If I used one of those in the config, I was hoping it will set all moderators from level 3 to 6 as green and admins level 0 to 2 as red.

OR

Tool Name="AdminNameColoring" Enable="True" AdminLevelNeeded="5" AdminPrefix="(Adm)" AdminColor="[FF0000]" ModeratorLevelNeeded="10" ModeratorPrefix="(Mod)" ModeratorColor="[008000]"

If I set this it would set all mods from lvl 6 to10 as green and admins from lvl 0 to 5 as red.

With this in mind, could you add a donator color? You have reserved slots already so that is a great feature to match. Server admins could set a donating player to a admin tier with extra commands such as /home or /teleport commands but also change the name color. When their reserved status is removed or runs out, they will know when they no longer appear in a color.

Tool Name="DonatorColoring" Enable="True" DonatorLevelNeeded="9998" Prefix="(Don)" Color="[0066ff]"

This tool you would not want the same kind of range input with the config or they all need to be defined instead. What I mean is you wouldn't want donators defined as 9998 up to 7 where moderator levels start... I think the best solution is allowing range inputs in your config for all the color change stuff. Ex 0-2 or 3-6.

You don't have to of course, either way thank you so much for all your work on this project so far. You have really made a difference in the 7Days community.

**Comment by ObsComp** [comment]
I see it cut out my examples... doh!

**Comment by ObsComp** [comment]
I changed it myself so I can have a range of admin tiers and mod tiers.

Also changed invalid items to work with players and mods, but skip admin level.

Added donator colors.

Going to start working on some anti cheat checks soon. I will let you know how it goes.

**Comment by dmustanger** [comment]
added :D
https://github.com/dmustanger/7dtd-ServerTools/commit/4adfc05743f364e5b5915650f941a9c0698808cf
