### ISSUE TITLE
[19.0.0] Server logs being flooded with: Test Damage Detection

### ISSUE THREAD

**Issue by jeppelykke** [dmustanger/7dtd-ServerTools#211]
Hey Hey,

Server logs being flooded with all damage done in the world example from logs:

`INF Test Damage Detection. New Block houseFrontDoor2_v3. Old Block houseFrontDoor2_v3
 INF Test Damage Detection. New Block houseFrontDoor2_v3. Old Block houseFrontDoor2_v3

INF Test Damage Detection. New Block treeOakLrg01. Old Block treeOakLrg01
INF Test Damage Detection. New Block treeOakLrg01. Old Block treeOakLrg01
INF Test Damage Detection. New Block treeOakLrg01. Old Block treeOakLrg01

INF Test Damage Detection. New Block decoSwingSet. Old Block decoSwingSet
Test Damage Detection. New Block woodRailing. Old Block woodRailing
`

**Comment by geinporem1976** [comment]
yeah indeed and it cant be turned off and miss out on few items it does not recon...
setting for dammage is false

**Comment by ObsComp** [comment]
It has been fixed in 19.0.1

Thank you for the report
