### ISSUE TITLE
Does not work Invalid_Item_Kicker

### ISSUE THREAD

**Issue by sLimLong** [dmustanger/7dtd-ServerTools#213]
`<Tool Name="Invalid_Item_Kicker" Enable="True" Ban="False" Admin_Level="0" Check_Storage="true" />`
![image](https://user-images.githubusercontent.com/36954136/86521549-07c6ec80-be5b-11ea-9da2-2e24e1ff119f.png)

**Comment by ObsComp** [comment]
Okay, I have it marked down for the next round of fixes. Thank you

**Comment by sLimLong** [comment]
ban 171 "Invalid Item: drugRedPillAdmin" - slightly wrong command to kick the player
he does this if you do not include the player's ban
Please correct

**Comment by ObsComp** [comment]
Thanks slim. Got that updated for you on next patch. Should be out this weekend.
Also updating the capitalization for this file. <Item Name="" />

**Comment by ObsComp** [comment]
19.0.5 is out. Invalid item kick should be working now. Please report any issue you may have tho

**Comment by geinporem1976** [comment]
report off non working items in the list as i am sure i use the right names; gunHandgunPistolAdmin shown in game live map;concretePilar100 etc
[item rejections.txt](https://github.com/dmustanger/7dtd-ServerTools/files/5102844/item.rejections.txt)

**Comment by ObsComp** [comment]
Change item itemName= to this:
Item Name="terrOrePotassiumNitrate" /> as an example. The capitalisation was changed and cleaned up.. Delete the file and let it rebuild, then add your custom items back on to it.


________________________________

**Comment by geinporem1976** [comment]
thnx so much ;) never  saw that one damn xd yes works
