### ISSUE TITLE
New player message fails to stop showing

### ISSUE THREAD

**Issue by geinporem1976** [dmustanger/7dtd-ServerTools#214]
ServerTools': *The stench of young flesh bares itself upon the world*

the message will show up still even if its 2nd or 3rd time join

probably it happens after server restart

**Comment by ObsComp** [comment]
Yes it was after server restart. Two things happened. The internal data storage was not functioning properly and the pimps changed something in the api so it has been fixed in 19.0.1.

Thanks for the heads up
