### ISSUE TITLE
HighPingKicker doesnt work. checks if not admin instead of is admin 

### ISSUE THREAD

**Issue by Z1NC** [dmustanger/7dtd-ServerTools#215]
in HighPingKicker.exec
if (Dict.ContainsKey(_cInfo.playerId) || !GameManager.Instance.adminTools.IsAdmin(_cInfo))
should be
if (Dict.ContainsKey(_cInfo.playerId) || GameManager.Instance.adminTools.IsAdmin(_cInfo))

**Comment by ObsComp** [comment]
You are right! Thanks
