### ISSUE TITLE
Wallet not saving between restarts or updates

### ISSUE THREAD

**Issue by Letoric** [dmustanger/7dtd-ServerTools#216]
I'm using Logic Servers, so it is possible that this is an issue on their side, however, it's hard for me to say for sure, so I'm reporting and hoping for the best. Host platform is Windows based, Prior version was 19.0.0, wallet was not saving, current version is 19.0.1, a quick test by booting the server, using telnet to add coin to the wallet, then shutting down, then restarting and using wallet <steamid> which reports 0

**Comment by Letoric** [comment]
*Update, I verified that it does save the wallet on my home windows 10 box. Do you have thoughts on what might be wrong that would prevent it from working on a hosting platform?

**Comment by ObsComp** [comment]
This was a bug in 19.0.0 however it should be fixed in 19.0.1. I added wallet coins in the same manner and restarted without issue. I will double check right now though

**Comment by ObsComp** [comment]
My only thought is your host did not update properly. Try and reinstall ST fresh and see if it fixes it

**Comment by ObsComp** [comment]
If your host has a one click installation process, I have seen them fail at times. You may have ran it with the server still open so it did not copy the files over properly.

**Comment by ObsComp** [comment]
I can not replicate the issue on my end by the way. This leads me to believe it is the installation process not updating the files. Double check the output log reports 19.0.1 on start up

**Comment by Khurune** [comment]
We fixed the issue on the host side, seemed to work fine after restarting the server.
-LogicServers.

**Comment by ObsComp** [comment]
Excellent, great news. Thank you for the report.

Closing this topic.
