### ISSUE TITLE
BloodmoonWarrior skipping players for reward

### ISSUE THREAD

**Issue by Z1NC** [dmustanger/7dtd-ServerTools#217]
(I run my BloodmoonWarrior  without the `(random.Next(0, 11) < 6) `so everyone is eligible)
BloodmoonWarrior skipping players for reward. I was not sure why so i output debug info to console 
and `_warriors.Count` is being decremented while` _warriors[i]` it being iterated over causing it to reward one then skip a player

not sure if its just me because this is my first experience using c# 
`WarriorList.Remove(_warrior);` seems to be decrementing `_warriors.Count`
like `List<int> _warriors` is pointing to` List<int> WarriorList` data

I removed
```
WarriorList.Remove(_warrior);
KilledZombies.Remove(_warrior);
```
and
```
if (WarriorList.Contains(_warrior))
{
    WarriorList.Remove(_warrior);
    KilledZombies.Remove(_warrior);
}
```

then I just clear both outside the for loop and it works now

**Comment by ObsComp** [comment]
That was done purposely so that it did not offer it to everyone each time. It was a random 50/50 draw that they may get it so that it was a bit more special but by all means if you like it that way thats cool. I am glad you were able to change it for your server

**Comment by ObsComp** [comment]
The randomization is only upon inviting them to the bloodmoon event. The reward is based on them having enough zombie kills and not dying during the bloodmoon.

**Comment by Z1NC** [comment]
sorry what i meant was players that were in the event and got 3 time the required zombie kills without dying or leaving were not being rewarded 
I set it to output ` _warriors` list to console to figure out why and it was being removed from while it was being iterated over due to `WarriorList.Remove(_warrior);`
causing the `_warriors` list to shift and skip players for the reward
if there is more than 2 players  in the event the second player in the list is always skipped for reward even if they meet the requirements

**Comment by ObsComp** [comment]
Okay I have tweaked it a bit for next patch
