### ISSUE TITLE
Starting Items

### ISSUE THREAD

**Issue by xSunnyxx** [dmustanger/7dtd-ServerTools#218]
I have a problem with the starting items. 
If the players join again after a server restart, the starting items are given again. 
How can I avoid that?
Thanks in advance
Greetings Sunny

**Comment by geinporem1976** [comment]
There is a updayed version where its fixed or its work in progress

**Comment by ObsComp** [comment]
Yes the update fixed this. It was a bug in 19.0.0 
Please update to 19.0.3 which is the latest release and is very stable. They will unfortunately receive them one more time each. All data in general was not saving. Any version past 19.0.1 has this fixed but the best version is 19.0.3

**Comment by geinporem1976** [comment]
cool so 19.0.4 isnt
 stable yet @ObsComp
