### ISSUE TITLE
set home working for some players others it doesnt

### ISSUE THREAD

**Issue by geinporem1976** [dmustanger/7dtd-ServerTools#219]
For some reason i as a owner can set home with out problems and my fellow player can't even when i give him full admin rights the console say
2020-07-09T01:24:43 2670.651 ERR [MODS] Error while executing ChatMessage on mod "Server Tools"
NullReferenceException: Object reference not set to an instance of an object

same message on tp friend command /friend 171(my id in game) fails

also when in friends house i can set home and my first home gets
deleted

**Comment by geinporem1976** [comment]
for some reason i as a owner can set home with out problems and my fellow player can even with admin rights the console say
2020-07-09T01:24:43 2670.651 ERR [MODS] Error while executing ChatMessage on mod "Server Tools"
NullReferenceException: Object reference not set to an instance of an object

**Comment by ObsComp** [comment]
I am investigating the first two issues today. 

Home is a single place so yes it over writes the original save. There is an option to turn on home 2 in the options. This will allow a second home location.

I am planning to add the option to set how many home location a player can set. It will work very similar to waypoints

**Comment by geinporem1976** [comment]
More then home would be nice if it can be.
163 exp still gives me this problem.

**Comment by ObsComp** [comment]
I have it written down to expand the home system and allow more locations. It will work like the waypoint system when it is done

**Comment by geinporem1976** [comment]
little update on the error: some players sethome works! a known but,

the players for who it doesnt work, outside there claim the command say your not in a claimed area(so for them the command works outside the claimblock area)

**Comment by ObsComp** [comment]
It should only allow a home be set inside their own claim or friends claim. That is what it is coded for. I cant seem to replicate this. Could I have an output log of it happening? Maybe I can figure out whats causing it

**Comment by geinporem1976** [comment]
I am absolute willing to try and send it what or where is the out put log

**Comment by ObsComp** [comment]
Output log is normally in your default 7 days server folder either in the main one or inside the 7DaysToDieServer_Data folder. Sometimes it is labeled differently depending on your host. It will have all the information from server start up and players joining/leaving/chat

________________________________

**Comment by geinporem1976** [comment]
[output.log](https://github.com/dmustanger/7dtd-ServerTools/files/5250424/output.log)

**Comment by ObsComp** [comment]
Version 19.0.5 is what you are running going by your log. Please update to the latest 19.0.11 and report if you are still having this issue. There was an problem with the claim check if I recall but it was fixed in a later version. Let me know though

**Comment by ObsComp** [comment]
https://github.com/dmustanger/7dtd-ServerTools/releases/download/19.0.11/7dtd-ServerTools-19.0.11.zip

**Comment by geinporem1976** [comment]
Okay thnx and yes i was waiting with update until it was fixed ill run the latest and report iff needed

**Comment by geinporem1976** [comment]
okay here again new log 
on command it only shows yellow word servertools
so somthing id changed just not all for the working good xd
[output (1).log](https://github.com/dmustanger/7dtd-ServerTools/files/5252796/output.1.log)

**Comment by geinporem1976** [comment]
btw did new update break the joined fresh and stinks again
i just joined and second time i join i get again i join for the first time

**Comment by geinporem1976** [comment]
[output (2).log](https://github.com/dmustanger/7dtd-ServerTools/files/5252808/output.2.log)
some more checking

**Comment by geinporem1976** [comment]
[output (3).log](https://github.com/dmustanger/7dtd-ServerTools/files/5289247/output.3.log)
here on 19.1 fresh install same issue 1 player can other cant
hope you can find the issue. thnx

**Comment by ObsComp** [comment]
If this is still an issue in the latest release, please let us know. ST is at 19.4.1
