### ISSUE TITLE
[Suggestions for BloodmoonWarrior] add variable to disable reward of death remove 

### ISSUE THREAD

**Issue by jeppelykke** [dmustanger/7dtd-ServerTools#221]
Hey Hey,

From HowToSetup on Bloodmoon warrior: 
_Players death count will reduce by one if successful_
Could we get a variable to turn on/off if we want the Bloodmoon Warrior to remove a death from players stats. 

Exsample: 
`<Tool Name="Bloodmoon_Warrior" Enable="True" Zombie_Kills="10" Remove_death_stats="False"/>`

**Comment by ObsComp** [comment]
Yep that is no problem

**Comment by ObsComp** [comment]
This has been added in 19.0.5. Thanks for the suggestion.
