### ISSUE TITLE
having to reupload configs to the server after every restart

### ISSUE THREAD

**Issue by mcdj23** [dmustanger/7dtd-ServerTools#222]
been having this problem where every time I restart my server or turn it on it reset all the server tool configs to default and I have to reupload them even does it when start the server after uploading the configs well it's off. i put a zipped video of me showing the problem and my configs
been trying to figure out why it's doing this for 3 days now final gave up and decided to ask you guys the devs of the plugin/mod 
[7-days-server-tools-configs.zip](https://github.com/dmustanger/7dtd-ServerTools/files/4907774/7-days-server-tools-configs.zip)

[2020-07-11 16-41-13.zip](https://github.com/dmustanger/7dtd-ServerTools/files/4907767/2020-07-11.16-41-13.zip)

**Comment by mcdj23** [comment]
if you need me to show any thing else just ask

**Comment by giK-LoA** [comment]
I don't have this problem anymore since the latest patch to ST (A19). Are you on A18 still?

**Comment by ObsComp** [comment]
Quite bizarre. I have not seen that before. That is normally a permissions value from the server itself. I will release another version of  18 with the latest editions in hopes that is all fixed for you.
