### ISSUE TITLE
Block Home tp/friend tp on claim blocked erea suggestion

### ISSUE THREAD

**Issue by geinporem1976** [dmustanger/7dtd-ServerTools#223]
If possible i would like to see the option to prevent teleport on a enemies claim to make the game even with tp more competitive on the raids.

thnx in advandge for all the great work you guys do.

**Comment by ObsComp** [comment]
Would it be useful to have an option to check for near by non friend players as well?

**Comment by geinporem1976** [comment]
Yeah i thunk if that iption would be able to turn on and off be great

**Comment by ObsComp** [comment]
In general you can not set a waypoint inside a claim. You can only teleport inside of a claim through the use of the home command so you would need to be friends. Maybe this has to do with that bug you were having from the earlier version of ST?

Has someone setup a waypoint and then another person placed a claim in that spot?
