### ISSUE TITLE
Damage_Detector bans users who take off own claim blocks

### ISSUE THREAD

**Issue by zelenovas** [dmustanger/7dtd-ServerTools#225]
Damage_Detector identifies removing own claim block as causing a lot of damage and ban that user.

Example of ban message:
`<blacklisted steamID="XXXXXXXXXXXXX" name="XXXXXX" unbandate="2025-08-23 16:27:51" reason="Auto detection has banned you for using a damage manipulator. Damage recorded: 7000" />`

I think it is possible to add check: if claim block owned by user who remove/damage it.

P.S.: Thanks for your work!

**Comment by zelenovas** [comment]
Tested on Linux Server: Ubuntu 16.04.2 LTS

**Comment by ObsComp** [comment]
Yes I had what I thought was a working check on it. I have it written down as a priority for next round of patch work.

**Comment by ObsComp** [comment]
This is fixed in the latest patches. Thank you for the report
