### ISSUE TITLE
ccp conflict 

### ISSUE THREAD

**Issue by djshylow** [dmustanger/7dtd-ServerTools#228]
Hi ccp for chat color prefix 
it is conflicting with another plugins we use 
chat command permission

is there a way to change it ?

**Comment by ObsComp** [comment]
If you type help by itself it will show all the available commands. Typing help and the command will show you other variables to the command that can be used. For example typing help will show you st-ChatColorPrefix. Typing help st-ChatColorPrefix will show you can use st-ChatColorPrefix, ccp, or st-ccp

Sorry it took so long to respond. I was busy coding :)
