### ISSUE TITLE
login data question?

### ISSUE THREAD

**Issue by DemonRem** [dmustanger/7dtd-ServerTools#230]
as i server creator how i can get login data for access the panel?

**Comment by kamohy** [comment]
good question :D 
self question :D

**Comment by DemonRem** [comment]
i like the comment :D
but what to put there steam access ?

**Comment by kamohy** [comment]
good question, next ?
i don't know...

**Comment by kamohy** [comment]
okay u need this:
https://store.steampowered.com/app/294420/7_Days_to_Die_Dedicated_Server/

this tool u need 4 ServerTools i think :D 

-wiki read-

**Comment by batboyboy1990** [comment]
metoo i cant't not to login this. im have decated sever but by steam CMD ( sorry my eng bad) my qurestion ( where is a password and ID)

**Comment by batboyboy1990** [comment]
> okay u need this:
> https://store.steampowered.com/app/294420/7_Days_to_Die_Dedicated_Server/
> 
> this tool u need 4 ServerTools i think :D
> 
> -wiki read-

i have this but by steam CMD ! is not work??

**Comment by kamohy** [comment]
start this file: startdedicated.bat

thats ure server start-file

**Comment by ObsComp** [comment]
I am not sure what you mean by this. ServerTools is a stand alone mod running with in 7D2D dedicated server operations. It helps manage dedicated servers. After installing the mod files and starting your server, it will create a folder named ServerTools inside your main server directory. This folder has the config file you need to access in order to change settings in ServerTools. Depending which tools are enabled, various xml files will be created in this same folder that allow you to customize various lists that will help you control your server

**Comment by batboyboy1990** [comment]
> I am not sure what you mean by this. ServerTools is a stand alone mod running with in 7D2D dedicated server operations. It helps manage dedicated servers. After installing the mod files and starting your server, it will create a folder named ServerTools inside your main server directory. This folder has the config file you need to access in order to change settings in ServerTools. Depending which tools are enabled, various xml files will be created in this same folder that allow you to customize various lists that will help you control your server

no imean is a weppanel !

**Comment by ObsComp** [comment]
ServerTools has no control over your hosts webpanel. You will need to contact them.

If you are simply looking for which port your control panel opens on, it is listed in the output log on server start up

**Comment by 1d0navan** [comment]
so the question is still not answered. what, if i have the server running on a dedicated linux machine? and i want to login to the custom admin panel: http://123.123.123.123:8084/st.html/ what are these credentials the creator asked....

**Comment by ObsComp** [comment]
AHH! Now it makes more sense lol
I just didn't understand what they were asking.

The login credential are given through the game console. Either login to your server and use the console or access it through telnet/control panel. Type ws add {steamId}.  Example: ws add 76561191234567890

It will response with their password. They can then use this steam id and the password to login. After they login they can change their password on the website.

It is a website so when you call it a UI I get a little thrown off. You are right though it technically is a combination website/UI.

Does that help or were you asking something else?

**Comment by 1d0navan** [comment]
ahh, this is what i needed :) thanks for the quick info. btw im currently working on a bootstrap based interface 👍

**Comment by DemonRem** [comment]
i type the command ws add and my steam id and i get denying command ws add steamid from client lust
