### ISSUE TITLE
where is a ID pass on web login?? 

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#231]
where is a ID pass on web login?? do you have combine weblogin like a bot man ??

**Comment by ObsComp** [comment]
Use a console either in game or through telnet to add their steam id as a login to the site. You can use any console that has access to your server to do this as long as you have admin rights. When you add them it will return their temporary password. They can use this to login with the steam id you added and the password it gave you. After logging in they can change their password at any time.
