### ISSUE TITLE
teleport vehicle some error

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#232]
the bike is gone, i cant' not save the new bike becuse im delete that bike on botman , in severtool cant save new other bike, help my find data vehicle and delete old vehicle! im' try to dell vehicle on save game, reinstall games ( not delete world) reinstall mod , is  not working :(

**Comment by ObsComp** [comment]
That info would be held in the ServerTools.bin file
It should still allow you to save a new bike though. What does it say when you try to save a new one? Anything reported in the log?

**Comment by batboyboy1990** [comment]
> That info would be held in the ServerTools.bin file
> It should still allow you to save a new bike though. What does it say when you try to save a new one? Anything reported in the log?


I have translated into other languages, "Its mean I saved the motorbike wrongly, but my bike is bicycle" before that my bike was a bicycle, but deleted by "botman"

**Comment by batboyboy1990** [comment]
> That info would be held in the ServerTools.bin file
> It should still allow you to save a new bike though. What does it say when you try to save a new one? Anything reported in the log?

HOW TO EDIT FILE BIN?

**Comment by batboyboy1990** [comment]
> That info would be held in the ServerTools.bin file
> It should still allow you to save a new bike though. What does it say when you try to save a new one? Anything reported in the log?

last time it worked with MD500 mod, now it no longer works with mod media

**Comment by MkxTrax** [comment]
> > That info would be held in the ServerTools.bin file
> > It should still allow you to save a new bike though. What does it say when you try to save a new one? Anything reported in the log?
> 
> HOW TO EDIT FILE BIN?

hey man, have you tried disabling the command in botman? Also checked le in console, to ensure its truly gone? it may not be an ST issue here just a conflict, because both mods will have data in .bin files

**Comment by ObsComp** [comment]
I have updated the vehicle teleportation tool in the upcoming release 19.6.2
Custom vehicles should work without issue to save and teleport
Please give us a report about the new version if it still does not function
