### ISSUE TITLE
i search a command list to add admins ect.

### ISSUE THREAD

**Issue by kamohy** [dmustanger/7dtd-ServerTools#233]
Where have a full command-list ?

there is nothing in the wiki....

**Comment by batboyboy1990** [comment]
Full here on Triggers
or
http://7daysbroad.ddns.net/forum/threads/cac-ma-lenh-hien-hanh-7daystodie.75/post-154

**Comment by ObsComp** [comment]
While in game you type /commands to see chat commands and in console type help. Servertools commands are marked with st- so you know.
Chat commands only show based on which tools are enabled.

**Comment by ObsComp** [comment]
I will mark down to update the wiki. It is very out of date at this point
