### ISSUE TITLE
 The zone is down

### ISSUE THREAD

**Issue by tatra1995** [dmustanger/7dtd-ServerTools#235]
Hello on version 19.0.8, the zone was working. Come on, you had to get wet and on 19.0.9 after setting xyz nothing happens zero reaction, mainly I mean ZONES to PVP because you can do them nicely save zone but now it stopped working, maybe you have some tips how to fix?
I had such a code and it worked until yesterday.

[https://i.imgur.com/ZknoabR.png](url)

<?xml version="1.0" encoding="UTF-8"?>
<Zones>
    <Zone>
	    <Zone Corner1="-2744,40,2882" Corner2="40" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-1558,40,-3418" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-115,40,4277" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="4210,65,635" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-1303,55,-2023" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="667,40,1133" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-4454,50,4244" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="4298,45,3275" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-1802,45,-1890" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="670,40,-4418" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="3391,60,-1828" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="1437,40,986" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="3390,45,566" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="307,55,-2016" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-3300,50,288" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
		<Zone Corner1="-611,40,877" Corner2="30" Circle="True" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="false" Protected="true" />
        
        
        
    </Zone>
</Zones>

**Comment by batboyboy1990** [comment]
me too cant not remove zone

**Comment by ObsComp** [comment]
Hello. Add Name="" to those lines

Here is an example:
<Zone Corner1="-8000,0,8000" Corner2="8000,200,0" Name="North" Circle="false" EntryMessage="You are entering the Northern side" ExitMessage="You have exited the Northern Side" Response="" ReminderNotice="You are still in the North" PvE="false" NoZombie="false" Protected="false" />

**Comment by tatra1995** [comment]
and in fact it is not in the previous version and now it is thanks;)

**Comment by ObsComp** [comment]
I think it will work anyways but change that to this instead:

Zone Corner1="-8000,0,8000" Corner2="8000,200,0" Circle="false" Name="North" EntryMessage="You are entering the Northern side" ExitMessage="You have exited the Northern Side" Response="" ReminderNotice="You are still in the North" PvE="false" NoZombie="false" Protected="false"

I need to fix the default examples

**Comment by tatra1995** [comment]
I do not know why the message pops up in the game at the entrance, but at the exit, System.String []
and Pve doesn't work as you can kill on true

**Comment by tatra1995** [comment]
https://www.youtube.com/watch?v=Rj7HCQ7heYo&feature=youtu.be

**Comment by ObsComp** [comment]
Hmm I made some changes to Zones so I will run tests and get it fixed up for you
Sorry about that

**Comment by tatra1995** [comment]
Thank you for trying so hard;)
forgive me for english. I'm using a translator

**Comment by tatra1995** [comment]
hi when can you expect updates? zone etc.
and I also test a few other things and the kill notice does not show damage even if it is true and the fly detecor works too well banning players when it comes down to xD brackets
if I find something else, I will let you know;)

**Comment by ObsComp** [comment]
I am working on it right now and have been for a few days. Pecking away at it. I need to fix the console command to remove a protected zone so that the protection actually turns off but its looking good so far. Got a few things fixed and improved.

The damage is dependent on the injection process working. Do you have any other mods running injections that might be stopping the process? Your output log will tell you if it cant inject to a method due to another mod on load up. It also had a bug in one version so make sure you have the latest running.

What brackets?

**Comment by ObsComp** [comment]
I think it will be out tonight. I am going to honor the veterans for a few hours but when I get home I will finish up and release

**Comment by tatra1995** [comment]
I have a few mods, but the tools server worked with them normally, but I have the 2nd server clean and the same thing does not work on the main server on the 2nd test clean also does not work

**Comment by ObsComp** [comment]
New patch is out that should fix zones for you.

What brackets were you talking about that triggered Flight detection?

**Comment by tatra1995** [comment]
ok, update the mod and test;) I mean killnotice
For example, player 30 kill player 40 with ak47 guns dmg [??] does not show damage

**Comment by ObsComp** [comment]
Did you update your phrase file by deleting it and letting it rebuild? Delete it while the server is off to be sure it is a clean rebuild from the latest release.

________________________________

**Comment by tatra1995** [comment]
the inscription is already working but I have to wait for some player to enter the server and check pvp xD

**Comment by tatra1995** [comment]
thanks for the help ;)
Are you collecting any donations?

**Comment by ObsComp** [comment]
Glad to hear it is working.

Yes if you wish to donate you can do so at either of these links. Appreciated but certainly not necessary. It all goes towards more development of ST and helping me not go crazy haha

https://www.paypal.me/ObsessiveCoder
https://www.patreon.com/ObsessiveCoder

________________________________

**Comment by tatra1995** [comment]
no pvp works in my zone;

**Comment by ObsComp** [comment]
Did you set the zone to pve true?

________________________________

**Comment by tatra1995** [comment]
I'll send you the video soon

**Comment by tatra1995** [comment]
https://www.youtube.com/watch?v=xi3NCW9_wzU

**Comment by tatra1995** [comment]
the subtitles are working now, nozombi also removes them when they enter my wife, but pve I don't know sometimes it doesn't work; (

**Comment by ObsComp** [comment]
You have pve set to true. That will stop all PvP in that zone.

________________________________

**Comment by tatra1995** [comment]
does not stop ,
can shoot others,
from all caresses; (

**Comment by tatra1995** [comment]
on version 19.0.8 it worked, 19.0.9 I don't know and on 19.0.10 it no longer works

**Comment by ObsComp** [comment]
Oh I just released a patch tonight to 19.0.11 that addresses some issues with zones. Please give it a shot and be careful of the structure in the Zones.xml file. I added Name a few patches ago. You may need to add that by stopping the server and restart for it to take proper effect after adding it to the file.

Example:
<Zone Corner1="-8000,0,8000" Corner2="8000,200,0" Circle="false" Name="North" EntryMessage="You are entering the Northern side" ExitMessage="You have exited the Northern Side" Response="" ReminderNotice="You are still in the North" PvE="false" NoZombie="false" Protected="false" />

________________________________

**Comment by ObsComp** [comment]
Oh you know what... I just noticed you also use circles. I have to work on protection for circular space. PvE should work but I am working on the circle. Protection works for squares and rectangles only 🙂

If you need to make a protected space, use the Protected Spaces tool and make an area that is protected that way.

________________________________

**Comment by tatra1995** [comment]
from what I see, it works on fist melee weapons, tools but, with firearms it deals damage I don't know what it is
https://www.youtube.com/watch?v=VYcL2GzRC0Q
<Zone Corner1="-2724,30,2866" Corner2="-2763,80,2899" Name="North" Circle="false" EntryMessage="Save Zone" ExitMessage="Exit Save Zone" Response="" ReminderNotice="You are still in the North" PvE="true" NoZombie="true" Protected="true" />

**Comment by ObsComp** [comment]
Alright I will run some more tests

**Comment by tatra1995** [comment]
I got pissed off that it works on the test and it doesn't work on the main one and I did 10 restarts from the nerves and it started working !!! in the end, I don't know what happened but it works

**Comment by shizhiwen2020** [comment]
Your tools are perfect.But after I tested it, I have some personal advice to tell you: the bank and wallet functions are not separate, players need to deposit money in the bank before transferring to the wallet, which is really troublesome, why not directly deposit into the wallet? I don't understand the Big Lottery function, only two buttons?One is to initiate, one is to buy, why not more shortcuts.Hope to listen to my Suggestions and improve, I will sponsor you

**Comment by shizhiwen2020** [comment]
Another problem is that the prison is not fully functional. You can imprison players but you can't release them.

**Comment by ObsComp** [comment]
Prison should be fully functional now.

As for the wallet and bank advice. It does go straight to the wallet. A wallet does not hold physical casinoCoin though, it is digital. The only time you need to use the bank is if transferring it from casinoCoin in to digital or digital to casinoCoin.

**Comment by ObsComp** [comment]
Oh there is one other time you might use the bank and that is to store your wallet value without losing it. There is an option to lose everything in the wallet upon death so the bank is a way to keep it safe but it does feel like extra steps for no reason overall

**Comment by ObsComp** [comment]
Prison should be fixed. I forgot to mention it
