### ISSUE TITLE
Safe zone

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#241]
key Protected="false" in Zones does not work.
please add admin permission level for allow construction in this protected area for administrators.
unprotected spaces found inside the protected area.

**Comment by tatra1995** [comment]
Protected = "True" works for me, but if I change it to false, the protection remains; (

**Comment by ObsComp** [comment]
This will be addressed in 19.3.3. I am working on it now. Very sorry for the delay.
