### ISSUE TITLE
Bloodmoon warrior reward items have no mod slots

### ISSUE THREAD

**Issue by jayfusion08** [dmustanger/7dtd-ServerTools#243]
So I replaced the rewards in the bloodmoonwarrior xml with quality level 5-6 weapons, tools and guns and when you receive the reward the item has no mod slots. The only options it has is equip, drop, scrap and repair with 0 mod slots for a quality 5 or 6 item.

**Comment by ObsComp** [comment]
I believe this is fixed in the upcoming version 19.6.2 
Sorry it took so long
