### ISSUE TITLE
Jail Time 

### ISSUE THREAD

**Issue by tatra1995** [dmustanger/7dtd-ServerTools#244]
it is possible to edit the jail time from 60 minutes to e.g. 5
Also strange, it is PvE_Violations by default on jail on 4 and after shots nothing happens on 3 the same and on jail 1 it is enough to 1 shot and jail a little ring
     <Tool Name = "PvE_Violations" Jail = "2" Kill = "6" Kick = "8" Ban = "10" />

**Comment by ObsComp** [comment]
hmm that is strange indeed. I will have to check that. thanks

**Comment by ObsComp** [comment]
This has been fixed recently. Sorry for the delay
