### ISSUE TITLE
spawnz command is not working

### ISSUE THREAD

**Issue by WEEDMEN** [dmustanger/7dtd-ServerTools#246]
good friend, I'm executing the spawnz command but nothing happens, no zombies come out, with version 19.0.5 the "ser" command works correctly

**Comment by ObsComp** [comment]
I believe the issue is when using multiple id. You no longer need @ in the command but I also broke it when using multiple id. Sorry. I will fix it soon

**Comment by ObsComp** [comment]
This has been fixed. Sorry for the delayed response
