### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GrummeGert** [dmustanger/7dtd-ServerTools#247]
Can i easily set up more places like lobby/market? 
And whare can i find a complete command list?

**Comment by ObsComp** [comment]
In game you can type /commands. It will display all available commands for chat based on what tools are enabled. If you want to check the console commands, type help in the console. Any command that starts with st- is a Servertools command. You do not need to use st- for them but in case of command overlaps, that is an option.

You can setup custom commands that will bring players to an area like lobby and market. You could then setup a protected space around the area if need be. You can also set delays to custom commands so you can limit how often they could teleport in.

**Comment by ObsComp** [comment]
Does that cover your questions and did you need any other help?

**Comment by MkxTrax** [comment]
> Does that cover your questions and did you need any other help?

triggers help for custom commands would be lovely here Obs or additional variants of market and lobby that already work like market 2, 3 etc

**Comment by GrummeGert** [comment]
I find it really hard to find the full command line in cmd. It's not like an cisco hardware whare you can type help after your command and se your options, and there's no guides to find online. Help is short. 

So I'm on try'n fail.

**Comment by MkxTrax** [comment]
Hi Grumme this occurs when you have several mods installed as the console will only reveal so many lines and also lot of the help in there is still limited to its basic functionality. st-help is not working to show only st commands at present, but you may still be able to reveal the full list from all mod commands if you use clear then help

**Comment by MkxTrax** [comment]
Also use help st-lobby for lobby help, limited info but more than sufficient, ive also found it best to turn off and on ingame before adjusting any XMLs that are created. Also there is a howtosetup in the servertools folder but this has not been updated in a while. i have updated one based o my knowledge of the tool and findings and attach below to help you if possible.


[HowTO.txt](https://github.com/dmustanger/7dtd-ServerTools/files/5539580/HowTO.txt)

**Comment by GrummeGert** [comment]
> Also use help st-lobby for lobby help, limited info but more than sufficient, ive also found it best to turn off and on ingame before adjusting any XMLs that are created. Also there is a howtosetup in the servertools folder but this has not been updated in a while. i have updated one based o my knowledge of the tool and findings and attach below to help you if possible.
> 
> [HowTO.txt](https://github.com/dmustanger/7dtd-ServerTools/files/5539580/HowTO.txt)

Awsome thanks

Thats the info i needed
