### ISSUE TITLE
NetPackageDamageEntity ProcessDamage check

### ISSUE THREAD

**Issue by Aviator-Coding** [dmustanger/7dtd-ServerTools#248]
https://github.com/dmustanger/7dtd-ServerTools/blob/master/ServerTools/src/AntiCheat/ProcessDamage.cs#L28

![image](https://user-images.githubusercontent.com/5182697/96962841-99736c00-14d5-11eb-9be5-c4ec9270b151.png)

you can bypass the Server Check for the NetPackageDamageEntity if you instigator id is -1. Allows you to kill any Player in dm since you can execute kill on the client

**Comment by ObsComp** [comment]
Thanks man. For those that see this aside from yourself that already knows it, there is a patch out to help address multiple net packages
