### ISSUE TITLE
Problem with manipulated packages Help!

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#249]
Hello, the server manage is very good, very good job, but it keeps banning people for no reason with the package handling thing. I have that false, I am using version 19.2.3 since 19.2.5 stopped working the Zones.xml: / mode. How do I stop him from banning them anymore.

**Comment by MkxTrax** [comment]
> Hello, the server manage is very good, very good job, but it keeps banning people for no reason with the package handling thing. I have that false, I am using version 19.2.3 since 19.2.5 stopped working the Zones.xml: / mode. How do I stop him from banning them anymore.

Hey man, have you checked that all the relative files are updated? if you update via a ModManager you may have mixed data.

Also ensure there are no triggers to ban set in zones.xml response= section

**Comment by ObsComp** [comment]
You are correct. It was not a permanent solution so it did not get refined. We knew pimps were updating the game pronto to block the manipulation. Sorry for any issues it may have caused. It is no longer in ST. Please update to the latest version 19.3.2
