### ISSUE TITLE
New Function Travel won't work

### ISSUE THREAD

**Issue by Markezzz** [dmustanger/7dtd-ServerTools#25]
Hello all,

i want to use the new travel function, but it dont work on our server.
this is my code from the TravelLocations.xml:

```
<TravelLocations>
    <Travel>
        <location name="zone1" XYZmin="97,3,4" XYZmax="100,7,1" destination="146,30,1753" />
        <location name="zone2" XYZmin="83,3,-9" XYZmax="86,7,-6" destination="-2941,20,-70" />
        <location name="zone3" XYZmin="100,3,-20" XYZmax="97,7,-17" destination="-567,21,-3269" />
        <location name="zone4" XYZmin="114,3,-6" XYZmax="111,7,-9" destination="2558,23,90" />
        <location name="zone5" XYZmin="145,29,1753" XYZmax="147,32,1747" destination="96,14,-8" />
        <location name="zone6" XYZmin="-2935,19,-69" XYZmax="-2932,22,-69" destination="96,14,-8" />
        <location name="zone7" XYZmin="-557,20,3270" XYZmax="-555,23,3268" destination="96,14,-8" />
        <location name="zone8" XYZmin="2558,22,90" XYZmax="2555,25,88" destination="96,14,-8" />
    </Travel>
</TravelLocations>
```

and in the servertoolsconfig.xml:

`<Tool Name="Travel" Enable="True" />`

if i make a error to the code from TravelLocations.xml i get the error messages:

```
2018-01-06 17:56:13 708.413	ERR [SERVERTOOLS] Failed loading TravelLocations.xml: Document element did not appear. file:///home/steam/saves/ServerTools/TravelLocations.xml Line 1, position 1.
2018-01-06 17:56:13 708.413	ERR [SERVERTOOLS] Failed loading TravelLocations.xml: Document element did not appear. file:///home/steam/saves/ServerTools/TravelLocations.xml Line 1, position 1.
2018-01-06 17:56:13 708.416	WRN [SERVERTOOLS] Unexpected XML node found in 'travel' section: 3
        
2018-01-06 17:56:13 708.416	WRN [SERVERTOOLS] Unexpected XML node found in 'travel' section: 3
```

Unfortunately there is no entry in the Wiki or in the manual for this new feature.

**Comment by MkxTrax** [comment]
where do you have this installed pal at file:///home/steam/saves/ServerTools/TravelLocations.xml
looks like a local directory not a servers these will be similar Steam\steamapps\common\7 Days to Die Dedicated Server or a normal host will be /7DaysTodie/saves/servertools

**Comment by Markezzz** [comment]
We're running the server on linux, thats why it looks different to windows.
And it show only a error if i make intentionally a error in the config. so this is not the reason for the issue. :)

**Comment by ObsComp** [comment]
Your min and max values are not correct. Version 5.8 has a small fix for travel allowing a negative minimum number with a positive maximum. Please download 5.8 when it releases tonight and use these values in your Travel.xml:
<location name="zone1" XYZmin="97,3,1" XYZmax="100,7,4" destination="146,30,1753" />
<location name="zone2" XYZmin="83,3,-6" XYZmax="86,7,-9" destination="-2941,20,-70" />
<location name="zone3" XYZmin="97,3,-17" XYZmax="100,7,-20" destination="-567,21,-3269" />
<location name="zone4" XYZmin="111,3,-6" XYZmax="114,7,-9" destination="2558,23,90" />
<location name="zone5" XYZmin="145,29,1747" XYZmax="147,32,1753" destination="96,14,-8" />
<location name="zone6" XYZmin="-2932,19,-69" XYZmax="-2935,22,-70" destination="96,14,-8" />
<location name="zone7" XYZmin="-555,20,3268" XYZmax="-557,23,3270" destination="96,14,-8" />
<location name="zone8" XYZmin="2555,22,88" XYZmax="2558,25,90" destination="96,14,-8" />

There is no alert upon entering this zone currently. Make sure players are using /travel to trigger it.

**Comment by Markezzz** [comment]
Hello ObsComp,

thanks for your reply and the update.
All works fine now.
