### ISSUE TITLE
PvE Violations and Zones missing vital info!

### ISSUE THREAD

**Issue by MkxTrax** [dmustanger/7dtd-ServerTools#250]
<Tool Name="Zones" Enable="False" Zone_Message="False" Reminder_Notice_Delay="20"  />
ISSUE IS HERE <Tool Name="PvE_Violations" Jail="4" Kill="6" Kick="8" Ban="10" /> how to set when only option is True/False?

Set True or False for Enable
Set True or False for Zone_Message
Set a numeric value for Reminder_Notice_Delay

Enabling will create a Zones.xml in your main installation folder in a ServerTools folder
Automatically detects players locations to see if they match those listed in Zones.xml
Players will receive a message alerting them to entering the zone as well as when leaving.
It applies to both the killer and victim, if either one are protected, it will be detected.

ISSUE IS HERE **Automatically kills, jails, kicks, or bans the killer depending PvE_Violations.** However in Zones.xml options are  for PvE=True/False where do the violations get set? in the STconfig.xml it only shows     Tool Name="PvE_Violations" Jail="4" Kill="6" Kick="8" Ban="10"

thanks

**Comment by ObsComp** [comment]
When you create a zone within Zones.xml you can choose if you want it to be a PvE zone. That makes it so players shooting others while standing inside it or getting shot while inside one are detected. It should protect the person inside the pve area but also each hit against someone inside a pve space is considered a single violation. They are supposed to add up so if they get too many the PvE violation will kick in. I probably need to try it out again. Something must be wrong with it

**Comment by MkxTrax** [comment]
Thanks, makes perfect sense like obviously the help needs updating to include this info. I love this tool have since it came out. Your work is amazingly helpful. As a courtesy I have updated a howto file for you based on findings and use. I hope you dont mind just a bit of a time saver for I would be happy to help with updating your wiki too as a support method to assist you, anytime.  

[HowToSetupST.txt](https://github.com/dmustanger/7dtd-ServerTools/files/5736466/HowToSetupST.txt)

**Comment by ObsComp** [comment]
There was an issue with this but it has been fixed in more recent versions. Let us know if you have any more problems.
