### ISSUE TITLE
[SERVERTOOLS] Detected a new or unplayed map and old save data. Old data has been cleared from ServerTools

### ISSUE THREAD

**Issue by Zeddy96** [dmustanger/7dtd-ServerTools#253]
Why does it do this sometimes on server restarts after i edit something completely not related to server tools... 
It has reset /home of people about 3 times now and its starting to become annoying.., people go far away from base to then reconnect to having no more /home set.

Console : [SERVERTOOLS] Detected a new or unplayed map and old save data. Old data has been cleared from ServerTools

Edit : I also get this a couple of messages before in console if it has anything to do with this.., : [SERVERTOOLS] Injection failed: GameManager.ChangeBlocks method is already modified by another mod

I havent touched any map or save data only loot.xml to change 1 minor thing.

**Comment by MkxTrax** [comment]
You have a conflict with another MOD both using a same command and both active/ Webhook is overriding servertool function?

**Comment by Zeddy96** [comment]
Allocs or CSM are only ones that could be doing this., do you know if i can disable this on one of them to prevent the issue or the need of removing either of these other mods?

**Comment by ObsComp** [comment]
Please update to more recent version of ServerTools. This has been addressed. The latest is version 19.3.1

Make sure you server is off. Install the files as you did the first time but overwrite the existing files and start your server. It will detect the version change, copy your existing xml files and update your main ServerToolsConfig for you while keeping your settings.

Let me know if you have any more issues with this
