### ISSUE TITLE
Zones issue

### ISSUE THREAD

**Issue by gilvertoo** [dmustanger/7dtd-ServerTools#258]
Hi guys!

I have a fully dedicated 7 days to die server. I have been using the zone messages for 3 years. Only the message, no pve or anything. but after this complete wipe when I enable the zone message, then a constant error appears in the terminal window. 

The eroor is this:

 INF [SERVERTOOLS] Error in ProcessDamage.ProcessPlayerDamage: Object reference not set to an instance of an object

I wouldn't even care about the error, but it takes down the server fps a lot!
I would appreciate it if anyone could help!
thank you

**Comment by ObsComp** [comment]
I believe this is fixed in the latest version 19.3.1

Sorry for the delay. Let me know if it continues
