### ISSUE TITLE
Admin Commands

### ISSUE THREAD

**Issue by Redbuck71** [dmustanger/7dtd-ServerTools#259]
How do I find the list of commands and the way to implement some of these aspects to my server?

**Comment by ObsComp** [comment]
If you are looking for console commands, type help in console. All servertools commands have a st- prefix to help identify them. For more info on each command type help 'command name', example: help st-bounty

chat based commands are seen by using /commands in chat. They are shown based on which tools you have enabled.

Tools are enabled via the ServerToolsConfig.xml or the console
