### ISSUE TITLE
Feature Request: Make /travel work with minibikes

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#26]
Request to make /travel work while on minibike like /home command.

**Comment by ObsComp** [comment]
Okay, thanks. I will look into it

**Comment by ObsComp** [comment]
I will attempt this in version 7.0

**Comment by ObsComp** [comment]
Added a bike travel option for 7.0.  Make sure you are riding the bike when you type /travel. It will set that bike for the travel and ask you to get off it. Get off the bike and type /travel again. You and the bike will now teleport to your destination :) .  After the bike is set, the bike will only come with you for up to 1 minute.

**Comment by markrjackson** [comment]
So how does /home do it. /home teleports while being on minibike. Just curious...
