### ISSUE TITLE
Error in ProcessDamage

### ISSUE THREAD

**Issue by WEEDMEN** [dmustanger/7dtd-ServerTools#261]
hi how are you
this message appears a lot on my console, do you know why? I am using the latest version 19.3

2020-12-05 23:11:16 | INF [SERVERTOOLS] Error in ProcessDamage.ProcessPlayerDamage: Object reference not set to an instance of an object
-- | --

**Comment by ObsComp** [comment]
I believe it was a change over from an internal request for item names. It has been changed in the version I just released. Let me know if you have any more issues with it
