### ISSUE TITLE
Banking Doesn't Work

### ISSUE THREAD

**Issue by MrSmallZzy** [dmustanger/7dtd-ServerTools#262]
Players can check their bank but can not deposit coins into their bank.

**Comment by ObsComp** [comment]
I will have to test this and see. Sometimes it is a mix up of commands. You either put coins in a chest and stand by it then type /bank deposit $$$ or take them from the wallet and put them in the bank with /wallet deposit $$$. There are also options to control this. Make sure they are turned on

**Comment by MrSmallZzy** [comment]
I managed to get it working by just removing /bank from the command. It
works by putting casinoCoin in a secure chest or storage crate in the first
slot and typing in /deposit #.

**Comment by ObsComp** [comment]
ah yes see now I mixed up the commands hahha. Glad you figured it out.
