### ISSUE TITLE
Overlapping zones

### ISSUE THREAD

**Issue by Zipcore** [dmustanger/7dtd-ServerTools#264]
Overlapping zones are not fully working since they use the same dictionary to keep track of players are inside which zone.
Would be nice to see this resolved someday to allow overlapping zones which is already a problem with your example configs since you have North + South + other zones.

Same issue when zones touch each other or are close and you travel fast between them.

**Comment by ObsComp** [comment]
If you wish for a zone to reside inside of another larger zone, make sure it is listed higher in the zone list. As an example.
Zone 1 is all of the north. Zone 2 is all of the south. If you added zone 3 and it is inside zone 1, make sure it is listed prior to the one it resides in. You would shift zone 1 to zone 2, zone 2 to zone 3 and put the new one as the first on the list. Vice versa if you wish it to go the other way

**Comment by ObsComp** [comment]
I will have to test out touching zones and see if I can improve on how it functions

**Comment by ObsComp** [comment]
I will fix the examples and add a note to the xml at the top about zone order. Thank you for the report

**Comment by Zipcore** [comment]
looking forward

**Comment by ObsComp** [comment]
Meow
