### ISSUE TITLE
new to all this 

### ISSUE THREAD

**Issue by Arixon1984** [dmustanger/7dtd-ServerTools#266]
Hello i cant find any answers and im new to this i posted my issue on few forums so far now reply

Warning | [SERVERTOOLS]  Ignoring Zones entry because of missing Corner1 attribute zone  corner1="-1,2,7" corner2="0,4,7" Circle="false" Name="RESET ZONE"  EntryMessage="You are entering the RESET ZONE! DONT BUILD HERE!"  ExitMessage="You have left the RESET ZONE! " Response=""  ReminderNotice="You are still in the RESET ZONE" PvE="false" NoZombie="false"  Protected="True" had to put it without<../>. as it wouldnt display the full error line.
whats wrong with this line? it has the corner attribs but claims its missing ? what am i doing wrong? or is it the fault of the program? i wanna know cause im new in this and no one wants to give me an answer please let me know what do i do wrong if it is me as in the file there is no specific info how are these coords input in the line cheers.

**Comment by Arixon1984** [comment]
Supposedly my map values were wrong so i corrected them still the same problem persists. Suggestion you should include some proper info on how exactly configure and input the information its frustrationg to waste hours upon hours for people that are new to this to figure it out. it supposed to help ppl save time instead here we have the opposite and the worst thing about the situations is no one is willing to explain even on the 7dtd forums.Back to the problem though 👍 

Warning | [SERVERTOOLS]  Ignoring Zones entry because of missing Corner1 attribute: <zone  corner1="1772,81,1660" corner2="-1412,81,1908" Circle="false"  Name="RESET ZONE" EntryMessage="You are entering the RESET ZONE! DONT  BUILD HERE!" ExitMessage="You have left the RESET ZONE! " Response=""  ReminderNotice="You are still in the RESET ZONE." PvE="False"  NoZombie="False" Protected="False" />
-- | --

Warning | [SERVERTOOLS]  Ignoring Zones entry because of missing Corner1 attribute: <zone  corner1="1772,81,1660" corner2="-1412,81,1908" Circle="false"  Name="RESET ZONE" EntryMessage="You are entering the RESET ZONE! DONT  BUILD HERE!" ExitMessage="You have left the RESET ZONE! " Response=""  ReminderNotice="You are still in the RESET ZONE." PvE="False"  NoZombie="False" Protected="False" />

Warning | [SERVERTOOLS]  Ignoring Zones entry because of missing Corner1 attribute: <zone  corner1="1772,81,1660" corner2="-1412,81,1908" Circle="false"  Name="RESET ZONE" EntryMessage="You are entering the RESET ZONE! DONT  BUILD HERE!" ExitMessage="You have left the RESET ZONE! " Response=""  ReminderNotice="You are still in the RESET ZONE." PvE="False"  NoZombie="False" Protected="False" />
[SERVERTOOLS] Ignoring Zones entry because of missing Corner1 attribute: <zone corner1="1772,81,1660" corner2="-1412,81,1908" Circle="false" Name="RESET ZONE" EntryMessage="You are entering the RESET ZONE! DONT BUILD HERE!" ExitMessage="You have left the RESET ZONE! " Response="" ReminderNotice="You are still in the RESET ZONE." PvE="False" NoZombie="False" Protected="False" />

**Comment by Zipcore** [comment]
I don't think this has anything todo with your corner1 attribute, thats just the first attribute which is being checked.
Can you privide the full config file to see if there is a syntax issue? You could use a website like https://hastebin.com/ to share code

**Comment by Arixon1984** [comment]
Its cool i got it sorted seems like the major issue was the capital letters in the line on corners lol 
Line that works now:
zone Name="RESET ZONE" Corner1="1780,-56,1925" Corner2="1402,200,1650" Circle="false" EntryMessage="You are entering the RESET ZONE! DONT BUILD HERE!" ExitMessage="You have left the RESET ZONE! " Response="" ReminderNotice="You are still in the RESET ZONE." PvE="False" NoZombie="False" Protected="True"
cheers for the reply and the willingnes to help :)

**Comment by Arixon1984** [comment]
i have an issue with this line again but its something diffrent i changed the protected=False but its now despawning zombies in the town that i had the zone on protected?! LOL it messes with everything and ruins the server experience? why is it despawning zombies in that zone? i thought nozombies was for despawning?
