### ISSUE TITLE
Airdrop as a voting reward

### ISSUE THREAD

**Issue by Killom** [dmustanger/7dtd-ServerTools#267]
Greetings!

Back in 2015 there was an external tool which checks for voting on 7daystodie-servers.com and spawning an air drop crate as reward for players. This was way fancyer than just putting some stuff into players inventory. Missing this tool now. 😢 

Can you implement this into server tools as alternative for votereward.xml? Maybe also with option to either fly in with regular airship and dropping on players position, or just spawn within 2 blocks of players current position. (determned via parameter - or if admin wants to let players decide: determined by the use of '/' and '!' -> '/' Spawns at player; '!' Flies in with airship)

Possible to dynamically modify air drop contents for vote reward crates? -> CrateReward.xml

**Comment by ObsComp** [comment]
It is a viable option. The reward system allows you to spawn an entity.

<Tool Name="Voting" Enable="True" Your_Voting_Site="https://7daystodie-servers.com/server/12345" API_Key="xxxxxxxx" Delay_Between_Uses="24" Reward_Count="1" />
    <Tool Name="Voting_Extended" Reward_Entity="False" Entity_Id="73" Weekly_Votes="5" />
    
    Change your config to utilize Reward_Entity and Entity_Id. You need to create a new entity on your server using the base air drop but customized. Then you create a loot table with the items you want to possibly spawn for them in the crate. It will spawn the air drop for them near by.
    
    This method runs a few risks which is why most servers do not use it anymore. Air drops and the crates themselves can occasionally spawn underground or inside a wall, causing terrible lag. They can have trouble finding a valid spawn point near the player depending on where they are because it avoids player created blocks. Those are not valid spawn points. There are a few other things that can happen with that approach but it is a valid and possible method. 
    
    ServerTools does not handle it automatically as an option due to the server needing to input the proper entity id and they most likely want to use a custom one with a custom loot table. Those are both xml modification and not something ST is focused on. ST is meant for managing servers, not altering your base game files with modded xml.
    
    I hope that helps but if you need more info, feel free to inquire further
