### ISSUE TITLE
ReservedSlots vip problem!

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#268]
reserver slot vip. I'm having a problem with that parameter, I put the player's id but it doesn't expel a player that isn't on the list. I don't know if it is this new version "ServerTools-19.3.2" of the servertools or it is the game, I did not try with the current version that always used the "ServerTools =" 19.0.11 "

```
<ReservedSlots>
    <Players>
        <Player SteamId="76561191234567891" Name="Test" Expires="10/29/2050 7:30:00 AM" />
        <Player SteamId="76561198197303946" Name="Vermouth" Expires="02/10/2021 7:30:00 AM" />
        <Player SteamId="76561198073223182" Name="DarkMago" Expires="02/10/2021 7:30:00 AM" />
        <Player SteamId="76561198371765414" Name="Pablerik" Expires="02/10/2021 7:30:00 AM" />
        <Player SteamId="76561198034031943" Name="On3" Expires="02/10/2021 7:30:00 AM" />

    </Players>
</ReservedSlots>
```

so I have it set!

**Comment by ObsComp** [comment]
Sorry for the late response. Is this still a problem for your server?
