### ISSUE TITLE
Set backup schedule to absolute times

### ISSUE THREAD

**Issue by Killom** [dmustanger/7dtd-ServerTools#269]
Hi there, its me again.

Would it be possible, to implement a "fixed" schedule for backups? Atm. it is every x hours after starting the dedicated. (so x hours + random minute offset, depending on startup time) I'd rather be able to do backups always at specific times. Like every 3 hours beginning at 0:00 o'clock

**Comment by ObsComp** [comment]
Not yet, however I just implemented an event schedule in 19.4.0 which will allow hard coded time spans so this feature will be added soon
