### ISSUE TITLE
Bedroll despawning when placed using "remove falling blocks option" latest Release

### ISSUE THREAD

**Issue by Dingoking40** [dmustanger/7dtd-ServerTools#271]
Using the 19.3.2 Release of Servertools on a patch 19.3 dedicated server with the "remove falling blocks" option enabled, when placing down a bedroll it immediately despawns and gives the message "Your bedroll is gone."

**Comment by ObsComp** [comment]
Are you sure this only applied when remove falling blocks was enabled?

There was a internal tool to help with a bed bug issue in version 19.3.2. This has been removed in 19.4.0. Please give it another try and let us know.

**Comment by ObsComp** [comment]
This has been fixed in 19.4.1. Very sorry for the problem. It was effecting other blocks too but prevention has been added. If you see it occur with any other blocks, let us know
