### ISSUE TITLE
Hardcore not working

### ISSUE THREAD

**Issue by Zero9606** [dmustanger/7dtd-ServerTools#274]
Hardcore enabled in Server Tools, optional enabled

When typing /hardcore on it tells me "You are already signed up for hardcore..etc type /hardcore"
When i typ /hardcore it says "You have to turn on hardcore mode"

Anything iam missing or is this just not working?

**Comment by ObsComp** [comment]
Sounds bugged. I will run tests and get it up to date for next release.

**Comment by ObsComp** [comment]
This should be working properly now. I had fixed your reported bug but made some new ones and did not realize until recently. It should all be working an intended now
