### ISSUE TITLE
19.3.2 Jail Command Not Working Properly

### ISSUE THREAD

**Issue by bradleyclay81** [dmustanger/7dtd-ServerTools#275]
I have built a jail on my server and set the co-ordinates to the prison cell that i want them but im just getting this and cannot move around freely?
![image](https://user-images.githubusercontent.com/78207083/106263272-11aba500-621c-11eb-8af6-f7de8e5d4e72.png)

![image](https://user-images.githubusercontent.com/78207083/106262958-a6fa6980-621b-11eb-888e-b156a3ee53f3.png)

**Comment by Davinel17** [comment]
are you sure you are not get teleport into a wall or something ? 
me it working fine.

**Comment by ObsComp** [comment]
This was a problem with a version not too long ago. Please update to the latest version 19.4.0 and let us know if it persists.
