### ISSUE TITLE
Real World Time Chat ist blank

### ISSUE THREAD

**Issue by HagbardCeline32** [dmustanger/7dtd-ServerTools#276]
Real World Time is not sending any text to ingame Chat.
It looks like the phrase id is wrong. 
realworldtime.cs is looking for  _phrase823 in servertoolsphrase.xml id is 471.
have testet adding text from id 471 to id 823 in phrase.xml
now it´s working.

**Comment by ObsComp** [comment]
The phrases were updated a while back. The internal code runs phrase 471 so whatever 471 is in your phrases.xml should be what is shown in game. Please confirm this is still an issue for you in 19.4.0 which is the latest release.
