### ISSUE TITLE
Rented Server Compatability?

### ISSUE THREAD

**Issue by VividDreamKillr** [dmustanger/7dtd-ServerTools#277]
I am looking to get these server tools set up for the server I run for me and my friends. We are looking to get this set up for our server and would love some help to get this done.
We are willing to work with you to test and provide feedback as needed if you would like. 
Thanks!

**Comment by Davinel17** [comment]
the HowToSetUp.txt is not up-to-date but with that you can easly install , configure and test it yourself and with your friend for somes features

so you need help with what ?

**Comment by ObsComp** [comment]
Dav is correct. The How To Setup covers most of the basic stuff to get going and about 75% of the tools. It needs a major over haul though which I will be working on for the next patch.

Do you need help with basic installation or setting up your configuration?

**Comment by ObsComp** [comment]
The How to Setup has been updated in 19.4.4

You can join us at our discord channel for more direct support.
