### ISSUE TITLE
Issue finding servertools config files

### ISSUE THREAD

**Issue by Zefland** [dmustanger/7dtd-ServerTools#279]
Not sure if I did it right, but I already had a mod folder in my directory, so I pasted the servertools folder into that. It showed that it was successful during the load up, but I don't know where the folder is or what I'm doing wrong. Sorry. I rent a dedicated server from GTXgaming. Any help is appreciated. 

**2021-02-09T10:51:02 1.353 INF [MODS] Trying to load from folder: ServerTools
2021-02-09T10:51:02 1.354 INF [MODS] Loaded Mod: Server Tools (19.3.2)**

**Comment by ObsComp** [comment]
Yes that looks correct. After the server has finished loading, it should have made a new folder called ServerTools inside the main directory of your server. The same location as the Mods folder, but not inside of the Mod folder. It is a stand alone folder. Inside of this new folder you should have the ServerTools config and various files required for customizing your experience.

Does this help or do you require more assistance?
