### ISSUE TITLE
No multiple homepoints

### ISSUE THREAD

**Issue by Thodde26** [dmustanger/7dtd-ServerTools#28]
Hi, the multiple homes have been removed. That would be a pity. Thank you for including so many new things.

Best Regards
Thodde26

**Comment by ObsComp** [comment]
Multi homes should be working in the latest release. I will run some tests to make sure.

**Comment by Thodde26** [comment]
Ok thanks
Best Regards
Thodde26

**Comment by ObsComp** [comment]
Multiple home points are available to regular players or just donors. You can set it via config in version 6.0
