### ISSUE TITLE
So there is linux support but the backups?

### ISSUE THREAD

**Issue by devliquid** [dmustanger/7dtd-ServerTools#280]
Im using ubuntu server 20.04 and so this is the mount point for my backup drive , also the folder has been chmod 0777 but its been 3 hours and its still not running. Do I need to change this to something else? Destination="/mnt/backup/hardcore" Tested it on a windows server and it works but does not seem to even try to run on the Linux server.

**Comment by devliquid** [comment]
Ok never mind its working it was a permission problem it works great! Do you have a Discord Server that i can join for all this?

**Comment by ObsComp** [comment]
Hey, sorry for the delayed response. I have not been receiving any notices in my email like it should.

Yes we have a discord, you might have found it already but just in case you have not, the invite is 6G8VZQg. Hope to see you there
