### ISSUE TITLE
Is it possible to protect the server?

### ISSUE THREAD

**Issue by Demon-MC** [dmustanger/7dtd-ServerTools#282]
I ran into a problem in the game. Through motion sensors and turrets, players look through textures. How can this be prohibited?
Link to the video [https://skr.sh/v6rJgGbbHDt?a](url)

**Comment by Zipcore** [comment]
There are countless glitches like that and even much more simple ones.

**Comment by ObsComp** [comment]
As Zipcore said its in the base game unfortunately. There are some programs out there designed to help with this tho. I am merging one of these in from our partner who has been working on it separately. To answer your question, yes it is possible and it is coming but do not expect anything perfect. It is merely a helpful tool that will reduce how much players can achieve that glitch in game until the develops deal with it
