### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by egik152** [dmustanger/7dtd-ServerTools#283]
Localization. Translation into other languages is possible! The ServerToolsPhrases file is easy to open and translate into your own or someone else's language. But there is a problem. This halyard doesn't have all the offers. For example, "Your charisma has blossomed through your prayer\", "You can fall without taking damage by the grace of your prayers\","Your prayers have developed in to a higher chance to cripple\"," Your prayers have been answered with auto weapon knockdown damage\ " and probably much more. The suggestions are taken from the file 7dtd-ServerTools-19.3.2. zip\7dtd-ServerTools-19.3.2\ServerTools\src\Tools\Prayer.

**Comment by ObsComp** [comment]
This is true, you can alter most of the phrases offered through ST. I may have missed some. I believe in this case you are referring to the Prayer.xml file. You can change those messages in the Prayer.xml file itself rather than through Phrases.xml

**Comment by egik152** [comment]
thanks)
