### ISSUE TITLE
Harcore extra life purchase seems to be free

### ISSUE THREAD

**Issue by CyclopDog** [dmustanger/7dtd-ServerTools#284]
Greetings, just got started with your tools, which are pretty awesome, and I was wondering about the 'buy life' implementation, when I was testing it, once I used the command '/buy life' it immediately made the purchase even though my wallet had 0 coins in it, the second purchase attempt was not successful as it seems to have made the proper funds check.

Is there any way I can buy you a coffee?

**Comment by CyclopDog** [comment]
I think I see what the problem is here:

`int _cost = Life_Price * _extraLives;`

checks for extra lives, but if the player has 0 extra lives then it is just going to cost 0 coin, I believe an if conditional setting it to Life_Price if extraLives == 0 would remedy that.

**Comment by CyclopDog** [comment]
I found this to be a better solution:

`int _cost = Life_Price * (_extraLives + 1);`

**Comment by ObsComp** [comment]
Ah! Thank you. You are correct. I will address this in the upcoming patch

**Comment by ObsComp** [comment]
This is fixed in 19.4.2
