### ISSUE TITLE
Block During Bloodmoon New Player

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#288]
I activate this mode and a friend who is level 120 could not enter the blood moon.

**Comment by servermasterzombie** [comment]
Did you increase the chance of bloodmoon warrior to 100?

**Comment by LPMZ** [comment]
I have that option disabled. Does it have something to do with it?

**Comment by servermasterzombie** [comment]
its the probability someone will recieve the message from 1-100%, set it to 100, every bloodmoon my guys get the message.

**Comment by LPMZ** [comment]
I'm trying to give these items to the players but it doesn't work. You know why it could be? I changed the name of the items because if the names have spaces it doesn't work but now I put - I don't know if it's okay. 

<?xml version="1.0" encoding="UTF-8"?>
<BloodmoonWarrior>
    <Items>
        <Item Name="Nota:-Desert-Vulture-lvl-7" SecondaryName="Desert Vulture lvl 7" MinCount="1" MaxCount="1" MinQuality="1" MaxQuality="1" />
        <Item Name="Nota:-Rifle-de-asalto-M4-lvl-7" SecondaryName="Rifle de asalto M4 lvl 7" MinCount="1" MaxCount="1" MinQuality="1" MaxQuality="1" />
        <Item Name="Nota:-Armadura-Legendaria" SecondaryName="Armadura Legendaria" MinCount="1" MaxCount="1" MinQuality="1" MaxQuality="1" />

    </Items>
</BloodmoonWarrior>

**Comment by ObsComp** [comment]
It doesnt like spaces, that is correct. It probably doesnt like the symbol : either since that is used in programming

**Comment by ObsComp** [comment]
You are asking two separate question here. First you are asking why your friend could not join and then you are curious about spaces being used inside the xml file.

Did you still need help with your friend and that tool?

**Comment by ObsComp** [comment]
I can see the problem with the blocking during bloodmoon for noobs. It was meant to be for new players but its applying to everyone. I will get that fixed up

**Comment by LPMZ** [comment]
if what happens that the user servermasterzombie intrigued me about warrrior blood. hehe I started testing it. (A player warned me that he only gave the one that says "Note: -Legendary-Armor"

**Comment by ObsComp** [comment]
The reward for the bloodmoon warrior is a single item from that list you create. It is not the entire list and does not allow you to choose how many from the list currently

**Comment by ObsComp** [comment]
Updated Bloodmoon_Warrior to allow multiple items in the reward. Try the latest release 19.4.4

I have fixed the player entry on bloodmoon.

Let me know if you have any more issues
