### ISSUE TITLE
Indestructible Areas

### ISSUE THREAD

**Issue by OmitLeChuck** [dmustanger/7dtd-ServerTools#289]
Hello,

this is not meant to be a message about an issue at all, but rather a wish.
It would be pretty cool to be able to define areas that are protected similar to the Trader.

The option would then probably be something like: Indestructible_areas = True with admin level query.
Then a new XML file where these areas can be defined. Attributes for the respective area can then be the following:
- Upper corner x,y,z
- Lower corner x,y,z
- Name 
- Teleport true/false (enable teleport)

For example, this would currently prevent the lobby on my server from being destroyed by trolls at regular intervals.

**Comment by Zipcore** [comment]
You can't use the trader protection while allowing admins to damage blocks

**Comment by ObsComp** [comment]
^ There is already a tool called Protected_Spaces which will protect areas as if they were trader spaces. Admins can not build inside them due to the internal code of the game. I have not found a way around it while maintaining block protection.

**Comment by ObsComp** [comment]
Just fixed this tool since it was having some problems. Please use 19.4.4 if you wish to use Protected Spaces which act as you said like a trader space
