### ISSUE TITLE
bank transfer not working in 19.4?

### ISSUE THREAD

**Issue by ironlungs85** [dmustanger/7dtd-ServerTools#292]
No matter how i try it i cannot get /bank deposit # to work at all. I have it set to be used within a claim zone and transfers are enabled. All other enabled features work from the xml. thanks

**Comment by ironlungs85** [comment]
also the casinoCoin is stored inside a secure chest.

**Comment by ObsComp** [comment]
Try /deposit #. Drop the /bank part.

**Comment by ObsComp** [comment]
There is /deposit # to transfer from a secure chest to the bank and there is /wallet deposit # to transfer from the wallet to the bank
