### ISSUE TITLE
Homes only works from a claim

### ISSUE THREAD

**Issue by Pesimus** [dmustanger/7dtd-ServerTools#294]
![cc633b2e4c13f512686a923a4b1c073f](https://user-images.githubusercontent.com/20616670/115594513-1e4d1000-a2d6-11eb-880e-074f489f825f.png)
I try to go home and it says "You can only teleport to a home that is inside of a claimed space", I am transporting myself to an claimed space but since I am not in a claimed space it does not take me home, however I use the command inside of my claim works and transports me.

**Comment by ObsComp** [comment]
You are correct. 
19.4.2 is out with a fix for it. 
Let me know if you have any more issues.
