### ISSUE TITLE
lost money, save poin if sever crash

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#296]
lost money, save poin if sever crash, or close with X icon on top, and im only use command shutdown is good but my sever some time crash all data , money. save, clan gone!

**Comment by ObsComp** [comment]
Are you losing data after a normal shutdown or only when it crashes? There is an auto backup system. You could take the ServerTools.bin from the last save and place it back in if something like that happens.

**Comment by batboyboy1990** [comment]
> Are you losing data after a normal shutdown or only when it crashes? There is an auto backup system. You could take the ServerTools.bin from the last save and place it back in if something like that happens.

yes crashes!

**Comment by batboyboy1990** [comment]
> Are you losing data after a normal shutdown or only when it crashes? There is an auto backup system. You could take the ServerTools.bin from the last save and place it back in if something like that happens.

and Phrases.xml - EventTriggers.xml - zone.xml not work like ols version

**Comment by ObsComp** [comment]
Those xml were updated and need to be refreshed. You can manually add your entries back to them after letting them rebuild new or compare the changes and make them accordingly to your older version.

If you have an old ServerTools.bin file running from a prior patch, try deleting it. Your players will lose their wallets, homes and waypoints but it should stop losing data after that.

**Comment by batboyboy1990** [comment]
> Those xml were updated and need to be refreshed. You can manually add your entries back to them after letting them rebuild new or compare the changes and make them accordingly to your older version.
> 
> If you have an old ServerTools.bin file running from a prior patch, try deleting it. Your players will lose their wallets, homes and waypoints but it should stop losing data after that.

thanks !  its work!
