### ISSUE TITLE
Hello, how to delete home

### ISSUE THREAD

**Issue by maomiblog** [dmustanger/7dtd-ServerTools#300]
ServerTools19.4.3

Hello, how to delete home
There is no instruction for some commands, and there is no output when directly input
Please update HowToSetup.txt, thank you very much

**Comment by ObsComp** [comment]
Yes sir. I have updated it for next release. It is similar to waypoints. If you had a prior version then you must also delete your phrase.xml and eventtriggers.xml to allow the new home setup to work properly. After that you can use /commands to show in game chat commands. The command is /home del 'name'. /sethome 'name' . /home save 'name'. /home 'name'. /home are the new commands.

**Comment by ObsComp** [comment]
It has all been updated in the latest release. You can also turn off certain commands if you dont like there being two versions /home save '' and /sethome ''.  Putting *** as the alternative trigger in EventTriggers.xml will prevent whatever command you set as that.

How to setup has been updated in 19.4.4

Let us know if you have any problems or suggestions
