### ISSUE TITLE
Web panel does not start because of invalid enum lookup

### ISSUE THREAD

**Issue by Tsaukpaetra** [dmustanger/7dtd-ServerTools#302]
https://github.com/dmustanger/7dtd-ServerTools/blob/fbaa3f4e9cd0c4d591caeadca12317781f7fdf30/ServerTools/src/WebPanel/WebPanel.cs#L188

I'm using build 19.4, and the web panel does not start because it is looking up `TelnetPanelPort`, which does not exist? I think it's called `TelnetPort`.

This should probably be wrapped in a try-catch?

**Comment by maomiblog** [comment]
https://github.com/dmustanger/7dtd-ServerTools/issues/299

**Comment by ObsComp** [comment]
Yes I have fixed this in the latest release 19.4.4
Thank you for the report
