### ISSUE TITLE
ws add command not working for me

### ISSUE THREAD

**Issue by reserect** [dmustanger/7dtd-ServerTools#305]
Hi trying to use the ws add (steamid) command and it keeps coming back with unknown command in game and through the dedicated server console.

**Comment by ObsComp** [comment]
Ah the console commands for the website were updated. 

Type help * st- to see a list of servertools commands
You can then type help 'command' for more information

Example: help st-web

The command is now "st-Webpanel", "web", or "st-web"

web add (steamid)
