### ISSUE TITLE
ProtectedSpaces Falling_Blocks_Remover version 19.4.5

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#308]
Hello, some problems that I found. ProtectedSpaces Hangs the server for a few minutes each time it starts. A long list appears that seems not to stop ... 2021-05-23T13: 57: 18 79.582 INF [SERVERTOOLS] Adding unloaded area 1752 @ -2329 998
2021-05-23T13: 57: 18 79.584 INF [SERVERTOOLS] Adding unloaded area 1802 @ -2328 931
2021-05-23T13: 57: 18 79.586 INF [SERVERTOOLS] Adding unloaded area 1850 @ -2328 979
2021-05-23T13: 57: 18 79.589 INF [SERVERTOOLS] Adding unloaded area 1899 @ -2327 911

Falling_Blocks_Remover Not working as it should. In the previous version the blocks disappeared quickly that is good not to generate lag. Now it is no longer of use.

**Comment by ObsComp** [comment]
Yeah Im not liking how it handles it right now. I will change that a bit.

I will run some test on the falling blocks and let you know. I changed it from before so Im not surprised to find it running differently.  I should be able to sort that out tho

**Comment by LPMZ** [comment]
OK, thanks a lot!! Mister!!!

**Comment by ObsComp** [comment]
The tool was modified as you know. It is more accurate now and should be removing the blocks properly.
