### ISSUE TITLE
Set Home

### ISSUE THREAD

**Issue by AngelEyez1976** [dmustanger/7dtd-ServerTools#309]
Hello I've been trying to use home teleport for hours, no matter what I enter / set home name or / home save name, I always get the message You have no homes saved what am I doing wrong
![Screenshot_100](https://user-images.githubusercontent.com/57451955/119659170-37456580-be2e-11eb-89c5-febbc6d0b33d.png)
![Screenshot_101](https://user-images.githubusercontent.com/57451955/119659251-47f5db80-be2e-11eb-8418-3f0b323c0cd9.png)

**Comment by shortybsd** [comment]
First set down a Claim Block, then run the command /sethome Test. Next leave your home area, type /home Test.

**Comment by AngelEyez1976** [comment]
i try it its not working https://www.youtube.com/watch?v=rnzeB2Nx-uI

**Comment by shortybsd** [comment]
What version are you running? Please download [19.4.5](https://github.com/dmustanger/7dtd-ServerTools/releases/tag/19.4.5)

**Comment by AngelEyez1976** [comment]
i´m use the version 19.4.5 in the log´s ar noting so in the server console ist no error 
![Screenshot_107](https://user-images.githubusercontent.com/57451955/120068817-fa25e100-c082-11eb-82bb-22b600eb75ff.png)

**Comment by shortybsd** [comment]
Have you tried to shut down the server, backup your config (ServerToolsConfig.xml), overwrite ServerTools with the same version in case something was corrupt with other one then copy back over your ServerToolsConfig. Also, there will be logs under ServerTools\Logs. You will have to enable certain things to log in ServerToolsConfig.xml.

Please pastebin your output_log and edit out any personal things like IP address, server password and so forth. I am wondering if upon server startup if ServerTools said it initialized successfully. Example:
```
2021-05-29T11:46:18 51.352 INF --------------------------------
2021-05-29T11:46:18 51.352 INF [SERVERTOOLS] Tool load complete
2021-05-29T11:46:18 51.352 INF --------------------------------
2021-05-29T11:46:18 51.352 INF StartGame done
2021-05-29T11:46:18 51.362 INF [Steamworks.NET] GameServer.Init successful
```

**Comment by ObsComp** [comment]
Try and delete your phrases.xml and eventtriggers.xml with the server off. when it reboots it should rebuild those files for you and i believe will work for you.

**Comment by ObsComp** [comment]
Hi it is not case sensitive and yes people have had the issues getting used to it. Before you would type /sethome1 and now you use /sethome 1 or any name you want. I am thinking of making it where typing sethome will auto set it to the next available slot, if there is one and name it for them and so when they type /home it will mention the name and should click after that

I will update it on next release

________________________________

**Comment by ObsComp** [comment]
There have been a few updates and no further reports of this issue. I am closing this report but please let us know if it still exists for you
