### ISSUE TITLE
ST-ResetPlayerProfile says steamid is not a valid integer

### ISSUE THREAD

**Issue by SirQwerx** [dmustanger/7dtd-ServerTools#311]
Hello - when attempting to reset a player profile on my server, I enter the command as: 
      rpp 765611981221##### 
(The hashmarks are the remainder of the steam id obscured for privacy.) The server says it is not a valid integer, every time.  do I need quotes or something?

**Comment by ObsComp** [comment]
I will work on this for next patch

**Comment by ObsComp** [comment]
This is fixed in the upcoming version 19.6.3
Thank you for the report
