### ISSUE TITLE
bad word filter does not work on the latest version

### ISSUE THREAD

**Issue by Demon-MC** [dmustanger/7dtd-ServerTools#313]

**Comment by Demon-MC** [comment]
bad word filter does not work on the latest version

**Comment by ObsComp** [comment]
Okay, thank you. I will work on it.

**Comment by ObsComp** [comment]
I have tested it with 19.6.0 and 19.6.1 and have no issues. Double check your BadWords.xml file is up to date and using the proper attribute tags. The latest version will auto update your xml files to their latest version and attempts to retain the data for you so I recommend updating to 19.6.1 and let us know if this problem persists for you
