### ISSUE TITLE
A longer timeout for Server Disconnected You: Network Timeout

### ISSUE THREAD

**Issue by BoQsc** [dmustanger/7dtd-ServerTools#315]
# The need to change Netowork Timeout lenght
Sometimes when you do nothing on the server you might get Network Timeout soon.
Most of the time it is unnecessary and the timeout might happen too early.
I'd like to know if it would be possible to implement a way to extend the Network Timeout.

![image](https://user-images.githubusercontent.com/21064622/124272836-f258d100-db47-11eb-89b9-290e0c7049a2.png)

**Comment by BoQsc** [comment]
I'm not sure why I've got disconnected. But customizing this message would still be fun.

**Comment by ObsComp** [comment]
A lot of that has to do with LiteNetLib which is technically a third party operating in conjunction with the game. I have not dont much with it before but I can experiment and let you know

**Comment by BoQsc** [comment]
> A lot of that has to do with LiteNetLib which is technically a third party operating in conjunction with the game. I have not done much with it before but I can experiment and let you know

At this moment I'm not sure if it is worth yours or anyone's time. 

I'm not sure If I had any more Network Timeouts.

The Network Timeout seems to appear while there is a constant struggle due to lack of performance on the client-side.

I think I resolved it by having around more RAM memory on the client-side computer.

Therefore I conclude that there is probably no need for Network Timeout configuration on the Server-Side.   

As it (the Network Timeout) more or less works well and it's more of the client-side problem 
of not having proper internet connection or lacking resources to sustain the gameplay.

**Comment by RoTheHated** [comment]
@BoQsc 
So Basically you mindset is is to say hump the poor people? A simple feature to allow gamers that can't yet afford more ram or stronger machines in general don't pay enough of your salary to care about. Nice #Fthepoor I guess

**Comment by ObsComp** [comment]
Not sure who you think is getting paid for any of this Ro. We are not developers for the game. Nobody pays us a salary. That would be great if we were paid monthly at least. ServerTools is a third party program to try and implement some automation and tools for admins to run their server. It is coded by poor people like myself. It is given out for free. 

Network configuration has a lot to do with player-server sync and netcode. Both of which I have no skills or experience coding. A network timeout is normally triggered by someone losing the sync with EAC verification or the client failing to transfer data to the server.

EAC is known to go down or have issues from time to time. Steam itself can also have issues. The newest issue is EOS id through Epic. Combining the three makes for some funky results.

This is not a rich vs poor scenario. Please dont try to make it one.

**Comment by 1265578519** [comment]
服务器只有4G可用内存，内存不足导致的，客户端会发生网络超时。不知道有没有方法设置超时时间？出现这个原因是系统正在使用“优化内存”，把不活跃的内存迁移到pagefile.sys，此时会卡住0.5s-1s左右，然后七日杀就所有玩家掉线了，有没有设置修改超时时间？或者检测到正在使用虚拟内存迁移时不让所有玩家掉线？总不可能让升级服务器内存吧，这会带来更多的服务器价格成本，l4d2他就能在200MB的内存下运行服务端
