### ISSUE TITLE
Add ability to customize server world name  

### ISSUE THREAD

**Issue by BoQsc** [dmustanger/7dtd-ServerTools#317]
Randomly generated worlds RWG seems to have issue with **GameWorld** property in the serverconfig.xml   
So it would be handy to customize server's world name without changing the name of the server's world.  

https://user-images.githubusercontent.com/21064622/125157992-bd1b3700-e176-11eb-8289-183fdac4c1be.mp4

![image](https://user-images.githubusercontent.com/21064622/125157574-847a5e00-e174-11eb-8697-a315f531e3bd.png)
![image](https://user-images.githubusercontent.com/21064622/125157577-88a67b80-e174-11eb-8505-fc5637797d03.png)

**Comment by ObsComp** [comment]
I am not sure I fully understand the request. You want to change the world name without changing the server's world name in the serverconfig.xml . You want it to show different in the browser then?

**Comment by BoQsc** [comment]
> I am not sure I fully understand the request. You want to change the world name without changing the server's world name in the serverconfig.xml . You want it to show different in the browser then and only the browser, not the actual world name used to generate it.

That's exactly what is my proposal.
If it is possible to implement relatively easily.

**Comment by ObsComp** [comment]
For ease of use and confusion over world save data, I am going to pass on adding this as a feature at this time
