### ISSUE TITLE
Pve "explosion" protection does not work well ServerTools 19.5.3

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#319]
pve "explosion" protection does not work well ServerTools 19.5.3

I was testing with a friend and within the protection pve you can continue to kill with all explosives, It only works if one is outside the protection radius and the other inside.

**Comment by ObsComp** [comment]
PvE protection within a zone was changed to use modes 0 - 3. Which one is it set to?

**Comment by LPMZ** [comment]
It is at 0 No Killing, I tried all the modes. Now he doesn't expel the player, that's excellent because it was very annoying. I understand that this system must be very complicated in a game like this. congratulations for this update every time much better!

**Comment by ObsComp** [comment]
I have this on the top of my list now for tests. Have not forgot about it

**Comment by ObsComp** [comment]
It is fixed in the upcoming release 19.6.2
