### ISSUE TITLE
Server Tools protect (Bug Black screen)

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#322]
Hello, I remember to see a server administrator in which he had an anti-bug protection that prevents seeing through the ground (When seeing through the ground the screen goes black). He told me that "servertools" would implement this in the future. I wanted to know if it is true because this would avoid a lot of headaches with players who use this bug to their advantage, especially on pvp servers. Thanks a lot.

**Comment by ObsComp** [comment]
Yes that is a planned feature. The project is handled by another coder from our team. I have yet to merge in his work but intend to very soon. We are looking at ways to improve the response and processing time of it but if we can not, it will be merged in as is.

**Comment by Demon-MC** [comment]
good afternoon, have you added this tool to servertools? is there any other way to implement this now?

**Comment by Demon-MC** [comment]
here's how it is implemented on someone else's server [https://disk.yandex.ru/i/MUX0GEKpa3r6Sg](url)

**Comment by ObsComp** [comment]
XRay detection has been added in version 19.6.6
