### ISSUE TITLE
CommandList.xml

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#324]
CommandList.xml can't not to change! im dell all old version! and try again but nothong change. work for ver 19.4.0

**Comment by LPMZ** [comment]
Version 19.4.0 uses EventTriggers.xml not CommandList.xml

**Comment by batboyboy1990** [comment]
> CommandList.xml

CommandList.xml im; try edit CommandList.xml but can;t not work, im downgrade to 15.0 now home cant not save!

**Comment by ObsComp** [comment]
Please update to the latest 19.6.1. The latest version will auto update your xml files to their current version and try to keep your settings. If any are lost, manually enter them in to the new xml by using the xml backups that are auto generated during updates.

I have tested the Command List in 19.6.1 and it worked without issue. Let us know if you still have issues tho
