### ISSUE TITLE
Dedicated Server (FPS Per Second) 

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#333]
Hi, I've been wondering for a long time why the dedicated server doesn't show fps per second. Is it possible that servertools can implement this? It would be very helpful for people who want to configure their server in performance like (Max Zombie, Max Players, Map, Amount of prefabs!). With this tool you could know the exact performance of the host!

**Comment by ObsComp** [comment]
Technically the FPS tool does allow this and so does the Day7 tool. When the server reports the 'fps' it is really reporting the cpu cycle count remaining before it starts to lag and run out of over head. This is why when players first join it will read something like 50 fps or more but as soon as you have more than 20 players it is normally down to 30 fps or less which is really the cpu processing potential available

**Comment by ObsComp** [comment]
Steam has its own built in fps counter. While in game go to the steam overlay. At the bottom is a setting button. Click that and look for a section that says fps counter. You can tell it which corner you want it to display in
