### ISSUE TITLE
ProtectedSpaces "off", "remove", and "active" not working

### ISSUE THREAD

**Issue by mixels** [dmustanger/7dtd-ServerTools#336]
I protected a space using st-ps add in console. The protection works fine. The problem I have now is that I can't unprotect it. I tried the following:

`st-ps off`
`st-ps active 1`
`st-ps remove 1`

None of these resulted in me being able to modify the protected space.

**Comment by mixels** [comment]
Won't resetting the region remove the structure completely?

**Comment by ObsComp** [comment]
This has been fully redone and should no longer have issues getting stuck in 19.6.6 onwards. It allows dynamic changes whether in game or offline
