### ISSUE TITLE
New_Player_Protection no work. last version!

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#337]
This is a good idea but it is not working. not even adjusting the protection level. Sometimes the new player can kill a higher level player, the high level player cannot kill him: S. It would be a re cheater! haha

**Comment by ObsComp** [comment]
Uh oh. I will fix this. Thank you for the report

**Comment by LPMZ** [comment]
I tried it just in version "19.6.3", the error is equal to PVE zones mode. The lower level player without exceeding the configured level is left with the ghost body when attacked but can be beaten and killed with hands when the death animation remains, similar to the video uploaded on YouTube !. Ah, you can also kill him with a Molotov.

**Comment by ObsComp** [comment]
If you are aiming for a PvE server with a PvP arena or designated area, you will have to set it to PvP. Make a zone that covers the entire map and set PvPvE = "0"
Then where you want some PvP spaces, add zones for them but make sure they come before the big PvE one in the list. If two zones overlap, the first one on the list will apply.

If you find it to be lagging with a specific set of zones, send me your Zones.xml and I will run some tests to see what may be causing the lag or improve the tool if complicated zones overload the process
________________________________
