### ISSUE TITLE
how to change coin balance?

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#34]
I just updated and turned on market/coin feature and it already shows a balance for myself and others. Not sure why it shows a balance or where this coin balance came from and would like to zero it out.

**Comment by markrjackson** [comment]
Ok, so now I understand why there is already a coin balance. I dug into your code and see where the coin balance is coming from and how it is calculated but I would like to request a console command for admins to be able to set the balance or make adjustments (or even give additional coins to players, etc). Also it would be nice if the hard-coded values used in the calculation could be set in the config like coins per zombie, etc.

**Comment by ObsComp** [comment]
You got it. This was the first version to get it started. I will be adding config options so you can set the values such as what a zombie/player kill gives you and how much a death subtracts. Also some console commands to add or subtract from a player's wallet.

**Comment by markrjackson** [comment]
Very nice! Love all the new features and fixes.

**Comment by ObsComp** [comment]
You can change the base values of the wallet calculations and add coins or subtract them through the console now :P
