### ISSUE TITLE
Zone doesn´t work 

### ISSUE THREAD

**Issue by RoXNaRT** [dmustanger/7dtd-ServerTools#340]
I can't add zones and there are also no console errors. Is there something wrong?  (It is active from "ServerToolsConfig")

> <?xml version="1.0" encoding="UTF-8"?>
<Zones>
<ST Version="19.6.5" />

    <Zone Name="Trader" Corner1="-481,51,29" Corner2="-487,60,46" Circle="True" EntryMessage="Testing" ExitMessage="TestingX" EntryCommand="" ExitCommand="" ReminderNotice="" PvPvE="0" NoZombie="True" />
</Zones>

`

**Comment by LPMZ** [comment]
if that happens in version! Server tools 19.6.4. Something similar happens to me as the auto bloomoon message, or auto message of the time of my country. it was running every 20 seconds !. 19.6.4 is corrupt !. try the latest version !. If ObsComp fails, you will be aware!

**Comment by breeece** [comment]
> > Did you try putting where it says "Circle =" True "in false? What version do you use? Also try putting it like this.
> > Corner1 ="-481,0,29" Corner2 ="-487,500,46"
> 
> With this I am now able to configure the zone.
> 
> Btw, I'm getting a nonstop of "ExitMessage" which causes that if I move away from the area I can continue with the benefit of this

I am getting constant Exitmessage.

**Comment by LPMZ** [comment]
> 
> 
> > > Did you try putting where it says "Circle =" True "in false? What version do you use? Also try putting it like this.
> > > Corner1 ="-481,0,29" Corner2 ="-487,500,46"
> > 
> > 
> > With this I am now able to configure the zone.
> > Btw, I'm getting a nonstop of "ExitMessage" which causes that if I move away from the area I can continue with the benefit of this
> 
> I am getting constant Exitmessage.

what version do you use?

**Comment by ObsComp** [comment]
Version 19.6.6 fixed the Zone exit spam. Circles might not be working. I have not used it in a long time honestly. I will mark it down for retest. Thanks

**Comment by Rival819** [comment]
You need to use "Y" has height, think of a 3D box, your first corner should be at y=0 and your second corner at like y=500 so it his high enough. It works great, and also all first layers will be primary, so if you create an arena and make it a pvp zone, then create a pve zone OVER it to make sure people dont get killed when getting out it will work great and turn into a pvp area when you get inside your arena, but not the other way around, if you made the pve zone then create and arena over it, the pve zone will be primary so not detecting the other pvp zone, so the one before  it his always primary.
