### ISSUE TITLE
CustomCommands with Parameters

### ISSUE THREAD

**Issue by OmitLeChuck** [dmustanger/7dtd-ServerTools#341]
Currently, only static commands are possible in the CustomCommands.
But it would be super cool if parameters could be used as well.

These could then be displayed according to the usual pattern `{1} {2} {3}`. Parsed space separated.

**Example:**
Chat:
`/goto player`

XML:
`<Custom Trigger="goto" Command="tele {EntityId} {1} ^ whisper You are now at player {1}." DelayBetweenUses="15" Hidden="false" Permission="false" Cost="0"/>`

**Comment by abckill101** [comment]
help me how to warp <Custom Trigger="nort" Command="teleport {EntityId} {1} 300 200" DelayBetweenUses="0" Hidden="false" Permission="false" Cost="0" />

**Comment by OmitLeChuck** [comment]
> help me how to teleport
> 
> Custom Trigger="nort" Command="teleport {EntityId} {1} 300 200" DelayBetweenUses="0" Hidden="false" Permission="false" Cost="0"

hi @abckill101 ,

is that what you wrote a question?
The command `teleport` give the following options when you type `help tele` in the console of the server:
```*** Command: tele ***
Usage:
  1. teleportplayer <steam id / player name / entity id> <x> <y> <z> [view direction]
  2. teleportplayer <steam id / player name / entity id> <target steam id / player name / entity id>
1. Teleports the player given by his SteamID, player name or entity id (as given by e.g. "lpi")
   to the specified location. Use y = -1 to spawn on ground. Optional argument view direction
   allows you to speify a direction you want to look in after teleporting. This can be either
   of n, ne, e, se, s, sw, w, nw or north, northeast, etc.
2. As 1, but destination given by another (online) player
```

That means to me that my suggested command `/goto playername` will end up in `tele currentplayer playername` and teleport the current player (who types the command in the chat) to the player with the given `playername`.
This could also work with entityid or steamid, but normally you have only the name of the player you want to teleport to when you are ingame.

This example is of course a custom commands that should only be available for admins i guess ;)

**Comment by ObsComp** [comment]
The teleport commands placed in custom commands were not working when I tried them out and I am not sure why. They worked without issue before. I will have to test it and see. I tweaked it a bit in 19.6.6 so give that version a try
