### ISSUE TITLE
ChatColor not working (maybe)

### ISSUE THREAD

**Issue by OmitLeChuck** [dmustanger/7dtd-ServerTools#342]
Some of our players of course want to have their own color in the chat, and so I thought that ChatColor.xml would be just right.
However, it does not work, or I do something wrong.

Here is my entry for one player:
`<Player SteamID="THERIGHTSTEAMID" Name="THERIGHTSTEAMNAME" Group="Admin" Prefix="" NameColor="FF00FF" PrefixColor="FF00FF" Expires=""/>`

Everything is always white. Any ideas?

I'am using `<ST Version="19.6.3"/>`

**Comment by LPMZ** [comment]
Look for the player id. Use the command "lp" when the player is connected and write down the steam id.

An example

<Player SteamId="12345678901234567" Name="bob" Group="user1" Prefix="" NameColor="[FF0000]" PrefixColor="[FFFFFF]" Expires="10/29/2050 7:30:00 AM" />

**Comment by OmitLeChuck** [comment]
OK. I will try that, but i am quite sure about the SteamIDs i configured.

Maybe the missing ` [ ] ` is the problem.
Is `Expires` and `PrefixColor` mandatory, or could they be left empty?

**Comment by ObsComp** [comment]
Were you able to sort this out or do you need some more help?
