### ISSUE TITLE
Xray V.19.6.8

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#346]
This usually happens in the previous and last version. Testing if I crouch works but if I stay standing it does not. 

Example:
https://youtu.be/tNMfw5KwZbw

**Comment by LPMZ** [comment]
I just tested again. It works fine, it was my mistake, I needed to restart the server and remove the admin for it to work well !. :)
Now only the pve zone system is missing and you would make me happy! hehehehe

**Comment by ObsComp** [comment]
XRay is going to get a full redo along with some of the other anti cheat. PVP is not played as much as originally thought so focus on anti cheat has been minimal but it is marked down for rework. Sorry it took so long to respond. Clearing up posts
