### ISSUE TITLE
help me how to seting stub by stub Shop.xml

### ISSUE THREAD

**Issue by abckill101** [dmustanger/7dtd-ServerTools#347]
?xml version="1.0" encoding="UTF-8"?

Shop
ST Version="19.6.8" /
    !-- Secondary name is what will show in chat instead of the item name --
    !-- WalletCoin can be used as the item name. Secondary name should be set to your Wallet Coin_Name option --
  
/Shop

**Comment by ObsComp** [comment]
You can set any items you want from your items.xml found in the default xml to the game server. I will add an example to this at the top to make it easier in the future.

Here is an example entry.

<Item Name=\"drinkBoiledWater\" SecondaryName=\"Boiled Water\" Count=\"10\" Quality=\"1\" Price=\"100\" Category=\"Food\" />
