### ISSUE TITLE
A20

### ISSUE THREAD

**Issue by OmitLeChuck** [dmustanger/7dtd-ServerTools#349]
Hello all,

You are probably already in the process of hammering away at the keys regarding the A20 version.
But I just wanted to ask carefully when you will have an A20 capable version ready.

Still in December, or rather in the new year only?

**Comment by LPMZ** [comment]
uuh yes !, without server tools in alpha 20 it would be my downfall! :(

**Comment by ObsComp** [comment]
My cat was quite sick so things got backed up and very behind but yes a a20 version is out and now a patch for it bringing it to version 20.0.1
