### ISSUE TITLE
Claim

### ISSUE THREAD

**Issue by sLimLong** [dmustanger/7dtd-ServerTools#35]
Works well for Linux 4.4 Ubuntu 16.04.

Is it possible to make a team of admins who can without an obstacle delete the claim of other players

**Comment by ObsComp** [comment]
I am not sure what you mean by prizes. Can I have some more information?

**Comment by sLimLong** [comment]
sorry,fixed, text.

**Comment by ObsComp** [comment]
Oh I understand what you are saying. Ummm, yes actually, I could make that.
