### ISSUE TITLE
Shutdown function not working correct

### ISSUE THREAD

**Issue by Thodde26** [dmustanger/7dtd-ServerTools#351]
I have the shutdown function on false and the server still make shutdown after 2 minuts . I turn it on and set a value there he always goes down after 2 minutes. can someone post me the line times set correctly with every 6 hours restart? 

sorry for my english 
thank you 
Merry christmas and a happy new year 
Thodde26

**Comment by LPMZ** [comment]
to have 6 hours you have to put 360. The shutdown works for minutes.

**Comment by Thodde26** [comment]
Ok.         
<Tool Name="Shutdown" Enable="True" Countdown="10" Time="360" Alert_On_Login="True" Alert_Count="60" />
<Tool Name="Shutdown_Extended" UI_Lock="True" />

i will Test it

**Comment by LPMZ** [comment]
> 

Countdown is the last minutes you give the server to shut down, I always leave it 5. Example: when 6 hours have passed, the autochat starts, it will say that the server shuts down in 5 minutes.

**Comment by ObsComp** [comment]
Version 20.0.1 has a fix for that added in and has just been released. Thank you for the report
