### ISSUE TITLE
ServerTools 20.0.0 Falling_Blocks is crashing the server.

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#352]
Falling_Blocks is crashing the server. I activated it and in the logs I jump to falling_block that wanted to delete something and the server died. I have it deactivated and it does not crash anymore!

**Comment by ObsComp** [comment]
Hmm, okay, I will check it out, thank you

**Comment by LPMZ** [comment]
hello, is it possible to remove it completely ?, the entire server closed without saying any crash but when I see the logs it said this.
"2022-01-04T23: 38: 07 6305.043 INF [SERVERTOOLS] Entity cleanup: Removed falling block id 221858"
 I don't understand why it continues to work, I have it false, now directly disable the main parameter: 
"<Tool Name =" Entity_Cleanup " Enable = "False" 
I keep testing.

**Comment by ObsComp** [comment]
I am going to redo that tool for next release

________________________________

**Comment by LPMZ** [comment]
okay! "Entity_Underground" is similar to zones.xml NoZombie = "True"? The zones.xml tool was using it to delete zombies in a zone. It is also damaging and closing the server without saying any error. I already deactivate everything related to that and the server is working 3 days ago to perfection. thank you.

**Comment by LPMZ** [comment]
Well my server is working fine I also had to remove the <Tool Name = "FPS" Enable = "False" Set_Target = "60" Low_FPS = "30" /> parameter. It is seen that it has the same operation as Entity_Cleanup. When I had it activated it kept closing the server for no reason.
