### ISSUE TITLE
Unjail not working 20.0.1

### ISSUE THREAD

**Issue by krazybeat** [dmustanger/7dtd-ServerTools#355]
when I send a player to jail, and then try to remove him from jail with unjail, it doesn't work.

**Comment by ObsComp** [comment]
This has been reported to me again recently. I have added it back to the test schedule and will get it cleared up this week if the problem persists

**Comment by ObsComp** [comment]
This is confirmed to work while they are online but it was not while offline. They would come back online to find themselves in the same jail space. I have added something to teleport them out of the jail position when they come back online at a later time in 20.3.3
