### ISSUE TITLE
Public Waypoints Not working

### ISSUE THREAD

**Issue by Rival819** [dmustanger/7dtd-ServerTools#356]
Hi, I have noticed that the public waypoints wont work in A20 even when setup properly in the XML and activated in waypoints_extended and also in public_waypoints. When typing /way I can see all my public waypoints listed but cannot teleport to them, servertools just wont answer if you have no waypoint of your own, and will say that they are none in the list if you have some waypoints setup for yourself. There his also no command at all in the CommandList.xml for public teleport, also infos are totally absent inside the "HowToSetup.txt" file under "Waypoint_Extended" and "Public_Waypoints". I also noticed that the Lobby command has no checkup for vehicle teleport so people can teleport to your lobby while inside their vehicles jamming them in walls where you need to break walls to unstuck them, basically the only workaround is setting your /lobby outside of the lobby or using a public /way lobby since the vehicles=true works well with normal waypoints. But public waypoint dont work anyway so forced to setup /lobby outside. Thanks for your time and thank you for this mod.

EDIT: I also tried using /way or /waypoint and the name of the public waypoint and even if I can see them in the list they wont work.

<a href="https://freeimage.host/i/YIEXRe"><img src="https://iili.io/YIEXRe.th.png" alt="YIEXRe.th.png" border="0"></a>

**Comment by Rival819** [comment]
I am not the best in programming, but I have been wondering, his this normal ?
I cannot see Public_Waypoints and PVE_Violations inside the DLL ? Shouldn't this be there ? All other ones seems to be inside there. Again, I dont know much in C# yet, but seems like they both missing ? 

<a href="https://freeimage.host/i/YIXdy7"><img src="https://iili.io/YIXdy7.th.png" alt="YIXdy7.th.png" border="0"></a>

**Comment by ObsComp** [comment]
I did not add a console command for the public waypoints tool yet. Thank you for reminding me. It does exist in the code. It is in the ..Tools/Waypoints/Waypoints.cs
I will write down to test it out again for next release

**Comment by Rival819** [comment]
Oh Cool! Okay thanks for very fast reply ! :)

**Comment by ObsComp** [comment]
This tool is working in the latest tests. Closing this topic
