### ISSUE TITLE
Steam ID not found

### ISSUE THREAD

**Issue by FastCDr** [dmustanger/7dtd-ServerTools#358]
Im executing command st-GiveItem 76561198065917102 ammo44MagnumBulletAP 1 1
76561198065917102  - This is my real steamid
In response, I get: [SteamID not found](https://fastcd.ru/img/steamid-not-found.png)

**Comment by ObsComp** [comment]
You must use the new format the pimps have introduced. Steam_76561198065917102 or the EOS_id. Alternatively you can use the entity id or your name while online

**Comment by FastCDr** [comment]
Hello! I tried to execute the command in this way: st-GiveItem Steam_76561198065917102 ammo44MagnumBulletAP 1 1, but the result is the same - SteamID not found.
Works only through the player's nickname :(

**Comment by FastCDr** [comment]
And EOS_id
[SERVERTOOLS] Can not give item: Invalid id EOS_00026921701a415f871e35c991f2e5b3

**Comment by ObsComp** [comment]
Alright I will add it to the test schedule. Thanks

________________________________
