### ISSUE TITLE
request: add quantity to /buy command

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#36]
Request to add quantity to /buy command like this:

`/buy <item#> <qty>`

Quantity can be optional and default to 1.

**Comment by ObsComp** [comment]
ah yes, good idea.
This was the first version of the shop so that is a great feature to add now that it is running.
Thank you.

**Comment by ObsComp** [comment]
10.7 has added this. Thanks for the idea
