### ISSUE TITLE
does not work Dropped_Bag_Protection 

### ISSUE THREAD

**Issue by egik152** [dmustanger/7dtd-ServerTools#364]
does not work  Dropped_Bag_Protection. I'm trying to run this function on my server. The server has a PvP mode. Are there conditions for this function to work?

**Comment by batboyboy1990** [comment]
metoo

**Comment by ObsComp** [comment]
It is working in tests. Admin have access to all bags so if you are testing the tool as an admin, that is why it seems to not work. Once a bag is accessed by the owner, it is accessible to all. If friends option is enabled, their friends can access the dropped bag and will also make it available to all if they access it
