### ISSUE TITLE
Ping simulation.

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#365]
Hello, I wanted to ask you if you can make a ping simulation parameter. Is it possible? Because as my host is home and I have 0 ping, people realize that I am an admin and I would like to avoid that. I remember that another server manager had it but it did not work. Thanks a lot.

**Comment by ObsComp** [comment]
Oh you mean a fake ping. That might be possible. Not something typically done though. Are you sure you want that?
