### ISSUE TITLE
Bloodmoon Warrior crash.

### ISSUE THREAD

**Issue by LPMZ** [dmustanger/7dtd-ServerTools#367]
Hello, When the horde ends and several players who survived, blood moon warrior usually crashes the server when he wants to give the items to the players. This is similar when he reported the "Gimme" command that crashed in alpha 19. 

Logs:
`2022-01-13T00:02:38 10271.935 INF Entity zombieNurse 326888 killed by BATU 325979
2022-01-13T00:02:40 10274.011 INF Entity zombieFatHawaiianPodrido 326864 killed by Evim 307849
2022-01-13T00:02:41 10274.456 INF 10236.5 SleeperVolume -1826, 38, -772: Spawning -1825, 39, -768 (-115, -48), group 'zombieBusinessManGroupGS1', class zombieBusinessMan, count 63
2022-01-13T00:02:41 10274.465 INF 10236.5 SleeperVolume -1827, 42, -787: Spawning -1825, 42, -781 (-115, -49), group 'sleeperHordeStageGS2', class zombieSteve, count 63
2022-01-13T00:02:41 10274.504 INF 10236.55 SleeperVolume -1833, 42, -786: Spawning -1830, 42, -786 (-115, -50), group 'sleeperHordeStageGS2', class zombieDarlene, count 63
2022-01-13T00:02:41 10274.514 INF 10236.55 SleeperVolume 23, 90, 1387: Spawning 39, 90, 1389 (2, 86), group 'zombieBusinessManGroupGS50', class zombieBusinessManFeral, count 63
2022-01-13T00:02:41 10274.567 INF 10236.62 SleeperVolume -1827, 42, -787: Spawning -1824, 42, -781 (-114, -49), group 'sleeperHordeStageGS2', class zombieNurse, count 63
2022-01-13T00:02:41 10274.795 INF 10236.66 SleeperVolume -1833, 42, -786: Spawning -1830, 42, -785 (-115, -50), group 'sleeperHordeStageGS2', class zombieNurse, count 63
2022-01-13T00:02:41 10274.804 INF 10236.66 SleeperVolume 23, 90, 1387: Spawning 31, 90, 1394 (1, 87), group 'zombieBusinessManGroupGS50', class Zgore, count 63
2022-01-13T00:02:41 10274.908 INF 10236.97 SleeperVolume 23, 90, 1387: Spawning 34, 90, 1389 (2, 86), group 'zombieBusinessManGroupGS50', class zombieBusinessMan, count 63
2022-01-13T00:02:41 10275.023 INF 10237.08 SleeperVolume 23, 90, 1387: Spawning 24, 90, 1395 (1, 87), group 'zombieBusinessManGroupGS50', class zombieBusinessMan, count 63
2022-01-13T00:02:43 10276.773 INF Entity zombieJoePodrido 326697 killed by KOTEX 8530
2022-01-13T00:02:47 10280.405 INF 356857 EntityBackpack id 326840, plyrId 170089, (-1736.4, 50.4, 2277.2) (-109, 142), chunk True (-109, 3, 142), items 9 frameShapes:VariantHelper, meleeWpnBladeT1HuntingKnife at (0, 0, 0, xz 0 0) : Write
Crash!!!
SymInit: Symbol-SearchPath: '.;C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20;C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 534, UserName: 'Frank'
OS-Version: 10.0.0
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\7DaysToDieServer.exe:7DaysToDieServer.exe (00007FF6226F0000), size: 675840 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.14.53691
C:\Windows\SYSTEM32\ntdll.dll:ntdll.dll (00007FFD69FB0000), size: 2052096 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\KERNEL32.DLL:KERNEL32.DLL (00007FFD68B90000), size: 774144 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\KERNELBASE.dll:KERNELBASE.dll (00007FFD677C0000), size: 2916352 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\UnityPlayer.dll:UnityPlayer.dll (00007FFD3EFB0000), size: 29044736 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2020.3.14.53691
C:\Windows\System32\USER32.dll:USER32.dll (00007FFD69510000), size: 1703936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\win32u.dll:win32u.dll (00007FFD67730000), size: 139264 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\GDI32.dll:GDI32.dll (00007FFD69F80000), size: 172032 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\gdi32full.dll:gdi32full.dll (00007FFD67CC0000), size: 1093632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\msvcp_win.dll:msvcp_win.dll (00007FFD67DD0000), size: 643072 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\System32\ucrtbase.dll:ucrtbase.dll (00007FFD67B10000), size: 1048576 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\System32\ole32.dll:ole32.dll (00007FFD68240000), size: 1220608 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\RPCRT4.dll:RPCRT4.dll (00007FFD69B30000), size: 1224704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\SYSTEM32\VERSION.dll:VERSION.dll (00007FFD5FC60000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\combase.dll:combase.dll (00007FFD68470000), size: 3493888 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\msvcrt.dll:msvcrt.dll (00007FFD69EE0000), size: 647168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 7.0.19041.546
C:\Windows\System32\SHLWAPI.dll:SHLWAPI.dll (00007FFD69430000), size: 348160 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\SETUPAPI.dll:SETUPAPI.dll (00007FFD696C0000), size: 4624384 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\System32\cfgmgr32.dll:cfgmgr32.dll (00007FFD67A90000), size: 319488 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\bcrypt.dll:bcrypt.dll (00007FFD67AE0000), size: 159744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.662
C:\Windows\System32\ADVAPI32.dll:ADVAPI32.dll (00007FFD69E10000), size: 704512 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.610
C:\Windows\System32\sechost.dll:sechost.dll (00007FFD683D0000), size: 634880 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\SHELL32.dll:SHELL32.dll (00007FFD68CB0000), size: 7610368 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\OLEAUT32.dll:OLEAUT32.dll (00007FFD69D40000), size: 839680 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.804
C:\Windows\System32\IMM32.dll:IMM32.dll (00007FFD69400000), size: 196608 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\WINMM.dll:WINMM.dll (00007FFD5F7C0000), size: 159744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FFD50A70000), size: 1204224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\CRYPT32.dll:CRYPT32.dll (00007FFD67E70000), size: 1437696 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\System32\WS2_32.dll:WS2_32.dll (00007FFD694A0000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FFD5A9C0000), size: 1093632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\HID.DLL:HID.DLL (00007FFD66030000), size: 53248 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\GLU32.dll:GLU32.dll (00007FFD586B0000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\SYSTEM32\kernel.appcore.dll:kernel.appcore.dll (00007FFD65690000), size: 73728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FFD67FD0000), size: 524288 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.662
C:\Windows\system32\uxtheme.dll:uxtheme.dll (00007FFD651E0000), size: 647168 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\shcore.dll:shcore.dll (00007FFD68110000), size: 712704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll:mono-2.0-bdwgc.dll (00007FFD3E840000), size: 7790592 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\System32\PSAPI.DLL:PSAPI.DLL (00007FFD68050000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\windows.storage.dll:windows.storage.dll (00007FFD65890000), size: 7933952 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\Wldp.dll:Wldp.dll (00007FFD671A0000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.662
C:\Windows\SYSTEM32\profapi.dll:profapi.dll (00007FFD67670000), size: 126976 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\SYSTEM32\iphlpapi.dll:iphlpapi.dll (00007FFD66BB0000), size: 241664 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\MSCTF.dll:MSCTF.dll (00007FFD68830000), size: 1134592 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\System32\clbcatq.dll:clbcatq.dll (00007FFD68060000), size: 692224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2001.12.10941.16384
C:\Windows\System32\MMDevApi.dll:MMDevApi.dll (00007FFD5F730000), size: 544768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\System32\DEVOBJ.dll:DEVOBJ.dll (00007FFD674E0000), size: 180224 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\AUDIOSES.DLL:AUDIOSES.DLL (00007FFD546C0000), size: 1576960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\powrprof.dll:powrprof.dll (00007FFD66CD0000), size: 307200 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\UMPDC.dll:UMPDC.dll (00007FFD66B90000), size: 73728 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\resourcepolicyclient.dll:resourcepolicyclient.dll (00007FFD652A0000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\CRYPTSP.dll:CRYPTSP.dll (00007FFD670E0000), size: 98304 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\rsaenh.dll:rsaenh.dll (00007FFD66840000), size: 212992 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (00007FFD67100000), size: 49152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\7DaysToDieServer_Data\Plugins\x86_64\EOSSDK-Win64-Shipping.dll:EOSSDK-Win64-Shipping.dll (00007FFD3CB60000), size: 23248896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 1.14.1.0
C:\Windows\System32\WLDAP32.dll:WLDAP32.dll (00007FFD68370000), size: 352256 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\Normaliz.dll:Normaliz.dll (00007FFD69490000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\WINTRUST.dll:WINTRUST.dll (00007FFD67760000), size: 393216 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.804
C:\Windows\SYSTEM32\Secur32.dll:Secur32.dll (00007FFD51090000), size: 49152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\VCRUNTIME140.dll:VCRUNTIME140.dll (00007FFD58CE0000), size: 106496 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.29.29917.0
C:\Windows\SYSTEM32\MSVCP140.dll:MSVCP140.dll (00007FFD58620000), size: 577536 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.29.29917.0
C:\Windows\SYSTEM32\VCRUNTIME140_1.dll:VCRUNTIME140_1.dll (00007FFD64D40000), size: 49152 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 14.29.29917.0
C:\Windows\SYSTEM32\SSPICLI.DLL:SSPICLI.DLL (00007FFD675F0000), size: 200704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\MSASN1.dll:MSASN1.dll (00007FFD67320000), size: 73728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\NSI.dll:NSI.dll (00007FFD696B0000), size: 32768 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.610
C:\Windows\SYSTEM32\dhcpcsvc6.DLL:dhcpcsvc6.DLL (00007FFD61080000), size: 94208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\dhcpcsvc.DLL:dhcpcsvc.DLL (00007FFD611B0000), size: 118784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\mswsock.dll:mswsock.dll (00007FFD66F10000), size: 434176 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\napinsp.dll:napinsp.dll (00007FFD58600000), size: 94208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\pnrpnsp.dll:pnrpnsp.dll (00007FFD585E0000), size: 110592 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\wshbth.dll:wshbth.dll (00007FFD53550000), size: 86016 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\system32\NLAapi.dll:NLAapi.dll (00007FFD63210000), size: 118784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\SYSTEM32\DNSAPI.dll:DNSAPI.dll (00007FFD66C00000), size: 835584 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\System32\winrnr.dll:winrnr.dll (00007FFD58460000), size: 73728 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.19041.928_none_faefac437613c6cc\gdiplus.DLL:gdiplus.DLL (00007FFD510A0000), size: 1748992 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\SYSTEM32\DWrite.dll:DWrite.dll (00007FFD5BBC0000), size: 2617344 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.804
C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.844_none_ca00b6081b84eb1d\comctl32.dll:comctl32.dll (00007FFD53570000), size: 2727936 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 6.10.19041.844
C:\Windows\SYSTEM32\textinputframework.dll:textinputframework.dll (00007FFD5D730000), size: 1019904 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\CoreUIComponents.dll:CoreUIComponents.dll (00007FFD649A0000), size: 3530752 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\CoreMessaging.dll:CoreMessaging.dll (00007FFD64DE0000), size: 991232 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\SYSTEM32\ntmarta.dll:ntmarta.dll (00007FFD66470000), size: 208896 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\wintypes.dll:wintypes.dll (00007FFD63640000), size: 1392640 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\SYSTEM32\TextShaping.dll:TextShaping.dll (00007FFD5B120000), size: 704512 (result: 0), SymType: '-deferred-', PDB: ''
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\7DaysToDieServer_Data\Plugins\x86_64\steam_api64.dll:steam_api64.dll (0000000075030000), size: 266240 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.4.91.85
C:\Windows\system32\wbem\wbemprox.dll:wbemprox.dll (00007FFD57C90000), size: 69632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FFD58D00000), size: 606208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FFD57470000), size: 81920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\system32\wbem\fastprox.dll:fastprox.dll (00007FFD57CB0000), size: 1093632 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\amsi.dll:amsi.dll (00007FFD57B80000), size: 102400 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.746
C:\Windows\System32\rasadhlp.dll:rasadhlp.dll (00007FFD59BC0000), size: 40960 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\System32\fwpuclnt.dll:fwpuclnt.dll (00007FFD5A210000), size: 520192 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\7DaysToDieServer_Data\Plugins\x86_64\eac_server.dll:eac_server.dll (00007FFD3C9F0000), size: 1454080 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 2.0.0.0
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\steamclient64.dll:steamclient64.dll (0000000074260000), size: 14430208 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.21.37.56
C:\Windows\System32\imagehlp.dll:imagehlp.dll (00007FFD69EC0000), size: 118784 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\vstdlib_s64.dll:vstdlib_s64.dll (0000000073E70000), size: 438272 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.21.37.56
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\tier0_s64.dll:tier0_s64.dll (0000000073EE0000), size: 3612672 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 4.21.37.56
C:\Windows\SYSTEM32\Wlanapi.dll:Wlanapi.dll (00007FFD60F30000), size: 434176 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.928
C:\Windows\system32\schannel.DLL:schannel.DLL (00007FFD66760000), size: 593920 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.789
C:\Windows\SYSTEM32\mskeyprotect.dll:mskeyprotect.dll (00007FFD59D70000), size: 86016 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.662
C:\Windows\SYSTEM32\NTASN1.dll:NTASN1.dll (00007FFD671D0000), size: 241664 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\ncrypt.dll:ncrypt.dll (00007FFD67210000), size: 159744 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.662
C:\Windows\system32\ncryptsslp.dll:ncryptsslp.dll (00007FFD52D10000), size: 155648 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Windows\SYSTEM32\gpapi.dll:gpapi.dll (00007FFD66040000), size: 143360 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.844
C:\Windows\System32\cryptnet.dll:cryptnet.dll (00007FFD5A290000), size: 200704 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.906
C:\Windows\SYSTEM32\WINNSI.DLL:WINNSI.DLL (00007FFD612F0000), size: 45056 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.546
C:\Server 7 Days to Die\7 Days to Die Dedicated Server Alpha 20\7DaysToDieServer_Data\Plugins\x86_64\getrss.dll:getrss.dll (000000006D3C0000), size: 53248 (result: 0), SymType: '-deferred-', PDB: ''
C:\Windows\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FFD614A0000), size: 1982464 (result: 0), SymType: '-deferred-', PDB: '', fileVersion: 10.0.19041.867

========== OUTPUTTING STACK TRACE ==================

0x00007FFD401CBC79 (UnityPlayer) physx::Gu::AABBTreeOverlap<physx::Gu::AABBAABBTest,physx::Sq::IncrementalAABBTree,physx::Sq::IncrementalAABBTreeNode,physx::Sq::PrunerPayload,physx::Sq::PrunerCallback>::operator()
0x00007FFD40244047 (UnityPlayer) physx::Sq::IncrementalAABBPrunerCore::overlap
0x00007FFD40243991 (UnityPlayer) physx::Sq::ExtendedBucketPruner::overlap
0x00007FFD401D5687 (UnityPlayer) physx::Sq::AABBPruner::overlap
0x00007FFD401DA5A3 (UnityPlayer) physx::NpSceneQueries::multiQuery<physx::PxOverlapHit>
0x00007FFD401F0184 (UnityPlayer) physx::NpSceneQueries::overlap
0x00007FFD3F813396 (UnityPlayer) PhysXRaycast::FindParticleIntersections
0x00007FFD3F1A1EF1 (UnityPlayer) WorldCollision
0x00007FFD3F1A11EF (UnityPlayer) CollisionModule::Update
0x00007FFD3F1784C7 (UnityPlayer) ParticleSystem::UpdateModulesIncremental
0x00007FFD3F175B3F (UnityPlayer) ParticleSystem::Update1Incremental
0x00007FFD3F1761D6 (UnityPlayer) ParticleSystem::Update1b
0x00007FFD3F1779D4 (UnityPlayer) ParticleSystem::UpdateFunction
0x00007FFD3F6E73E6 (UnityPlayer) JobQueue::Exec
0x00007FFD3F6E8810 (UnityPlayer) JobQueue::Steal
0x00007FFD3F6E7634 (UnityPlayer) JobQueue::ExecuteJobFromQueue
0x00007FFD3F6E7923 (UnityPlayer) JobQueue::ProcessJobs
0x00007FFD3F6E8E30 (UnityPlayer) JobQueue::WorkLoop
0x00007FFD3F7DC7E8 (UnityPlayer) Thread::RunThreadWrapper
0x00007FFD68BA7034 (KERNEL32) BaseThreadInitThunk
0x00007FFD6A002651 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/Frank/AppData/Local/Temp/The Fun Pimps/7 Days To Die - Dedicated/Crashes
`

**Comment by LPMZ** [comment]
for now in several days it doesn't happen anymore in version 20.0.41

**Comment by ObsComp** [comment]
Closing this one as it seems to be okay at this time
