### ISSUE TITLE
conflict between /friend feature and teleport detection

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#37]
Not sure if you got my reply since the original (issue #33) was set to "closed". If you did then I apologize for making a duplicate but I wanted to let you know that this is still happening even with the latest fix.

**Comment by markrjackson** [comment]
Same thing is also happening when people use /home command. They are detected/banned for teleporting.

**Comment by ObsComp** [comment]
Oh darn, sorry. I will throw it back into the test lab :)

**Comment by ObsComp** [comment]
Teleport check is disabled in the latest version due to false positives. I have to learn how to code something new for that to work out. Sorry
