### ISSUE TITLE
Getting and setting CVars

### ISSUE THREAD

**Issue by OmitLeChuck** [dmustanger/7dtd-ServerTools#374]
Hi,

I have a feature request.
It would be very nice if there will be a command for the console to set and get a CVar.

Example(s):
`setcvar <steamid/entityid/name> myVarName "My Var Value(s)"`
sets the CVar so that it can be used in a characterinfo - window.

`getcvar <steamid/entityid/name> myVarName [json]`
returns the given CVar raw or in json format like `{"myVarName":"My Var Value(s)"}`

`getcvars <steamid/entityid/name> [json]`
returns all CVars raw or in json for the player

This will be great and for this feature you will be always in my heart.

**Comment by ObsComp** [comment]
This has been added as you know. I will on it some more soon
