### ISSUE TITLE
Hook to Discord channel 

### ISSUE THREAD

**Issue by MaxWatson94** [dmustanger/7dtd-ServerTools#375]
Hi there, find bug. 
If I activate discord bot for show game chat, all users who have emoji in nickname will be crash server.
Nickname like: Fire*FoX\El'FoX🔥

**Comment by ObsComp** [comment]
Yikes. Okay thanks

**Comment by ObsComp** [comment]
I think I fixed this with a U+ check on the messages. Can you confirm it is working now with more recent releases?

**Comment by MaxWatson94** [comment]
I checked! Now there is no such error!
