### ISSUE TITLE
Bad words filter  does not work

### ISSUE THREAD

**Issue by hameleon0128** [dmustanger/7dtd-ServerTools#379]
Hello!

Experiencing some problems with the bad word filter.
First: If I add words using the add command, I get this message: "[SERVERTOOLS] Could not add entry. Bad word already found"
This happens even if the list is empty! (100% there is no such word)
I write the following: "bwf add test"
Possibly wrong syntax?
Further. If I add a line in the XML file: "<Bad Word="test" />" - then if I say test in the chat of the game, nothing happens.

Thank you. I count on your support.

**Comment by ObsComp** [comment]
Hi sorry I missed this post. My apologies. I will write this down for rework
