### ISSUE TITLE
time for mute

### ISSUE THREAD

**Issue by xorex** [dmustanger/7dtd-ServerTools#38]
time for mute console command

`mute add <steamId> <time_in_minutes>`

and maybe options for default time in main settings for **mute add** command

**Comment by ObsComp** [comment]
Yeah that is a good idea. I will add it to the list. Thanks

**Comment by ObsComp** [comment]
This is added to 9.0. Default muting sets them to 60 minutes but you can put what you want via console. mute add steamId/entityId time. Put -1 to set them to infinite.
