### ISSUE TITLE
[Bank] Issue parsing variables for commands

### ISSUE THREAD

**Issue by unsivilaudio** [dmustanger/7dtd-ServerTools#380]
Deposits to bank are not working. I believe this is an issue with reading the player inventory.  Example of /deposit and /withdraw commands for bank.
![image](https://user-images.githubusercontent.com/26225174/163275564-f170d70a-ebd9-4907-89b1-506e57de9a13.png)

**Comment by ObsComp** [comment]
Ok, I have written the bank down for tests. Thanks

**Comment by unsivilaudio** [comment]
So here's the thing, _It does actually work_ just not as I expected it to. Maybe just improve the error messages? **I still thought you had to put coins in secure storage to deposit.** Still I thought it was weird that the variable names weren't parsing correctly.

**Comment by ObsComp** [comment]
This should all be fixed in the latest version. 
If you are still having variable issues, check your Phrases.xml has been updated. It is possible I changed the variable and you still had an older version of the phrases setup
