### ISSUE TITLE
Web_API suddenly stops working.

### ISSUE THREAD

**Issue by hameleon0128** [dmustanger/7dtd-ServerTools#381]
Web_API suddenly stops working. And with it some other features. I tried reinstalling the mod. enable and disable Web_API too.
The ports are all open.  What could be the problem?

**Comment by theronhh** [comment]
> Web_API suddenly stops working. And with it some other features. I tried reinstalling the mod. enable and disable Web_API too.
> The ports are all open. What could be the problem?

Same Problem here, since the last update the Web API doesn works

**Comment by ObsComp** [comment]
Is this 20.4.0? Please try the latest and let me know if it is still a problem for you

**Comment by AzraelX06** [comment]
I'm having an issue with it also, tried different ports and a number of other things and I'm getting the following pair of errors in the console:

```
[SERVERTOOLS] Host IP could not be verified. Web API has been disabled
[SERVERTOOLS] The host ip could not be determined. Web API is disabled
```

Nothing I am able to do seems to be able to get the API to work.

**Comment by hameleon0128** [comment]
> Is this 20.4.0? Please try the latest and let me know if it is still a problem for you

It seems to work. :) Installed the latest version helped. If anything changes, I'll let you know. Thank you.

PS. it remains to parse with the filter of bad words.

**Comment by AzraelX06** [comment]
Okay to amend my previous comment, that issue was related to adding Server Tools to what I thought was a new game, but was actually an existing save. 

I'm still having the issue of connecting to the Web Panel, however. 

When attempting to access the web panel on multiple browsers nothing happens, I'm usually presented with a blank screen. 
 
This is on the current version (20.4.0).

**Comment by AzraelX06** [comment]
A further addition to my comments on this post, the web panel is now working... 
I have done a complete server reinstall as I've changed over to Undead Legacy. 
The only thing I did differently this time was I left the port at the default 8088 and it's working :S

**Comment by ObsComp** [comment]
Version 20.6.0 has been released. Recommend it to further improve the Web_API. 
Web_API issues have not been reported for a while so I am closing this
