### ISSUE TITLE
Invalid modify slot from buy shop

### ISSUE THREAD

**Issue by GunzenRising** [dmustanger/7dtd-ServerTools#382]
The issue is when I buy weapons or any items have Quality from shop I received item with invalid modify slot it give only 1 or 2 modify slot. I will check other functional feature like gimme or reward not sure is it same result.

Sample : When I buy AK47 with Quality tier 6, It give modify slot by random just only 1 or 2 slot, The correct must be 4 slot.

**Comment by ObsComp** [comment]
Hmm interesting. That might be a bug with the game to some degree. I have not tested for that specifically but wrote it down

**Comment by ObsComp** [comment]
This has been fixed. Please update to the latest version of ST
