### ISSUE TITLE
Using mod causes log creation to fail.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [dmustanger/7dtd-ServerTools#385]
I don't know if you shut it off or changed it but at least in a20.3 when trying to debug issues the game does not generate logs like these.
![869CrIz 1](https://user-images.githubusercontent.com/10351221/167465257-1905e40c-6ade-46ea-ab0e-005835f1545b.png)

**Comment by ObsComp** [comment]
It definitely should not be doing that. I dont have anything coded specifically to turn it off. Ironically I would need to see an output log to try and confirm what might be happening there

**Comment by P3rf3ctXZer0** [comment]
trust me I know XD

**Comment by ObsComp** [comment]
The game itself may have done that after changing your startup.bat. Do you have a host? They may have also modified it.

How does it show up now?
