### ISSUE TITLE
Country Ban not working as intended

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [dmustanger/7dtd-ServerTools#386]
When adding country ban addon you get a red text relating to harmony parsing. Not sure what that is about.

**Comment by ObsComp** [comment]
Is this with the latest release 20.4.0?

**Comment by P3rf3ctXZer0** [comment]
No this was with the latest a20.3b6 release. As a20.4 was a complete dumpster fire. I will be testing things with the latest a20.5b2 EXP when I get the chance. Was going to go back to some MC for a while as I have better building options.

**Comment by ObsComp** [comment]
You can still use the latest servertools release which is now 20.5.0 even if your game is an older version. You just can't go back to something like a19 and use ST 20

**Comment by ObsComp** [comment]
I released a new version of country ban which should have fixed the command to edit the banned countries, however I have a report from someone that it is still not banning them upon entry. The command is fixed but the process does not seem to be working. I have it marked for tests and will sort it out
