### ISSUE TITLE
Can't find examples of how it works {SetReturn} and {Return} 'trigger'

### ISSUE THREAD

**Issue by BECTEPH** [dmustanger/7dtd-ServerTools#387]
I tried to teleport to the zone and back, but it doesn't work.
Here is my code in CustomCommands.xml
`<Custom Trigger="Test" Command="{SetReturn} ^ tele {Id} 288 2 288" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />`
`<Custom Trigger="Testback" Command="tele {Id} {Return} 'Test'" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />`

**Comment by ObsComp** [comment]
You were close. {SetReturn} will take the trigger name and current location and save it as that so when you want them to go back to that location you use {Return} Test.

Does that make sense?

<Custom Trigger="Test" Command="{SetReturn} ^ tele {Id} 288 2 288" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />
<Custom Trigger="Testback" Command="{Return} Test" " DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />

**Comment by BECTEPH** [comment]
don't understand, please give example
don't working code:
`<Custom Trigger="Test" Command="{SetReturn} tele {Id} 288 2 288" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />
<Custom Trigger="Testback" Command="{Return} Test" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />`

**Comment by ObsComp** [comment]
<Custom Trigger="Test" Command="{SetReturn} ^ tele {Id} 288 2 288" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />
<Custom Trigger="Testback" Command="{Return} 'Test'" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" />

**Comment by ObsComp** [comment]
Regardless of putting capitals in the trigger, it will apply a lower case version.

You were missing ^ between {SetReturn} and your second command
