### ISSUE TITLE
Custom Commands {Return}

### ISSUE THREAD

**Issue by chullachulla** [dmustanger/7dtd-ServerTools#390]
Hi! The {Return} part sends players to 0,0.  

I have been having trouble with /lobby and /lback. So I disabled it and made a custom command instead. I just updated to the 20.5 version (it didn't work with 20.4 either).

`
<Custom Trigger="test" Command="{SetReturn} ^ tele {EntityId} 1639 44 3137" DelayBetweenUses="0" Hidden="false" Reserved="false" Permission="false" Cost="0" /> <Custom Trigger="testback" Command="{Return} test" DelayBetweenUses="0" Hidden="true" Reserved="false" Permission="false" Cost="0" />
`

I tried it with other keywords as well, it does the teleport, but never the return.

**Comment by ObsComp** [comment]
Alright I have it marked down for the next round of patch work, thank you for the report

**Comment by mchastant** [comment]
{Return} still teleports to 0,0.  Any word on a fix?

**Comment by ObsComp** [comment]
It is still in my stack for bug fixes. I will bump it up in priority for next patch. Thank you for the reminder

________________________________

**Comment by ObsComp** [comment]
This has been fixed in version 20.6.9
sorry for the delay
