### ISSUE TITLE
ServerTools xml folder installed in a different location than 20.4

### ISSUE THREAD

**Issue by Obiwanmonrobi** [dmustanger/7dtd-ServerTools#391]
I have been using 20.4. and enjoyed it.  It created a ServerTools folder underneath the main server folder (with all of the other main folders like the Mods folder).  When I upgraded I removed the Servertools folder underneath mods first, then put the new version in its place. I did not touch the ServerTools folder with the xml configs.  After I installed 20.5 it created a new Servertools folder underneath my Saves folder and doesn't seem to be working anymore.  For now I've rolled back to the 20.4 version.  The new location under Saves only has 3 files, commandlist.xml, servertools.bin, and servertoolsconfig.xml.

**Comment by CosMic92** [comment]
I have a similar issue, i installed 20.5, removed my servertools folder with all xml files, so the new version would make a new one, with all the new features, but the folder was never created and im stuck with no features :)

**Comment by ObsComp** [comment]
Hi, sorry for the hiccup. I have released another version. 20.5.2.

This addresses some of the folder and xml creation issues.

Just a reminder, ST must be located in your user data folder. If you have not specified a custom location, the user data folder will default to app data.  The fun pimps are switching all mods to run from this user data folder in the future, so we have coded the change in.

You can move your xml files in to the new location and they will be updated to the most recent version while maintaining your settings.

**Comment by Obiwanmonrobi** [comment]
I'm running my server from a hosting company named PingPerfect so I don't have a userdata folder but as long as I can just move the files over that will work.  Thanks for looking into this.
