### ISSUE TITLE
Wall command - Not working

### ISSUE THREAD

**Issue by CosMic92** [dmustanger/7dtd-ServerTools#393]
This might be user error, but command says it is enabled when i type /wall, i put down a claim and secure chest with same blocks i have on my toolbelt, but when i place two down the feature wont fill the gap. am i missing something?

**Comment by ObsComp** [comment]
It is not meant for frames. Make sure to use complete wall blocks such as concrete or wood. Also make sure it is in the same line. By that I mean it will create a single wall only if the blocks line up on the same parallel. Everything else sounds right. Let me know if it works with completed blocks.

**Comment by ObsComp** [comment]
I can confirm it is acting kind of weird to what it should be. I will do some more work on it

Thank you

**Comment by ObsComp** [comment]
Wall tool has been redone and simplified. Instructions have been updated in the HowToSetup file for 20.6.9
