### ISSUE TITLE
it-takes-a-village mod not woking

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#397]
https://7daystodiemods.com/it-takes-a-village-a-server-side-co-op-overhaul-mod/
it-takes-a-village not working on this mod!

**Comment by ObsComp** [comment]
ST should not conflict with it but a full conversion can do crazy things. I would need an output log to know what might be happening

**Comment by ObsComp** [comment]
If you can provide an output log from the server boot up, that would help address what might be conflicting or if there has been an installation error of ST

**Comment by kamohy** [comment]
it works ! :-)
