### ISSUE TITLE
Cant install servertools dedicated server

### ISSUE THREAD

**Issue by Djassie18698** [dmustanger/7dtd-ServerTools#398]
When trying to install on my dedicated server on linux i get this error. 
![image](https://user-images.githubusercontent.com/51295582/183999967-96b11384-2864-4870-b33c-5e92c3a7ed59.png)
 Do you know why?

**Comment by ObsComp** [comment]
ServerTools is the first to go ahead with the new changes to Mod folder location. The game devs will drop support for the old location at some point. All mods should go to ...UserDataFolder/Mods

In your case, your user data folder is /home/container/.local/share/7daystodie

Add a Mods folder to this location and put ServerTools there

**Comment by Djassie18698** [comment]
Thankyou guys so much, I changed the installation and it all works amazing now. 
Sorry for the late response, life got in the way and wasn't on the PC for a while. It all works now! :)
