### ISSUE TITLE
needs a update

### ISSUE THREAD

**Issue by reserect** [dmustanger/7dtd-ServerTools#399]
Will this be updated for the latest 7 days to die?

**Comment by 1trueway** [comment]
Is this why I cant get it to generate a ServerTools.xml file?

**Comment by ObsComp** [comment]
Version 20.6.0 has been released. It worked without needing an update. ServerTools generally works across an entire alpha regardless of the version so Alpha 20, any version will work with ServerTools 20.0.0+  until the next alpha comes out and then I new version is released to match. I hope that made sense. Anyways, ST 20.6.0 is out now

**Comment by 1trueway** [comment]
It is now updating max lives correctly.

It is not updating player deaths. 1 life remaining - die - still 1 life
remaining.
