### ISSUE TITLE
Request - Region Banning

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [dmustanger/7dtd-ServerTools#4]
So I am looking to ban regions and if they attempt to circumvent it the game asks for a password which would actually be a 64 bit random gen encryption key that your tool would generate on each server reboot.

-primary targets are-
China
Russia
Ukraine
Egypt
Japan

I tried that shitty Envul Software even paid them and they were useless.

**Comment by dmustanger** [comment]
I plan to add something like this

**Comment by MkxTrax** [comment]
Hey dude. is their any chance that u can look into why it conflicts with /cancel reboot. Obviously not a clancommand. but when using I need to use tcch / in console otherwise i get clanmanger not enabled??

thanks

**Comment by ObsComp** [comment]
Maybe I am not understanding what it is you are trying to do. When the restart kicks in and is in countdown, you would like to cancel it? To do this you open the console and type stopserver cancel

**Comment by ObsComp** [comment]
You might have a conflict Mkx with another mod using the / for chat commands. You can use a custom chat trigger via the config for the private (/) or announce (!) chat triggers.

**Comment by dmustanger** [comment]
this will be released with a17 
https://github.com/dmustanger/7dtd-ServerTools/commit/181cce66662d1ca4f3978170502f04336fc4b883
