### ISSUE TITLE
Change the way clan tag protection works

### ISSUE THREAD

**Issue by dmustanger** [dmustanger/7dtd-ServerTools#40]
change the clan tag to add the tag in front of a players name instead of kicking a player with that name

**Comment by ObsComp** [comment]
People can use it as a way to boot people or other clans who have that in their steam name. I will try and work on it asap

**Comment by ObsComp** [comment]
This has been changed in 9.0. Clan tags are now applied as a prefix and replaces the other coloring prefixes if they have one. The color will stay the same though. The auto boot for names containing clan names is gone. A real clan member will have the prefix.
