### ISSUE TITLE
Hardcore Not Updating Player Death Count - only player life count

### ISSUE THREAD

**Issue by 1trueway** [dmustanger/7dtd-ServerTools#400]
The "optional" setting gives you 2147483648 lives plus whatever amount of lives you input for Max_Lives. If you input -2147483647 lives to give the player 1 life, this works. The broken part of it all is that it seems to not be acknowledging the players death counts. Player has 1 life remaining, then dies, and still has 1 life remaining.

An excerpt from the src/Tools/Hardcore.cs -->

                if (Hardcore.IsEnabled && PersistentContainer.Instance.Players[id] != null)
                {
                    if (Hardcore.Optional)
                    {
                        if (PersistentContainer.Instance.Players[id].HardcoreEnabled)
                        {
                            Hardcore.Check(_cInfo, _player);
                        }
                    }
                    else if (!PersistentContainer.Instance.Players[id].HardcoreEnabled)
                    {
                        string[] hardcoreStats = { _cInfo.playerName, "0", "0" };
                        PersistentContainer.Instance.Players[id].HardcoreStats = hardcoreStats;
                        PersistentContainer.Instance.Players[id].HardcoreEnabled = true;
                        PersistentContainer.DataChange = true;
                        Hardcore.Check(_cInfo, _player);
                    }
                }
                
This is why the Optional setting sets the initial lives at a crazy number. It's never initialized or something. In the Optional = False setting - it gets set to 0, and applying a Max_Lives of 1 gives you 1 life. 

Regardless of Optional true or false, the player deaths are not updating. I tried to understand it, but I've never coded in C and have never modded anything. Truly running blind. I assume the Hardcore.Check(_cInfo, _player) is supposed to update or pull the deathcount somehow, but that's all wizardry to me.

**Comment by ObsComp** [comment]
Hi, I believe that is fixed now in version 20.6.0.

Please try it out and let me know

**Comment by 1trueway** [comment]
The Max_Lives config now sets the lives to that value as intended for both optional and not optional HC mode.

The main issue is that dying does not remove a life. 1 life remaining - die - still one life remaining. Server Tools isn't getting updated on player deaths.

**Comment by ObsComp** [comment]
20.6.2 addresses the Hardcore bug. Please repost a report if you continue to have issues with the tool
