### ISSUE TITLE
does not detect new currency

### ISSUE THREAD

**Issue by WEEDMEN** [dmustanger/7dtd-ServerTools#401]
I am trying to configure a new currency and servertools does not detect it, it keeps giving me the vanilla currency, how can I fix it?

![image](https://user-images.githubusercontent.com/35629566/186343803-daf5eb2e-fad2-4db1-adfb-e0f28bd66577.png)

![image](https://user-images.githubusercontent.com/35629566/186343916-5112a420-b7eb-409a-95dc-3f07150baa12.png)

**Comment by lcdblunt** [comment]
How did you fixed this?
