### ISSUE TITLE
INFINITE AMMO DETECTION

### ISSUE THREAD

**Issue by Retsof123** [dmustanger/7dtd-ServerTools#402]
I seem to be getting a number of false positives with the Infinite Ammo detection. Always comes up with -9 ammo with weapons ranging from pipe shotgun to M60 and causes unnecessary bans.  I have had to disable the detection.

**Comment by ObsComp** [comment]
yes I think I have figured out what is causing it. I will like redo how it functions soon. thank you for the report

**Comment by ObsComp** [comment]
This was improved in a more recent release. Removing this post. Please use 20.6.5 +
