### ISSUE TITLE
Darkness Falls issue

### ISSUE THREAD

**Issue by Tempritscher** [dmustanger/7dtd-ServerTools#405]
Greetings
I have some issues to setup an Server with ServerTools + DarknessFalls

2022-09-01T22:57:19 177.636 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"
2022-09-01T22:57:19 177.638 EXC The type initializer for 'ServerTools.Config' threw an exception.

is there a compatibility issue or do i need to change something in order to use it with darkness falls?

**Comment by smnio** [comment]
Seeing this too. Noticed that the ServerToolsConfig.xml has not been created anywhere on my server.

**Comment by toddpeltier** [comment]
Same issue....
2022-09-07T15:26:46 234.477 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"
2022-09-07T15:26:46 234.482 EXC The type initializer for 'ServerTools.Config' threw an exception.

Using ServerTools-20.6.1
Server has been up an running without any other issues for a few weeks......

**Comment by ObsComp** [comment]
I am not sure if people are using the old location or what the problem is. I dont use darkness falls and dont test against it since it is a separate full conversion mod. Try version 20.6.2
I added the ability to install to the old location since people cant or wont use the new location

**Comment by ObsComp** [comment]
Just a heads up, if you use the old location, expect every single mod to stop working eventually. The dev will not support that location forever

**Comment by toddpeltier** [comment]
> Greetings I have some issues to setup an Server with ServerTools + DarknessFalls
> 
> 2022-09-01T22:57:19 177.636 ERR [MODS] Error while executing GameStartDone on mod "Server Tools" 2022-09-01T22:57:19 177.638 EXC The type initializer for 'ServerTools.Config' threw an exception.
> 
> is there a compatibility issue or do i need to change something in order to use it with darkness falls?

7dtd-ServerTools-20.5.5 works perfect with 20.6 version DF. Been running for a week now.

**Comment by ObsComp** [comment]
Please try ServerTools 20.6.2
________________________________

**Comment by Tempritscher** [comment]
> 

latest build fixes the issue.
#closed
