### ISSUE TITLE
EXC The type initializer for 'ServerTools.Config' threw an exception.

### ISSUE THREAD

**Issue by Taavi95** [dmustanger/7dtd-ServerTools#406]
Hello, 

i followed your instructions but im not able to get this mod work on my server. 

Im using 7DTD on my own hosted root server with windows server 2019. If i past the Mod Folder in appdata or in Server mods folder i get the same error:

2022-09-08T06:40:23 62.197 ERR [MODS] Error while executing GameStartDone on mod "Server Tools"
2022-09-08T06:40:23 62.202 EXC The type initializer for 'ServerTools.Config' threw an exception.

is there something i can try to fix that? 

thank you in advance

**Comment by Taavi95** [comment]
I could make it work with Version 20.5.5. Maybe its helping someone :)

**Comment by ObsComp** [comment]
Unfortunately I am not sure why that is happening. Try version 20.6.2
It allows for both locations for installation. Preferably you will use the User Data Folder location which may be your app data location. Do not install to two locations

**Comment by Taavi95** [comment]
Great thank you very much for your work! :) its working fine now!
