### ISSUE TITLE
ST UPDATE INITIALISATION

### ISSUE THREAD

**Issue by Retsof123** [dmustanger/7dtd-ServerTools#407]
I updated to 20.6.2 and it did not backup old XML files or check existing the config for existing installation. I had to manually setup the servertoolsconfig.xml again. The same happened with 20.6.0 and 20.6.1. The last XML backup I have is 20.5.5. The earlier versions I put down to confusion over mod locations and my server host company being recalcitrant about it until I finally convinced them.  Updating to 20.6.2 did not have that problem.

I deleted the old ServerTools folder in ../UserData/Mods before copying the new update back into that location. The ServerTools data folder, in ../UserData remained throughout. It was like a fresh installation. Everything in the config was default, therefore needing a manual setup.

**Comment by ObsComp** [comment]
That could happen depending on the installation location. People have been jumping from the old location to the new one and I did not program it for both

**Comment by Retsof123** [comment]
I have been using ../userdata/mods since V20.6.0. I don't believe that's the issue. V20.6.0 was the trial and error phase between ../mods, ../data, and ../userdata/mods but was resolved in the latter, by me not the host (just made sense), before you did the wallet hotfix to v20.6.1. After v20.6.1 we completely wiped 7DTD from my server and it was migrated to new hardware, so no residue from previous installs. Next update I will monitor although I am going to be away for three weeks.

**Comment by ObsComp** [comment]
I found some small bugs that might have been contributing to the file getting wiped in special cases. They have been addressed for the upcoming release 20.6.3.

After this has been released and you have given it a try, let me know if it wiped your settings on the update. Crossing my fingers that this helps address some of the last issues people have faced.

You should always have a backup of the xml automatically taken during the update for reference sake at the very least.

**Comment by Retsof123** [comment]
Cool

**Comment by ObsComp** [comment]
Hiya. Version 20.6.3 has been released. 

Are the XML backing up for you?

**Comment by Retsof123** [comment]
All worked as it is supposed to. Thank you for your perseverance, I appreciate it.
