### ISSUE TITLE
[Wiki/Help] Could not find imap setup on your wiki page.

### ISSUE THREAD

**Issue by ErythroCraft** [dmustanger/7dtd-ServerTools#413]
Hello

Couldnot find a wiki entry for the online map.

st-version: 20.6.5
7DTD-version Alpha 20.6(b9)

Ports 8082 and 8084 I created.
Maybe I got any misstakes

[ServerToolsConfig.txt](https://github.com/dmustanger/7dtd-ServerTools/files/10049611/ServerToolsConfig.txt)
[IMapPermission.txt](https://github.com/dmustanger/7dtd-ServerTools/files/10049615/IMapPermission.txt)

**Comment by ObsComp** [comment]
IMAP has not been completed. It is still under development. It works in combination with allocs fixes. You just need to install allocs and tell it where the map files are located. The folder location that is. Then it will work in game when you type /imap. A link pops up you can click, taking you to the interactive map but the tool is hardly coded beyond exactly that. You can not even see players on it yet. It is being developed still so I would not bother too much with it until it gets more features added

**Comment by ErythroCraft** [comment]
ok. have it.
