### ISSUE TITLE
Ability to use clock time instead of x minutes in config?

### ISSUE THREAD

**Issue by TheEhTeam** [dmustanger/7dtd-ServerTools#419]
Would be nice to use a clock/system time option for the server shutdowns/backups/etc. configs instead of just time in x minutes... Would be more compatible with my server cron jobs as the system time and x minutes don't align for many reasons.

**Comment by ObsComp** [comment]
You can already do that. Enter it as 24 hour time
Example:
08:00
15:45
23:50
or multiple entries in one like this:
08:00, 15:45, 23:50

**Comment by ObsComp** [comment]
Not all tools allow this but things like backups, shutdowns infoticker and some others all have that option
