### ISSUE TITLE
request: small change to wallet console command

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#42]
It's great to be able to add/subtract from wallet but sometimes an admin needs to see current balance. Can you make a small change to wallet console command so that the `<value>` parameter is optional and if someone does `wallet <steamid>` without a value then it returns the current balance.

**Comment by ObsComp** [comment]
Absolutely great idea! I had forgot about it. *Russling stack of notes* hahah
Releasing 8.0 finally so I can look at new stuff like that.

**Comment by MkxTrax** [comment]
ObsComp, Just wanted to say excellent support you've added and truely grateful for the hardwork work put in to you, mustanger and individuals who help in the cleaning and Identifying of bugs etc.

I have several servers. I already actively promote such console plugins as a way of support, shout if I can help in testing or identifying. thanks.  steam page SSXAribo if you wanted to jump on another server for comparing or whatever, let me know I will assign rights and we can allocate time, if that helps in anyway.

**Comment by ObsComp** [comment]
This is command has been added in 9.0. wallet steamId will show their value. This does not update as live as I would hope but its quite accurate. The only thing that does not update is the zombie kills that help calculate the wallet value.  That updates just for this command when they login or out
