### ISSUE TITLE
Lobby Return not work

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#421]
Hello 
I have set a lobby. In the xml "Return=True" the teleport to the lobby works, in the chat also comes the message: Return with the command /lback (by the way, in the HowTo.xml it says /return) but both do not work.

**Comment by ObsComp** [comment]
Ok I will check it out, thank you

**Comment by sLimLong** [comment]
Return market does not work.

**Comment by ObsComp** [comment]
yes that and lobby have both been tweaked for next release already. Bunch of fixes and improvements on their way
________________________________

**Comment by ObsComp** [comment]
The lobby and market return options have been fixed in version 20.6.9. Thank you for the report
