### ISSUE TITLE
CommandList Change

### ISSUE THREAD

**Issue by JoeWenger1** [dmustanger/7dtd-ServerTools#423]
Hello, 
I wanted to change the commands for deposit and withdraw.
Unfortunately only the original commands disappear from the list.
Tried other commands, only /commands itself is changeable and works.
Also made a server restart
Here is my change:
    
XX Command Default="deposit" Replacement="payin" Hidden="false" XX
XX Command Default="withdraw" Replacement="payout" Hidden="false" XX

**Comment by ObsComp** [comment]
Are you inputting it with those XX ?
