### ISSUE TITLE
in 20.6.8 not work discord with discordian

### ISSUE THREAD

**Issue by dakravch** [dmustanger/7dtd-ServerTools#426]
send from game-in discord nothing. onle ServerTool notify appear in discord channal like  pvp kill
send from discord- appear console "NullReferance:object not set"

BUT
in version 20.6.5 send from game work correctly
send from discord-bug-console appear

**Comment by ObsComp** [comment]
Yes, sorry. Discordian is not working at this time. I honestly was not aware so many people were using it. Nobody had really said anything. I guess because it was working

**Comment by ObsComp** [comment]
Discordian has been discontinued at this time, my apologies. A future release and back end may be established but the dev team has discontinued the project for the time being
