### ISSUE TITLE
Bank deposit error

### ISSUE THREAD

**Issue by batboyboy1990** [dmustanger/7dtd-ServerTools#430]
Bank deposit error
can only send the first time, the second time can't send and the money is still lost, I use it with darknessfall and bloodcoin money

**Comment by CanucksIgnited** [comment]
im having the same issue. unable to deposit anything without the coins just disappearing. also not able to use the bank money for the shop it has to be withdrawn first

**Comment by ObsComp** [comment]
Bank has been fixed in version 20.6.9. Please give that a try and let me know if any more problems persist with the bank
