### ISSUE TITLE
I can't get the Discord Webhook or Bot to work at all

### ISSUE THREAD

**Issue by CitizenPrayer** [dmustanger/7dtd-ServerTools#431]
I've been at this for hours. I know the webhook URL is correct, I've followed all the steps for discordian, and nothing seems to be working whatsoever. I can start the Discordian bot but as far as it integrating with ServerTools in any way, it's just not happening. I'm not sure what's going on.

**Comment by ObsComp** [comment]
Hi the discord bot is not working from what I know. The webhook is working again in version 20.6.9

**Comment by ObsComp** [comment]
Discordian development has been discontinued, my apologies. the webhook will remain and still works. The back end for Discordian still exists if you already have it but it will not developunder its current production library. A rebuild of the back end and new library implementation will need to be addressed first. The entire project will have to be rebuilt before a new release
