### ISSUE TITLE
server tools dont work

### ISSUE THREAD

**Issue by PaddPadd** [dmustanger/7dtd-ServerTools#441]
Hi,

this "mod" dont work for me. I have follow the instructions, i have the xml, set all i want to true but cant do anything, no command or anything works. Have the latest Version. No error message, no info. I dont no whats the Problem. Can anyone help me?

**Comment by ObsComp** [comment]
The game has updated to a new alpha version. New versions of ST are available for that in specific.

Can you provide an output log from your dedicated server?
