### ISSUE TITLE
Discordian bot

### ISSUE THREAD

**Issue by MiPnamic** [dmustanger/7dtd-ServerTools#444]
In the Readme.md [here](https://github.com/dmustanger/7dtd-ServerTools#discord_bot--discord_bot_extended)

you should provide a link to the intended Discordian bot you mention

**Comment by ObsComp** [comment]
Discordian bot has been discontinued by the dev team for the time being. My apologies. Existing users can still run the file but updates will not be released with the current Discordian implementation. There has been a conflict with a library utilized in its production. I wont get into specifics here but the dev team has dropped support and will need to reform the back end. In the mean time, webhook tool will continue to function but Discordian will not receive updates at this time.
