### ISSUE TITLE
Normal players can't use /commands replacement

### ISSUE THREAD

**Issue by jaydee0004** [dmustanger/7dtd-ServerTools#446]
Using version Alpha 21 b323

It seems like normal players can't use neither /help (the replacement or /commands for some reason, while me, as an admin, can do.

Is this a permission thing I need to setup somewhere?

Also, when a user is typing a command they can't use, it removes the custom chat formatting (prefix,color,etc.).

**Comment by ObsComp** [comment]
When you run a command, they do not show colors and prefixes, this is for command utilization purpose. If I were to apply a color and it was not a servertools command, but rather for another mod, the color application will likely break the command so it is avoided. When a command is used by and applied by servertools, it stops the command from showing in game chat. Check your output log shows servertools is actually handling the chat. Another mod might be taking over. 

Try the latest release of ServerTools as well to be sure no bugs were occuring

**Comment by ObsComp** [comment]
This has been updated in more recent versions. All commands should show properly in response to /commands along with custom adjustments to the commands
