### ISSUE TITLE
missing some defaults to voting line in config

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#45]
Voting line in config missing defaults "Reward_Entity" and "Entity_Id"

**Comment by ObsComp** [comment]
You can add those manually but 8.1 has released. Tell me if it does not update correctly.

**Comment by ObsComp** [comment]
Ah nvm I see the bug
Thank you sir. Will release the fix soon

**Comment by ObsComp** [comment]
8.2 is out with the fixes :)
