### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by piranhas37** [dmustanger/7dtd-ServerTools#455]
idk where from comes but when i enable extra commands like bed or bigheads new error in server console shows i have version 21.06
[SERVERTOOLS] Error in EventSchedule.Exec: An item with the same key has already been added. Key: Shutdown

**Comment by piranhas37** [comment]
i have set shutdown false and error gone but when enable again that error

**Comment by piranhas37** [comment]
and /shutdown command not works something wrong on it plz check it

**Comment by ObsComp** [comment]
Hi this was updated in the latest edition 21.0.7
Are you still having issues?

**Comment by ObsComp** [comment]
I have addressed some issues with the scheduler for the upcoming release. It should hopefully be better than ever :)
21.1.0 is the latest being worked on. I will close this issue for now as both issues have been addressed in the upcoming release
