### ISSUE TITLE
Kits

### ISSUE THREAD

**Issue by sLimLong** [dmustanger/7dtd-ServerTools#46]
Add kits with the option "resolution level" and the timer

I think many such a function came in handy who supports donate.

**Comment by ObsComp** [comment]
I have no idea what you are trying say

**Comment by sLimLong** [comment]
Sorry, I can not do it in words. Here is an example: The player writes / kit donat, And receives items 3-6

Just need commands that give items to players

**Comment by Thodde26** [comment]
Hello ,
he means kit's (starterkit, adminkits, toolkits) you can get free tools within 24 hours, for example, and link this with the permission system. Guests or newcomers can not use this, but User  from Permission 100 can do it. i hope you understand what i mean
