### ISSUE TITLE
Some of the commands don't work

### ISSUE THREAD

**Issue by besterry** [dmustanger/7dtd-ServerTools#463]
A21 b324
I turned on the bank system, at first it worked for me, but after rebooting the server does not send messages (the system itself works, but I do not receive a response to the /bank, deposit, withdraw, transfer commands)
```
<Tool Name="Auction" Enable="True" No_Admins="False" Admin_Level="0" Total_Items="1" Tax="1" />
<Tool Name="Auction_Extended" Panel="True" Panel_Name="Awesome Auction" />
<Tool Name="Bank" Enable="True" Inside_Claim="False" Deposit_Fee_Percent="5" Player_Transfers="True" Direct_Deposit="True" />
<Tool Name="Bank_Extended" Deposit_Message="True" Direct_Payment="True" />
<Tool Name="Wallet" Enable="True" PVP="False" Zombie_Kill="0" Player_Kill="100" Bank_Transfers="False" />
<Tool Name="Wallet_Extended" Session_Bonus="5" Currency_Name="coin" Item_Name="casinoCoin" />
<Tool Name="Shop" Enable="False" Inside_Market="False" Inside_Traders="False" Panel="False" Panel_Name="Super Shop" />
```
I checked the list of available commands in the file /home/sdtd/server/ServerTools/CommandList.xml
`<Command Default="bank" Replacement="bank" Hidden="false" />`
I also don't understand how the vault system works, the /vault command is not recognized and is sent as a normal chat message. (this also happens with many commands, such as day7, sort, fps and others)
Private messages /rm nickname message from the server, an empty message is received in response (the player is not online), although earlier a message was received that the player was not found/offline

**Comment by ObsComp** [comment]
Hiya, an output log showing these events would help figure out what may or may not be happening when attempting to utilize various commands.

Bank ties into the Wallet tool code currently, but is being patched to allow it to operate independently. Generally speaking you do not interact with a bank in real life without your wallet or some kind of exchange so it was meant to reflect how a bank works. People have instead wanted to force a digital gulag system on people so I have had to adjust it all recently to allow strict bank only payments, bank only deposit and allowing it all to function without a wallet. Bank bank bank bank. It is weird but whatever, it is what people like to do. I guess to make the game even easier so you can never lose anything? Not judging. Just tossing out the why and how come so I can understand how this should be implemented. Many want a wallet system, not a bank, others want a bank and no wallet. Some want them integrated. Some want custom currency mixed with a wallet and/or a bank. In the end they want it all and free.

If I know what people are trying to achieve then I can program for it but I keep having people throw curve balls and want things to operate the polar opposite of how they work in real life so just let me know what you are attempting to achieve.

Many tools are fudged up right now after multiple patches for the base game have come out, including a21 itself. I am not rushing any development currently. Production is admittedly very slow however I am working on another patch with a lot of additions, changes and updates. It would have already released but they patched the game again which broke more stuff so I am back to working on that again

**Comment by ObsComp** [comment]
This has been updated in more recent versions. All commands should be fully functional and show in the /commands response properly now. Thank you for the report
