### ISSUE TITLE
Protected zones not working properly

### ISSUE THREAD

**Issue by informationalTech** [dmustanger/7dtd-ServerTools#468]
the protected zones of server tools stopped working and I had to install the latest version to get them to load. I removed all files and did a clean install. Now it is loading I can add a zone but the protection only works if I am inside of the protected zone. Then it only works after the first hit. I can step up to a block in a protected zone and hit it with an ax and do damage. Step out of the zone, then step back in and do another single hit worth of damage. Outside of the zone I can inflict damage all day long with an ax or bullets or any long range weapon.
thank you

**Comment by ObsComp** [comment]
Yes this was discovered. It was a half measure after the developers changed something in the game that limits our ability to protect blocks such as we used to. I have rebuilt the protection entirely for version 21.1.4
This is in final testing and should be released soon however it will be posted at the new host site Bit Bucket.

Development of ST will be posted here
https://bitbucket.org/obsessive-coder/sevendaystodie-servertools/src/core/

Thank you for your report. Please feel free to follow development at the new host
