### ISSUE TITLE
/sort and weird behavior

### ISSUE THREAD

**Issue by Johnnytwohands22** [dmustanger/7dtd-ServerTools#469]
Hello,

I'm not sure if this is a ServerTools problem or a different issue that was exacerbated by it.

Sometimes when using the /sort ServerTool, we experience some weird behavior. Currently, items with mod slots that weren't filled now contain items like bullet casings or engines. This renders the item unusable and additionally shows numerous error codes in the console until you leave the menu. We also experienced a strange issue where bullet casings would explode from the zombies whenever they were killed. I have logs that show pages of errors after using the /sort command. Most of the time it works, but occasionally will throw a fit. 

Currently, every item in every box that has mod slots available is now filled with some non-mod item. Since I have server backups, is it possible to replace some files with "clean" ones that would at least restore the items themselves? If not, we'll have to dump all equipment on character and in boxes and find new stuff that hasn't been corrupted.

![image](https://github.com/dmustanger/7dtd-ServerTools/assets/133157071/98ad0941-e4d4-49b4-800e-6dba378e8d48)

**Comment by ObsComp** [comment]
Hi, this has been identified and fixed for the upcoming release 21.1.4
This will be posted on Bit bucket at
https://bitbucket.org/obsessive-coder/sevendaystodie-servertools/src/core/

I will no longer be using Github in the future. Please follow development at the host site

**Comment by ObsComp** [comment]
Thank you for your report and support of ST
