### ISSUE TITLE
gimme doesn't show public response

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#49]
Gimme command with `Always_Show_Response="True"` doesn't show public response. It used to work in the past but no longer.

**Comment by ObsComp** [comment]
Hmm, I will have to take a peak at it. Thanks

**Comment by dmustanger** [comment]
Fixed and will be in next release.

https://github.com/dmustanger/7dtd-ServerTools/commit/1ec5c0bec6a8bb632e962742071563d574051309
