### ISSUE TITLE
Fly Check

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [dmustanger/7dtd-ServerTools#5]
Basically if a player has a inAIR for longer than 60 seconds chances are they are flying! lol

**Comment by DPxKnightxZero** [comment]
Any update on this? Ultimately this is becoming even more needed. I was forced to password the server.

**Comment by dmustanger** [comment]
i will see what i can do.

**Comment by dmustanger** [comment]
added 
https://github.com/dmustanger/7dtd-ServerTools/commit/4adfc05743f364e5b5915650f941a9c0698808cf
