### ISSUE TITLE
9.0 AND 9.1 WORKING BUT DOESNT GENERATE THE SUBFOLDERS TO EDIT INVALIDITEMS AND SUCH.

### ISSUE THREAD

**Issue by NAPvPMinion** [dmustanger/7dtd-ServerTools#51]
tried to install both versions last nite with the help of our host. we tried many uninstall and reinstall attempts on the new updated versions. both versions seem to work fine except we couldnt get neither of them to generate the howtosetupxml and all the tool subfolders to edit. we had to revert back to the 8.6 version last known version to work for us.

**Comment by ObsComp** [comment]
Ah, really sorry to make all that work for you.  There was a nasty error I left in which I am pretty sure was stopping it from working. I have uploading 9.3. Let me know if it doesn't work though :)
