### ISSUE TITLE
/auction

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#52]
Fails to detect an owned secure chest with 1 stack in it.

**Comment by ObsComp** [comment]
there were some updates that hopefully helped with this. try out the latest version and let me know

**Comment by Malkadore** [comment]
Dedicated Host may not be using most recent version. Updating it now, Will let you know.

**Comment by Malkadore** [comment]
Auction function now works as intended. All commands.

Fixed.
