### ISSUE TITLE
v9.3 /doncolor not working

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#53]
Fails to edit SystemAdmin.xml as described.
Fails to detect added players in ReservedSlots.xml.

**Comment by ObsComp** [comment]
There were some bugs in the early 9.* releases. Try out the latest and let me know. There is another coming out hopefully in a few hours.

**Comment by Malkadore** [comment]
I'll wait until this new release in a few hours before contacting my host then. Thanks for letting me know.

**Comment by Malkadore** [comment]
v9.3

Enabled. 

Edited Server Admin and ReservedSlots xmls.

In-game, when typing /doncolor nothing happens. No text is displayed in either public chat or console.

**Comment by Malkadore** [comment]
Ok I'll upload 9.4 and test it again using the example format provided for reservedslots.xml and post the outcome here.
I have had to add a player manually to both serveradmin and reserveredslot xmls every time.

You could code donors the same as you have with the Admin and Mod tags using the serveradmin.xml to allow for administration to designate between options 1 2 and 3. I'm utilizing a VIP system of 3 levels based on donor contribution which is why it would be great. :p

**Comment by Malkadore** [comment]
No worries, I used the 'Special person' option you've provided in v9.4 for my VIP system. I'll close this ticket and start a new one if i find anything with v9.4's /doncolor
