### ISSUE TITLE
different balances between /wallet and /buy

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#54]
One of my users reported a bug where the /wallet shows enough balance to make purchase but /buy command shows a different balance (see screenshot). If it helps, I am using different values in the coin calculation (not default).

`<Tool Name="Shop" Enable="True" Negative_Wallet="True" Coin_Name="shadowcoins" Zombie_Kill_Value="25" Player_Kill_Value="100" Death_Penalty_Value="100" Shop_Anywhere="True" />`

![untitled](https://user-images.githubusercontent.com/16080527/38441876-6b1111f6-39a3-11e8-9bcd-01f581d688e2.png)

**Comment by ObsComp** [comment]
wow i wish i had that many shadowcoins lol.  i will look into it, thanks man

**Comment by markrjackson** [comment]
Here's another one for reference from a different user:

![coins](https://user-images.githubusercontent.com/16080527/38466091-174a3bf8-3ae1-11e8-913c-117614e92d74.PNG)

**Comment by ObsComp** [comment]
Got it fixed in 9.4 Thanks
