### ISSUE TITLE
infoticker doesn't cycle thru messages

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#57]
Changelog says infoticker was fixed but it only shows the first message over and over and doesn't cycle through the others (I am using latest 9.3 version). I have it set to `Random="False"`. It used to work in earlier versions.

https://github.com/dmustanger/7dtd-ServerTools/blob/f6ee419dabfbe2a89ec66caf40a7f4438dfad081/ServerTools/Changelog.txt#L10

**Comment by Malkadore** [comment]
I can so confirm it is broken.

**Comment by ObsComp** [comment]
9.4 is out, tell me if its okay again

**Comment by markrjackson** [comment]
Installed 9.4. Appears to be working.
