### ISSUE TITLE
lobby /return doesn't work

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#59]
Installed latest version with new lobby feature but when I tried /return without moving outside lobby area it just teleports to same location and does not return to original spot. Seems like maybe it's not saving original location or something?

**Comment by markrjackson** [comment]
Here is screenshot from log. Notice /return just teleports to same lobby location instead of original location.

![untitled](https://user-images.githubusercontent.com/16080527/38478985-8f7bea5c-3b79-11e8-86e0-d5febe4559f3.png)

**Comment by ObsComp** [comment]
Okay doke, I will take a look , thanks

**Comment by ObsComp** [comment]
Fixed in 9.5. thank you
