### ISSUE TITLE
shop anywhere no longer works with latest update

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#60]
After config changes to /shop and /wallet, the shop anywhere option no longer works and requires trader area.

`<Tool Name="Shop" Enable="True" Shop_Anywhere="True" />`

**Comment by ObsComp** [comment]
YES! sorry, I knew I forgot something. I stripped out the trigger while coding and missed putting it back. I will get it back in for 9.5

**Comment by ObsComp** [comment]
err wait it is there. I just checked. Well I can try it out and will let you know

**Comment by ObsComp** [comment]
Tested to be working with 9.5 but open another ticket if you still have issues
