### ISSUE TITLE
v9.4 - ServerToolsPhrases.xml

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#61]
After repeated fresh installs of 9.4, the following was generated everytime:

        
        
        
        
        

Doesn't seem to affect the game though and contains the updates for v9.4 including lottery etc...

**Comment by Malkadore** [comment]
Reserved

**Comment by ObsComp** [comment]
lol, sorry. Thats updated manually, I forgot about it. I will remember now, sticky noted haha
