### ISSUE TITLE
v9.4 /Bounty (Suggestion)

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#65]
Could you make the amount for a bounty open to the person setting the bounty? 

Some of my members have thousands of currency and are willing to place more down, where as some low level players do not.

It would make it easier than having to repeatedly issue the /bounty command just to raise the value of the bounty.

**Comment by ObsComp** [comment]
yeah I was just getting it into the game first. Gotta make sure no bugs and then refine features. I always want to refine stuff and people ask for more base stuff :)

**Comment by ObsComp** [comment]
Done! added in 9.5
