### ISSUE TITLE
v9.5 /clancommands (Suggestion)

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#67]
When typing /clancommands for the 1st time, the player is given the following message:

![test](https://user-images.githubusercontent.com/38132394/38570941-669e0cc2-3d32-11e8-98d7-f2152de98c80.jpg)

It would be helpful if the response given was "Clan commands are: /clanadd {clan name}".

**Comment by ObsComp** [comment]
okay, can do
