### ISSUE TITLE
REQUEST: add /market (or similar command)

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#68]
Request to add /market (or similar) exactly like you did for /lobby so that players can teleport to central market/vending area and then /return to get back. Or even better would be to put these in a separate xml and let admins define different locations like lobby, market, or whatever.

**Comment by ObsComp** [comment]
hmm, okie

**Comment by ObsComp** [comment]
It is coming v 11 :)  It is all setup
