### ISSUE TITLE
Request: <Tool Name="Custom_Commands">

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#69]
It seems that each response is limited to a single line format.

If I wanted to present a list in a single response, e.g.

Item 1
Item 2

how do I initiate a line break for the same trigger? < .br > doesn't appear to work.

**Comment by ObsComp** [comment]
You can not. I am still getting the custom command ready for dual commands so you can trigger two things at a time. also merging console commands into custom commands so you can use them. It will be in version 10

**Comment by ObsComp** [comment]
Version 10 is out and adds multiple responses
