### ISSUE TITLE
v9.7 <Tool Name="Entity_Cleanup">

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#70]
When Bikes="True" **ALL** existing bikes on the server are removed as well as after inspecting a minibike you are trying to assemble. 

Is this what was intended? I was under the impression this was to remove any bikes that fall through the map. If  it is, could the operation be under its' own listing in the config file as 'Disable minibike' or something to that effect to be more clear or at least in the setup file?

As is, this is a great tool for disabling the minibikes from a server all together. Minibikes have been the bane of server admins for over a year now due to the bugs associated with them, but this tool now  prevents the assembly of a minibike and removal of any existing ones! Thanks!

**Comment by ObsComp** [comment]
Yes it is meant to remove them completely. I agree the name was deceiving. It was explained in the HowTo file but I think many people missed it. It does delete all bikes that are found so please be careful with it. Bikes underground already are sent to the surface and have been for a long time. I merged Entity_Underground into Entity_Cleanup so its been programmed a little cleaner and helps with server load. Underground always sent bikes and bags to the surface but I wanted to merge the options into one config tool. The name is Delete_Bikes in version 10  :)
