### ISSUE TITLE
v9.7 <Tool Name="Clan_Manager">

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#71]
![untitled](https://user-images.githubusercontent.com/38132394/38706826-0008ce36-3ef2-11e8-92ee-91296aac12c4.png)

After creating a clan, the clan tag will OVERRIDE any existing tag, whether it be ADMIN/MOD/SPECIAL etc

Can you allow for multiple tags? e.g. {Donor}{Clan}Player_Name / {Special}{Clan}Player_Name

Can you allow Clan tags color to be customizable in the ServerToolsConfig?

**Update:** Players have reported and I have witnessed intermittently, Clan chat duplicating what is said and publishing in public chat.

**Comment by ObsComp** [comment]
This is being caused by saving the data in a serialized format. It takes the capitalization out. This also happens when I try to store certain data in lists or dictionaries so I am likely missing something.
