### ISSUE TITLE
Prompt for compilation error CS2001

### ISSUE THREAD

**Issue by hugoshao** [dmustanger/7dtd-ServerTools#72]
------ Build started: Project: ServerTools, Configuration: Debug Any CPU ------
CSC : error CS2001: Source file 'C:\Users\Administrator\Desktop\7dtd-ServerTools-9.7\ServerTools\src\StopServer\StopServer.cs' could not be found.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by ObsComp** [comment]
The file is in the master files so you should not see that. Please download and try to compile it again. If you are still seeing this error, manually orient to ServerTools\src\StopServer\StopServer.cs in the current files and add it to the proper directory before compiling ST.

**Comment by hugoshao** [comment]
I still can't compile it, I don't have ServerTools \ src \ StopServer \ StopServer.cs   file in my Src folder

**Comment by ObsComp** [comment]
https://github.com/dmustanger/7dtd-ServerTools/tree/master/ServerTools/src/StopServer
