### ISSUE TITLE
shop anywhere no longer works with latest update

### ISSUE THREAD

**Issue by markrjackson** [dmustanger/7dtd-ServerTools#74]
You said to submit another issue if this is not working. Well here it is.

Even though shop anywhere is enabled it still requires a trader area to purchase. Players can do /shop but not /buy outside trader area.

**Comment by ObsComp** [comment]
I took out the problem in 9.7, are you sure you have the latest update? I can run a test again of course. I will let you know in 30 min

**Comment by ObsComp** [comment]
Just tested in 9.7, working as intended
