### ISSUE TITLE
v9.7 <Tool Name="Entity_Cleanup">

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#75]
<Tool Name="Entity_Cleanup" Items="True" Blocks="True" Falling_Tree="True" Entity_Underground="True" Bikes="False" />

Before v9.7 this tool would notify admins of an entities underground and attempt to resurface the entity... At least I believe it was this tool.

Of course I would be notified of bikes falling through the map and an attempt being made to bring them to the surface with its' coordinates, or even bags if I had <flight check> set to kill when someone fell through the map. I even had an instance where a vulture somehow ended up flying under the map and this wonderful tool was able to locate and resolve such anomalies. Granted, it didn't always re-surface bikes, but occasionally it worked and at least I was given the coordinates so I could attempt myself.

With patch v9.7 this is no longer the case. There is no warning to admins, there are no coords provided and there is no cleanup. I meant to get this posted sooner, since v9.7 has been out for awhile now, sorry got caught up with a few things.

**Comment by ObsComp** [comment]
Okay I will look into this

**Comment by ObsComp** [comment]
I was finding this caused spam on some servers for the admins. It was changed to report only to the output log instead.
