### ISSUE TITLE
Suggestion: <Tool Name="Dead_is_Dead">

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#76]
Is it my imagination or did Server Tools at one point have a 'Dead is Dead' tool?

I don't see any existence of it in v9.7, so if i'm mistaken, is it even possible?

I've had a few players request character wipes, so I've had to manually remove the files from the server.
The player wouldn't be able to use a chat command to issue a character wipe since they are online at the time and the files are Steam ID based. So it raises the question, how could this be possible to implement if at all?

**Comment by ObsComp** [comment]
resetplayerprofile does this. It kicks them from the server and removes their save profile

**Comment by ObsComp** [comment]
rpp steamId will reset the id you input

**Comment by Malkadore** [comment]
sorry im confused. is resetplayerprofile a console command? Never seen it listed before.

**Comment by ObsComp** [comment]
resetplayerprofile seems to be working in version 9.7 and 10. 10 has just come out. Tell me if you have problems with it
