### ISSUE TITLE
Console gui and  Praise to you

### ISSUE THREAD

**Issue by Thodde26** [dmustanger/7dtd-ServerTools#77]
Thank you for your great work. We love it.

@dmustanger 
Good morning, I have a question, there is the possibility to install a console so that opens on a windows root console. I have a project here
/ Zaklinatel / 7dtd-ConsoleGUI
Unfortunately, it will not be developed further Maybe you can do something with it
Best regards
Thorsten (Thodde26) K.

**Comment by ObsComp** [comment]
Hi Thodde. Thank you very much. I will check out the GUI. We are looking to implement a GUI with ST so this is very useful. Dmust has been waiting for a17/beta1 to release before getting back in to coding ST. Version 10.x is the last I am doing until A17 is released but we will definitely look into merging your GUI. Thanks again.

**Comment by Thodde26** [comment]
Great
