### ISSUE TITLE
Config not changing dynamically

### ISSUE THREAD

**Issue by zigstum** [dmustanger/7dtd-ServerTools#8]
I installed as instructed, initially just enabled ping kicker and autosave.
Then today I enabled custom chat commands for the rules etc, and they became enabled, and the customchat XML was created. However, no changes I make to the commandlist are reflected in game. I even deleted the list of commands and it was not rewritten. I have disabled the custom commands in Config.xml, but they are still available on the server, but with the stock messages. I tried giving full 777 permissions to the chatcommand file in case, but no dice.
Does the server need a restart for the changes to take effect?
Is it a bug?

**Comment by dmustanger** [comment]
can you post the CustomChatCommands.xml you are using

**Comment by zigstum** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomCommands>
    <Commands>
        <!-- possible variables {EntityId} {SteamId} {PlayerName} -->
        <Command Command="help" Response="say &quot;[00FF00]Type /commands for a list of chat commands.[-]&quot;" DelayBetweenUses="0" />
        <Command Command="info" Response="say &quot;[00FF00]Type /commands for a list of chat commands.[-]&quot;" DelayBetweenUses="0" />
        <Command Command="rules" Response="say &quot;[00FF00]NO playerkilling, NO griefing, NO raiding, NO admin begging, NO spamming global chat, NO racism, sexism, nationalism, etc. YES generosity, honesty, patience, loyalty and co-operation.[-]&quot;" DelayBetweenUses="0" />
        <Command Command="website" Response ="say &quot;[00FF00]http://7n2l.com.[-]&quot;" DelayBetweenUses="0" />
        <Command Command="ts" Response="say &quot;[00FF00]TS3 Address: 7n2l.com / pass: 7n2l.com.[-]&quot;" DelayBetweenUses="0" />
        <!--Command Command="kickme" Response="kick {EntityId} &quot;You said kick me&quot;" DelayBetweenUses="60" /-->
    </Commands>
</CustomCommands>
```

**Comment by dmustanger** [comment]
are you using linux?

**Comment by zigstum** [comment]
yes :)
```
2016-05-25T14:31:09 0.035 INF System information:
2016-05-25T14:31:09 0.059 INF    OS: Linux 3.13 Ubuntu 14.04 64bit
2016-05-25T14:31:09 0.060 INF    CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (cores: 8)
2016-05-25T14:31:09 0.060 INF    RAM: 32051 MB
2016-05-25T14:31:09 0.061 INF    GPU: Null Device (128 MB)
```

**Comment by dmustanger** [comment]
this may be a bug with linux.Restart the server and see if it updates the commands that way for you.

**Comment by zigstum** [comment]
The server is restarted at 4am every morning.

**Comment by dmustanger** [comment]
did the commands update?

**Comment by zigstum** [comment]
No, unfortunately not :/
The server has also crashed a few times since I made the changes, not that the crashes are related, just to emphasise that it has been restarted many times since I made the changes.
