### ISSUE TITLE
Permissions levels in chat

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#83]
Please add the chat prefix for more permissions levels.

PermissionLevel="0" Prefix="(Admin)" Color="[FF0000]"
PermissionLevel="1" Prefix="(Moder)" Color="[008000]"
......

**Comment by ObsComp** [comment]
There is a range built into it. If you put PermissionLevel="3" Prefix="(Admin)" Color="[FF0000]", everyone listed from 0 - 3 will be admins.

PermissionLevel="6" Prefix="(Moder)" Color="[008000]", would make everyone 4-6 as mods.

The chat color and prefix system is being redone for version 11.
