### ISSUE TITLE
Command fps and Info Ticker does not work

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#85]
Command fps and Info Ticker does not work.

**Comment by ObsComp** [comment]
Fps should load on your server start up. It sets the target fps the server is aiming for.

Infoticker was not working for some people with 10.6, particularly those that use Ravenhearst. 10.7 Fixed this though. Check your output log for any reported errors

**Comment by VitalGrigoryev** [comment]
I use vanilla 16.4 dedicated server (linux version) withot mods, but InfoTicker not work.
