### ISSUE TITLE
Reload config

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#86]
Add the command for reload configuration files.

**Comment by ObsComp** [comment]
It reloads if you delete the file. It loads internally every time you change it.

**Comment by VitalGrigoryev** [comment]
Changes in the settings are not observed after saving and closing the configuration files. On the example of CustomChatCommands.
It is possible that the plugin does not process more than 12 lines.

**Comment by ObsComp** [comment]
It is possible there was a mistake in the entry of one or multiple of your custom commands. Please check the output log for any errors.
