### ISSUE TITLE
KillMsg

### ISSUE THREAD

**Issue by Zipcore** [dmustanger/7dtd-ServerTools#9]
Is it possible to give some stats when someone was being killed. Like by who with which weapon?

**Comment by zigstum** [comment]
No, it's not possible.
Until the latest Alpha the only info you got was 'Player1 eliminated Player2', nothing more.
Now you don't even get that, only "Player died"

**Comment by juniorbond** [comment]
yeas it possible :)
look my server :)

BattleGrounds (PVP & RAID)
Address | 172.96.164.242:27556

**Comment by juniorbond** [comment]
[https://i.imgur.com/xjKJ1Dc.jpg](url)
[https://i.imgur.com/I8PFalL.jpg](url)

**Comment by juniorbond** [comment]
hi
