### ISSUE TITLE
settempunit for player

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#90]
Hi!
How can implement the command settempunit with CustomChatCommands?

not work

      <Command Number="12" Trigger="stu c" Response="settempunit c" Response2="pm {EntityId} &quot;Температура в С&quot;" DelayBetweenUses="0" />

**Comment by ObsComp** [comment]
I think the console command is stu c as well or settempunit celcius. I am not sure if the response was coded to trigger using the player that input it or set as null. I will have to look into this for you. If it runs the command as null, it will not work. I can change that for custom commands. It makes sense to do that.
