### ISSUE TITLE
v10.7 ServerToolsConfig.xml - Tool Name="Jail"

### ISSUE THREAD

**Issue by Malkadore** [dmustanger/7dtd-ServerTools#92]
Typing /jail add {PlayerName} in chat always returns the following response:

`{EntityID} player add {PlayerName} was not found online.`

If I remove 'add' and just type /jail {PlayerName} in chat, the command is displayed in chat and nothing happens.

Is this broken? What is the chat command to send someone to a designated jail position if 'Jail' is enabled?

**Comment by ObsComp** [comment]
I will have to test this out. I made some changes but it sounds like the response is failing. sorry about that. Use the console to jail players for now. You can give access to mods by adding it to the list of commands at a lower level tier

**Comment by Malkadore** [comment]
Unfortunately, the commands fail to work in console also.

**Comment by Malkadore** [comment]
Hit the wrong button lol.

**Comment by TinyDancer410** [comment]
Having the same problem no matter where I type. It's always wrong or the person is offline. Any updates on this?

**Comment by Malkadore** [comment]
There won't be any further development until after A17 Ex is released in a few weeks I would imagine.

**Comment by TinyDancer410** [comment]
ok! thx for the heads up
