### ISSUE TITLE
Mobs and Items Spawner

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#93]
Please add the mobs and items spawner!

Add commands for spawning mobs or items in position:
 /spawnadd spawnername mobs/itemstypes counts timerinterval playerdetectradius spawnradius consolecommandsresponses permissions
 /spawnremove spawnername 

It is necessary to detect the position or presence of players at the spawn point

**Comment by VitalGrigoryev** [comment]
Yes! Detect players in position and spawn mobs or items.

**Comment by ObsComp** [comment]
There is currently a console command to spawn an entities in a radius around a player. You could make a custom command where the player types something like /mobs and it spawns 4 zombies around them. All custom command responses are console operations so you can build your own. I believe you can trigger two console command responses and custom commands now allow command costs for each command listed in the custom command xml file.
