### ISSUE TITLE
Block mobs spawner

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#96]
spawn of mobs or items if the player has installed a block with a specific name (from block.xml) with delay

/addblock blockname mobs/itemstypes counts cost delay consolecommandsresponses permissions
/delblock blockname

This block is needed by the player to create his own farm

**Comment by ObsComp** [comment]
I do not want to link into the world blocks list until A17 is out with the refined world generation and new block code. The current internal code to make this feature is messy and might prove very difficult. I will keep it in mind though.
