### ISSUE TITLE
Economics systems

### ISSUE THREAD

**Issue by VitalGrigoryev** [dmustanger/7dtd-ServerTools#98]
Add or remove coins if player kill mobs or players, craft, set, replase or destroy blocks, teleported.

**Comment by Malkadore** [comment]
I believe an economics system has already been implemented with the Tool Name="Wallet", "Bank" and "Shop" among others...

**Comment by ObsComp** [comment]
Yes there is a base economic system started. It is not refined though. There will be more added to it once A17 drops. Currently you get wallet coins for mob kills, player kills. Just turn on the wallet and set the values you want for each action. You can use wallet coins in the Shop which allows a custom item lineup of your choice and whether they need to be inside a trader space to use it. Each command also has a cost which is paid through the wallet coins. You can set a custom coin name as well.

The bank allows you to deposit wallet coins or in game casino coins. You can withdraw them to either type from the bank. Players can transfer to each other's bank accounts with their unique transfer id. Deposit into the bank takes a 5% fee.

There will be some more things added to this such as losing wallet coins when you die which will motivate players to bank their coins to save them. More coming in a17
